### ISSUE TITLE
NCHC, Update to Dynamic Conference Schedule

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#1]
![28467245-3bde4fce-6dfd-11e7-9d12-25321eea4e47](https://user-images.githubusercontent.com/26412274/28691852-5f452c78-72ec-11e7-9049-6190dad317d3.JPG)

## Requested By:

National Collegiate Hockey Conference, 9/1/17

## Sharing & Intended Use:

Public, Media Relations (Rectangular)

## Template Description:

This is a modification to our previous schedule graphic, Template ID 320. It should accept as many as 6 and as few as 2 games. In cases with fewer games, template should should rearrange to make best use of empty space.

## Dynamic/Programming Considerations:

- White space increases in height when user lowers game total from 6 to 5.
- White content bar rotates and repositions to left side of screen when game total is 4 or lower.
- Gray title bar repositions to bottom of screen in this case as well.
- Finally, text elements for year and week will shift right, under the same circumstances.

## Potential Categories:

Variant of this template exist in Football (Tempalte ID 379), though it contains a different number of fields.

## Example Images / Additional Resources:

![28467280-5c98c10e-6dfd-11e7-845e-a1572e2d6d27](https://user-images.githubusercontent.com/26412274/28692063-0f2a433a-72ed-11e7-9c92-32eb83cb96c6.jpg)
Expanded state, at 5 games.

![preview-full-schedule_4_teams](https://user-images.githubusercontent.com/26412274/28691323-81c482f0-72ea-11e7-8814-3fdf7a70ff51.jpg)
Positioning at 4 or fewer games.

**Comment by ValentineRain** [comment]
This thread's dynamic features can be tracked [here](https://github.com/Aubron/scoreshots/issues/209).

**Comment by ericmoore1** [comment]
This is done and ready for review. 
https://github.com/Aubron/scoreshots/issues/209

**Comment by ValentineRain** [comment]
This needs some additional work still.

**Comment by ericmoore1** [comment]
This item is ready for review. see https://github.com/Aubron/scoreshots/compare/master...template-320

**Comment by ValentineRain** [comment]
As mentioned in the thread above, this one still has a couple of lingering logo issues.

**Comment by ericmoore1** [comment]
Fixed the lingering logo issues. See https://github.com/Aubron/scoreshots/pull/219

**Comment by ValentineRain** [comment]
Hey Eric, the logo issues we were talking about are fixed! Thanks for that!
This is my bad, though; I didn't notice this until just now. The extra conference/sponsor logos on the far left and right are also not repositioning. They're the last two spaces, so I bet neither of us had tried testing them til now.

![conference](https://user-images.githubusercontent.com/26412274/29579862-1eef7ca4-8742-11e7-84bf-4f0aab5d6595.png)

There's a space specified for them in the preview image, though!
This should hopefully be the last revision.

**Comment by ericmoore1** [comment]
Done...

**Comment by ValentineRain** [comment]
Oh, whoops, I'll get to this today! Sorry, I didn't see a testing flag on it so it got lost.

**Comment by ValentineRain** [comment]
This is good to go! Thanks for working so hard on this one.

**Comment by ValentineRain** [comment]
This can be merged~

**Comment by adavila17** [comment]
you should probably tag @Aubron so he gets a notification which will be ignored anyway.

**Comment by Aubron** [comment]
This is going out today. Closing task. Please reopen if additional work is needed.
