### ISSUE TITLE
FSU FinalShot

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#10]
![preview-full-2017-footballscoretemplate](https://user-images.githubusercontent.com/26412274/28797680-1fcce94c-7610-11e7-9cac-2cc8e16b29b8.png)

### Requested by:
Florida State University
### Due Date:
2017-07-21

## Template Description:
None provided in original task.

## Dynamic Considerations:
Requires some fancy shenanigans for logo clipping.

**Comment by ValentineRain** [comment]
You can track the development side of this task [here](https://github.com/Aubron/scoreshots/issues/206#issuecomment-317803465).

**Comment by adavila17** [comment]
![ss_fsu_finalshot](https://user-images.githubusercontent.com/26416133/28979892-a957de7c-7919-11e7-8e33-05689699f1e6.jpg)

**Comment by adavila17** [comment]
ready to test!!!! @Aubron

**Comment by adavila17** [comment]
@val for you to test

**Comment by ValentineRain** [comment]
Hey, I've finally tested this. It seems to work perfectly in the live client, in all browsers, and whatever work development did is already present so I don't think it needs a merge. I'm going to leave this thread open until it's been looked at, in case I missed something, but I think it's good to go.

Does the client already have access to this category or are we waiting until everything in it has been tested? If the former, @lisajohnson11 might want to let them know it's ready.

**Comment by lisajohnson11** [comment]
@ValentineRain Yup, client already has access and I'll let them know this morning that this is also available.

**Comment by adavila17** [comment]
donzo
