### ISSUE TITLE
Villanova Individual Player Highlight, Swimming

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#100]
### Requested by:
Michelle Ruel, Villanova

## Template Description:

![scoreshots example final](https://user-images.githubusercontent.com/26412274/31404481-2f201e18-adca-11e7-98f4-d64eabc4ba39.JPG)

As in the other threads, Villanova would [like a branded template](https://github.com/Aubron/scoreshots-templates/issues/63) to serve a similar purpose to the one above. 

They would like this template to highlight the results of a single athlete, and they've specified that they intend to use this graphic primarily on instagram (in case there are some design considerations that communicates to you).

Have reached out for a due date already.

## Dynamic Considerations:
N/A

**Comment by adavila17** [comment]
![villanova_swimming_finalshot_squarev1](https://user-images.githubusercontent.com/26416133/31461221-db824858-ae96-11e7-8f77-ce62169f1988.jpg)

**Comment by adavila17** [comment]
@ValentineRain ready for client

**Comment by ValentineRain** [comment]
Thanks @adavila17 , I'll send this their way shortly.

**Comment by adavila17** [comment]
Test temp ID: 702

**Comment by ValentineRain** [comment]
This one's good to go. Please add the preview image!

**Comment by adavila17** [comment]
preview added
