### ISSUE TITLE
FSU Basketball Final/SnapShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#102]
![fsu_basketball_finalshot](https://user-images.githubusercontent.com/26416133/31631092-9c6028d6-b286-11e7-901d-9501698233b8.jpg)

**Comment by adavila17** [comment]
![fsu_basketball_finalshotv2](https://user-images.githubusercontent.com/26416133/31682872-5c6a4590-b349-11e7-9315-4315a38dc3cc.jpg)

**Comment by lisajohnson11** [comment]
BASKETBALL
 
Neither one was really exciting our basketball group. I have asked that they send some examples to help guide the process.

**Comment by adavila17** [comment]
This is in another thread I think. 

Assigned for testing: https://github.com/Aubron/scoreshots-templates/issues/124

![fsu_basketball_finalshotv3](https://user-images.githubusercontent.com/26416133/32563437-44bda9fe-c47f-11e7-81bf-2501f9fbd378.jpg)

closing this one.
