### ISSUE TITLE
GAC, Square "Top Performers" Modification

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#103]
![684](https://user-images.githubusercontent.com/26412274/31629346-538f92fe-b281-11e7-8a10-978a2915e65f.jpg)

### Requested by:
GAC, Eric Moyer

## Template Description:
(This is template 684 in Media Relations)

> One question I did have - on the top performers graphic we created, can you add a variable for the number categories used?
> i would say just make the template adjustable...at least add 5 and 7 to the 6 you have available now

## Dynamic Considerations:

I'd like to future proof this template if we're going to give it the dynamic treatment.
Rather than defining an arbitrary range, let's make it selectable from the max number (7) down so we don't have to edit it again later. It will incrementally hide each stat, its associated number, and if applicable, the dividing line within it. 

Where it gets tricky is at 7 stats, because right now we stop at 6.
I asked @adavila17 about this, and he says the solution he's looking for is shrinking the topmost logo space, and reducing the "Top Performers" textline 4pts down to an 18 point font. Both items should be moved up to the top of the template again; this will make room for a seventh stat.

Let Adam or myself know if you have any questions about this in development! Realistically, Adam will be able to better articulate what he wants than I will.

Expect a rectangular copy of this task shortly!

**Comment by kelvin-im** [comment]
Starting dynamic work on this and rectangular template #104.

**Comment by kelvin-im** [comment]
Dynamicized. Used same PR for both square and rectangular templates. Ready for review @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/364

**Comment by ValentineRain** [comment]
Same issue described in #104 applies here!

**Comment by kelvin-im** [comment]
Found out what was going on. The scaling between the bounding box and image is different. Needed to use some extra code to get the correct scaling. Should be good for both templates. Give it another go @ValentineRain.

**Comment by kelvin-im** [comment]
Alright, I've modified the scaling to keep consistency with images. It should prevent the stretching. Give it another go @ValentineRain, when you get the chance.

**Comment by adavila17** [comment]
So this was merged? If so no preview image should be needed just a close on the task.

**Comment by ValentineRain** [comment]
No merge yet! It's on the list though.

**Comment by Aubron** [comment]
Merging!

**Comment by adavila17** [comment]
works already viewable to client
