### ISSUE TITLE
GAC, Rectangular "Top Performers" Modification

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#104]
![685](https://user-images.githubusercontent.com/26412274/31630772-a4850168-b285-11e7-8dc9-7ea4acf1900a.jpg)

### Requested by:
GAC, Eric Moyer

## Template Description:
(This is template 685 in Media Relations)

> One question I did have - on the top performers graphic we created, can you add a variable for the number categories used?
> i would say just make the template adjustable...at least add 5 and 7 to the 6 you have available now

## Dynamic Considerations:

I'd like to future proof this template if we're going to give it the dynamic treatment.
Rather than defining an arbitrary range, let's make it selectable from the max number (7) down so we don't have to edit it again later. It will incrementally hide each stat, its associated number, and if applicable, the dividing line within it. 

Where it gets tricky is at 7 stats, because right now we stop at 6.
I asked @adavila17 about this, and he says the solution he's looking for is shrinking the topmost logo space, and reducing the "Top Performers" textline 4pts down to an 18 point font. Both items should be moved up to the top of the template again; this will make room for a seventh stat.

Let Adam or myself know if you have any questions about this in development! Realistically, Adam will be able to better articulate what he wants than I will.

**Comment by kelvin-im** [comment]
Starting dynamic work on this and square template #103.

**Comment by kelvin-im** [comment]
Dynamicized. Used same PR for both square and rectangular templates. Ready for review @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/364

**Comment by ValentineRain** [comment]
The only issue I see so far is that the topmost logo scales in weird ways when you change the count.
It seems to blow up for some reason. [Check it out](https://drive.google.com/a/imsports.com/file/d/0BwH5-fbQakiyV0ZzaktRU2l5T3M/view?usp=sharing).

To reproduce, set some logos, change the count from 6>7, and then back.

**Comment by kelvin-im** [comment]
Found out what was going on. The scaling between the bounding box and image is different. Needed to use some extra code to get the correct scaling. Should be good for both templates. Give it another go @ValentineRain.

**Comment by ValentineRain** [comment]
@kelvin-im , really close on this one! The scaling is fixed for sure, but it looks like the first time you adjust the count, [it stretches the logo out to max width for that bounding box](https://drive.google.com/a/imsports.com/file/d/0BwH5-fbQakiyQzVPWXdYMkc5V0k/view?usp=sharing).

Again, this behavior is in both!

(Also fun fact, I just noticed that Adam named one of those logo spaces "Bounding Box 1", which I guess I didn't catch in the original run of testing. It seems pretty harmless though so I'm gonna leave it in case it breaks something).

**Comment by kelvin-im** [comment]
Alright, I've modified the scaling to keep consistency with images. It should prevent the stretching. Give it another go @ValentineRain, when you get the chance.

**Comment by ValentineRain** [comment]
Perfect! This is ready to add. Flagging it for merge; we can close it after since there's already a preview image!

**Comment by Aubron** [comment]
Merging!

**Comment by adavila17** [comment]
works no preview needed template already is client viewable.
