### ISSUE TITLE
Dover - Race Scheduleshot

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#105]
### Requested by:
Dover International Speedway, Lynn Sudik

## Template Description:

> Below are links to a few graphics that I thought were cool. I usually create an image to congratulate each week's race winner, so a new template specific to that purpose would be awesome if your team could come up with something. **One other thing that would be helpful is a race schedule shot. The last link is one that I created from a Media Relations template, but if there were one specific to motorsports, (as opposed to the tune-in templates), that would also be helpful.**

## Dynamic Considerations:
This will definitely need to have a selectable number of races. I think @adavila17 is the right choice to design this one and choose the range of races, since racing is kind of his thing!

## Additional Materials:

Here is an example which Ms. Sudik made with the templates we already offer. Let's try to think of ways that we can accommodate racing specifically in this one, so there's less to adapt.

![dmng3ncx0aacrk8](https://user-images.githubusercontent.com/26412274/31631143-c508b104-b286-11e7-86ff-71e0de24847b.png)

**Comment by ValentineRain** [comment]
@marissab1 is pursuing a due date on these and will update us when we know more!

**Comment by marissab1** [comment]
Her response to me asking for a due date: "Sooner would be better than later. The NASCAR season is over in about a month, so I would love to be able to use a new template a few times before then"

**Comment by adavila17** [comment]
Tell them yes you will be able to use logos instead of text if they wish but here's the draft.

![ss_motorsports_scheduleshot](https://user-images.githubusercontent.com/26416133/31779553-60da0934-b4c1-11e7-92dd-d4a16a7f675e.jpg)

**Comment by ValentineRain** [comment]
I might need to tap someone tomorrow to build this one so we can push development along.

**Comment by BillPate** [comment]
I have added the template to the engine @ValentineRain it is #707

**Comment by ValentineRain** [comment]
Hi @BillPate ! Thanks for looking at this. If anything ends up being of about it, it's my fault; I can only roughly approximate Adam's workflow.

I just took a look at it within in the engine and it looks like a few objects are missing. Specifically, the black semi-transparent objects, and the box around the date. I definitely saw them when I was in there, so I'm sure you added them. Was there a step we missed somewhere?

![dover](https://user-images.githubusercontent.com/26412274/32018813-0fd3bc4c-b999-11e7-85da-acbc0abd6ac2.png)

I do need these to be visible before I can have development work on it.
Also ignore the weird coloring. I know how to fix that and I'll take care of it.

**Comment by ValentineRain** [comment]
Thanks for fixing the objects, Aubron. Flagging this for development now.

This template should contain a dropdown for "Number of Races", with the minimum being 1 and the maximum 6. As the count is decreased, the lowest text and logo item on the list is hidden and the list is vertically recentered.

**Comment by Aubron** [comment]
@kelvin-im - I know you're working google drive today, but can you take a break at some point to knock this out?

**Comment by kelvin-im** [comment]
Cool, I'm on it.

**Comment by kelvin-im** [comment]
Dynamicized. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/373

**Comment by ValentineRain** [comment]
My hero

**Comment by ValentineRain** [comment]
This is ready to be merged. When it has been, I'll go ahead and add a preview image.

Also, sorry I forgot to tell you, @BillPate , you can get a little bit better alignment by nudging using the arrow keys, which'll bump an object over by a pixel each time. It's something of an undocumented feature! It probably would have saved you a headache.

A few of the items have been realigned and @kelvin-im took another pass at positioning them. Thanks for the teamwork everyone!

**Comment by ValentineRain** [comment]
Made available to clients. Closing!
