### ISSUE TITLE
Dover - Winning Racer Template

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#106]
### Requested by:
Dover International Speedway, Lynn Sudik

## Template Description:

> Below are links to a few graphics that I thought were cool. **I usually create an image to congratulate each week's race winner, so a new template specific to that purpose would be awesome if your team could come up with something.** 

## Dynamic Considerations:
None.

## Additional Materials:

Here are some examples of other images which Lynn Sudik provided. Note that she did not create them, so they should only be used as reference.

![dmisaeexcae9rx9](https://user-images.githubusercontent.com/26412274/31631266-38f22d20-b287-11e7-972e-f02f5fe07158.jpg)
![dmnpnooxuaey_3s](https://user-images.githubusercontent.com/26412274/31631267-390697d8-b287-11e7-9f89-046f2573ca4a.jpg)
![dmn0qh5xcaacey8](https://user-images.githubusercontent.com/26412274/31631268-39172aa8-b287-11e7-892c-7af2d59f06c0.jpg)
![dmnpp-3w0aa2a8c](https://user-images.githubusercontent.com/26412274/31631270-3b584fe0-b287-11e7-81db-f7eee3446fcc.jpg)

**Comment by ValentineRain** [comment]
Wow, I hit enter way too soon, huh. 
I'll fix it.

**Comment by ValentineRain** [comment]
Fixed it. @marissab1 will eventually update with desired due date!

**Comment by marissab1** [comment]
her response to a desired due date: "Sooner would be better than later. The NASCAR season is over in about a month, so I would love to be able to use a new template a few times before then"

**Comment by adavila17** [comment]
![ss_motorsports_finalshot](https://user-images.githubusercontent.com/26416133/31774397-9aaa88cc-b4b3-11e7-8cb8-c17bb9c80d3d.jpg)

**Comment by marissab1** [comment]
Lynn said "I like the look"

**Comment by ValentineRain** [comment]
I'm going to go ahead and test this; technically no ID was provided to me, so it may not be _ready_, but I know enough of the back end to find it myself!

I'm going to give it a go and adjust it if I need to. Will report back.

**Comment by ValentineRain** [comment]
Tested, it's deliverable. Even though it wasn't given to me officially, I feel confident about this. It's a simple template overall. 

I added a preview image to it, can confirm it's in the engine. Passing it to @marissab1 to deliver and closing this thread.
