### ISSUE TITLE
Dover - Quote Graphic

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#107]
### Requested by:
Dover International Speedway, Lynn Sudik

## Template Description:

An additional template idea from a partner, to fill out the otherwise empty category.
Attached below is an example quote graphic, which Ms. Sudik bundled in with the winning racer examples. We have a few of these in Social and Media Relations we can send her way, so this task may not be strictly necessary. I'm adding this one for review rather than design so we can discuss whether there's value in adding more racing-specific variations.

## Dynamic Considerations:
N/A

## Additional Materials:

Here is an example which Ms. Sudik provided.

![dmrlxfrxkaagvon](https://user-images.githubusercontent.com/26412274/31631352-7b0a0016-b287-11e7-9dad-40b7efb971ad.jpg)

**Comment by adavila17** [comment]
![ss_motorsports_quoteshot1](https://user-images.githubusercontent.com/26416133/31772085-64e6e976-b4ac-11e7-8ef3-c49fa8a37b85.jpg)

**Comment by Aubron** [comment]
@ValentineRain to reach out to client about existing quote scoreshots.

**Comment by marissab1** [comment]
I talked to Lynn, she said she didn't specifically need a racing QuoteShot.

**Comment by ValentineRain** [comment]
Thanks @marissab1 ! I'm closing this for the time being.
