### ISSUE TITLE
Mavericks SnapShot End o Quarter

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#108]
![preview-image](https://user-images.githubusercontent.com/26416133/31632119-d4833bce-b289-11e7-844c-1ba37caff585.jpg)

**Comment by adavila17** [comment]
Out of engine test.

![scoreshot mavericks test](https://user-images.githubusercontent.com/26416133/31665205-15cc9904-b316-11e7-8626-433149f45ed9.png)

**Comment by adavila17** [comment]
Temp ID: 699

**Comment by ValentineRain** [comment]
This is testing well so far, I just want to try the other browsers.
I'm assuming that the fonts don't match the preview image because it'd be a custom font of theirs?

**Comment by ValentineRain** [comment]
This is good.

**Comment by adavila17** [comment]
preview image added
