### ISSUE TITLE
add dynamic code

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#109]
duplicate dynamic code from temp ID: 687 to temp ID: 700

**Comment by adavila17** [comment]
![ss_golf_standingshot](https://user-images.githubusercontent.com/26416133/31680509-83b97726-b342-11e7-9557-0b892870394c.jpg)

**Comment by kelvin-im** [comment]
On it.

**Comment by kelvin-im** [comment]
Dynamicized. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/356

**Comment by ValentineRain** [comment]
Works as intended!~

**Comment by ValentineRain** [comment]
(Will need a preview image after the merge by the way).

**Comment by Aubron** [comment]
Merging!

**Comment by adavila17** [comment]
works already available to clients
