### ISSUE TITLE
GAC Standings Port to Media Relations

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#110]
Hi @adavila17 , we'd like to duplicate the golf standings template that was just designed for the GAC to Media Relations. It's 687, which is this one:

![687](https://user-images.githubusercontent.com/26412274/31680469-64bd77f0-b342-11e7-94ea-2185264a6b42.jpg)

If you could just duplicate that item, and we'll task development to copy the code to whatever the new template turns out to be. This is a low priority task.

**Comment by adavila17** [comment]
@ValentineRain i already made a task.........................

**Comment by ValentineRain** [comment]
Mine predates yours by one minute, but I'll be a good sport. We can close this one.
