### ISSUE TITLE
FSU socialshot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#111]
![fsu_socialshot](https://user-images.githubusercontent.com/26416133/31681095-3d60cb24-b344-11e7-8b96-e40a35823602.jpg)

**Comment by adavila17** [comment]
![fsu_socialshotv2](https://user-images.githubusercontent.com/26416133/31683871-15c170a2-b34c-11e7-839c-7c8cc1d14e15.jpg)

**Comment by lisajohnson11** [comment]
BASKETBALL
 
Neither one was really exciting our basketball group. I have asked that they send some examples to help guide the process.

**Comment by adavila17** [comment]
again new thread made for this one and was approved yesterday and closed.

therefore this gets closed too.
