### ISSUE TITLE
Player/SigningShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#113]
![preview-full-c3mi3gsucaqhayi jpg-large](https://user-images.githubusercontent.com/26416133/31734427-aad9267e-b40c-11e7-930d-4081b9082856.jpg)

**Comment by Aubron** [comment]
Establish a list of stat possibilities.
Push forward ETA Mid-December release

**Comment by Aubron** [comment]
Wanted to put this on your plate. Saw this photo and had a moment of inspiration. The items I like the most are the buttons for position, high school, height, and weight, as well as the state. 
 
Could something be built where perhaps there’s a variable field for the position/sport categories (for example, different graphic for different positions and different graphic for different sports) and an option to turn off the “weight” graphic if it’s for a women’s sport? 
 
Also, some function where we could do the home state as in this graphic would be awesome. I would imagine that putting 50 states in there would be a bit complex, but even if there was a spot somewhere for a PNG where I could load in a state cutout that’d be pretty cool as well. (A PNG slot for a signature scan might be a neat addition – not sure I it’s something I’d be able to use this year but I’m just looking ahead)
 
Obviously signing day is a ways off, but if some of these features could be worked into some of your existing templates that’d be awesome.

**Comment by adavila17** [comment]
Working on this.

**Comment by adavila17** [comment]
progress....

![ss_mediarelations_signingdayshot](https://user-images.githubusercontent.com/26416133/32572011-523f70d6-c497-11e7-8454-5bbaa098e72c.jpg)

**Comment by adavila17** [comment]
![ss_mediarelations_signingdayshotv2](https://user-images.githubusercontent.com/26416133/32572446-8eabae08-c498-11e7-8da4-ceac6355703b.jpg)

**Comment by adavila17** [comment]
@kelvin-im @ericmoore1 

Template ID: 724

This is ready for dev:

Dynamic elements include a drop down for stars labeled "Player Rating" with a list of 1-5. If 4 stars then there will be 4 stars filled out leaving the last one outlined. If 3 then there will be 3 filled out stars leaving the last two outlined. 5 filled stars will be our default.

Drop Down labeled "Home State" with a list of all the states in the US and a .png of home state will appear/replace on the canvas.  Set the angle of each state to -9.5 to match the angle in the preview and elements in the template.

Working on zipping up states .pngs

**Comment by adavila17** [comment]
Here you go the states have been zipped.

[States.zip](https://github.com/Aubron/scoreshots-templates/files/1474963/States.zip)

**Comment by kelvin-im** [comment]
I'll work on this one.

**Comment by kelvin-im** [comment]
Dynamics for player ratings are in place. @adavila17, I needed to unlock the stroke and override properties in the Admin side to properly give those stars an outline. Still in progress, but wanted to let you know.

**Comment by adavila17** [comment]
10-4 have made the change on my end.

**Comment by kelvin-im** [comment]
@adavila17, would it be possible to add a default state image for reference in the template? This way we would have the proper specs already in place when the state is swapped out.

**Comment by adavila17** [comment]
sure I can add the NC .png as a default.

**Comment by adavila17** [comment]
have added in.

**Comment by kelvin-im** [comment]
Alright, home states are succesfully changed in the dynamic template. @Aubron, you may need to add images to the live server. I have the images stored in the "uploads/templatecomponents/States" folder. Ready for review/testing.

PR: https://github.com/Aubron/scoreshots/pull/411

**Comment by ValentineRain** [comment]
Two quick notes on this one; it generally looks very good.

However, if you change the "state" dropdown without changing the "stars" one from its default, the number of stars will drop from 5 to 0, even though 5 is the default. This is easily fixed on the part of the user, but it's inconvenient considering their reaching the "states" dropdown implies they have reviewed and are fine with the default of 5. It makes them work backwards.

Secondly, Nebraska is much wider than the other items and so it bleeds over into the text. I dunno if these are to scale but maybe we should adjust the width on it?

Finally, I like that Puerto Rico is included as a State. It's not really fair that they don't have voting rights so they should at least get ScoreShots representation, that's almost as good, right? However, like Nebraska, their image might be a little too wide.

**Comment by kelvin-im** [comment]
I've added a default player rating of 5 to the template. I've also scaled down NE and PR states as well. Give it another go @ValentineRain, when you have time.
