### ISSUE TITLE
FSU Swim/Dive FinalShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#114]
Temp ID: 703

![fsu_finalshot](https://user-images.githubusercontent.com/26416133/31783609-dc06e982-b4cc-11e7-85a9-a458e3f108ec.jpg)

**Comment by ValentineRain** [comment]
This one needs your ScoreShots logo hack. It's missing it, and therefore crashing.
I should probably write a bug report on this, huh.

![thingo](https://user-images.githubusercontent.com/26412274/31787022-697deae4-b4d8-11e7-8e15-de7e5b3abe6a.png)

**Comment by adavila17** [comment]
probably the scoreshots logo thing

**Comment by adavila17** [comment]
try again

**Comment by ValentineRain** [comment]
Thanks for fixing it!
Reviewing this template, the background needs to be confined to the left hand side or photos with centered action will be unusable! 

![bg](https://user-images.githubusercontent.com/26412274/31792887-88bbc6de-b4eb-11e7-9426-5ca6513579a7.png)

**Comment by ValentineRain** [comment]
We might also want to move the "1" in "1st Place" to the top layer so the right hand side of it can be clicked. I'm not sure that'll help actually, since it's slanted, just an idea.

**Comment by adavila17** [comment]
did the background tested works and closing.
