### ISSUE TITLE
Williams Baptist College, 10-Person Playershot

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#115]
### Requested by:
William Baptist College, mah man Shane Stolz

## Template Description:

> Is there any way to make this graphic where I can fit 10 players into it? We have senior day on Saturday and I would like to have a graphic similar to this for our seniors! ...It would be great if we could have a template with 10 on it! It doesn't have to be that exact one. I can create one if needed! I just thought I would check!

Originally, he asked to make this template support up to 10 players. I discussed it with Adam and there is not sufficient space, so instead we proposed designing an ultrawide template using our newfound ability to make weirdly shaped ones.

![691](https://user-images.githubusercontent.com/26412274/31783623-f037999c-b4cc-11e7-8e17-053a06283e19.jpg)

## Dynamic Considerations:
To future proof this template, we could provide a range of 1-10 (or whatever upper bound @adavila17 thinks is attractive, provided it is at least 10).

**Comment by adavila17** [comment]
what ever.......

![ss_baseball_startingshot7](https://user-images.githubusercontent.com/26416133/31787072-8e642580-b4d8-11e7-81e4-64c9b48284eb.jpg)

**Comment by ValentineRain** [comment]
Looks good. Let's fast track this so we can get it done before your vacation!
Can we put it in Media Relations so that multiple sports can access it?

**Comment by adavila17** [comment]
Test temp ID: 704

**Comment by adavila17** [comment]
It's really for sports not media relations and I don't really see many teams not having baseball.

**Comment by ValentineRain** [comment]
Well, that's a good point, but I guess I mention it because I don't know what sport he intended to use it for. It's a volleyball template. So he might not find or use it if it's in baseball.

**Comment by ValentineRain** [comment]
No issues in testing. I'm going to share it with the client and will make visible/close the topic if they like it. But I do think we should return to this in the future.

**Comment by ValentineRain** [comment]
Uh, actually, @adavila17 I'll have to ask you to add the preview image, since this is a non-standard sized template. I'm afraid that if I add the preview image, I'll overwrite your size hack. Don't know how it works!

**Comment by adavila17** [comment]
added
