### ISSUE TITLE
Ice Hockey StatShot, XML-Driven

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#117]
### Requested by:
Internal, Rick Perko

## Template Description:

@adavila17 or @BillPate to create design. Should contain the fields below, though Rick specifies you should "feel free to modify if you have a good reason".

No specs outside this, sky's the limit.

## Dynamic Considerations:
Will track the following stats:

- Final Score
- Total Shots/Shots on Goal (pie chart)
- Shots on Goal/Saves (pie chart)
- Power Plays/Power Play Goals (pie chart)
- Team v. Team penalty minutes
- Attendance

## Additional Materials

[Link to an example XML file](https://drive.google.com/a/imsports.com/file/d/0BwH5-fbQakiyeDQwZTFlOGdfVHM/view?usp=sharing).

**Comment by ValentineRain** [comment]
Due date Friday, November 17th.

**Comment by adavila17** [comment]
I'm on it.

**Comment by adavila17** [comment]
work in progress in case needed for ss weekly

![ss_hockey_statshot](https://user-images.githubusercontent.com/26416133/32377009-cc2dbed0-c07c-11e7-8e07-9679460be1c3.jpg)

**Comment by adavila17** [comment]
![ss_hockey_statshotv1](https://user-images.githubusercontent.com/26416133/32385368-44fad3d6-c094-11e7-9536-4fd4c6f3736d.jpg)

**Comment by adavila17** [comment]
Better overlay

![ss_hockey_statshotv2](https://user-images.githubusercontent.com/26416133/32387766-e70b2f98-c09b-11e7-94ce-213759bf8c53.jpg)

**Comment by adavila17** [comment]
@kelvin-im @ericmoore1 - DUE DATE Wednesday 11/8

Make Dynamic & XML ready Template ID: 711

SHOTS ON GOAL BARS: should be comparative highest number equals full bar. Leave middle bar with dots alone those are for shots per period each dot represents a period in hockey.

FACEOFF CIRCLE GRAPH: fills counterclockwise  you should only manipulate "your faceoff circle"
Faceoffs are to tally up to get the totals on either end so 36(your team) + 31(opposing team) = 67 total shots as shown in the preview and use whole percentages.

GOALTENDING: "your goaltending circle" fills clockwise while "opponent goaltending circle" fills counterclockwise. Numbers inside circles are to be to the thousandth decimal place.

POWER PLAYS: fills clockwise

PENALTY KILLS: fills clockwise

**Comment by adavila17** [comment]
We need to be able to test on sometime Wednesday major demo the following day with the Hurricanes.

**Comment by kelvin-im** [comment]
In progress.

**Comment by kelvin-im** [comment]
Template is now dynamic and XML driven. @adavila17, there is one change that was needed in the Admin side. There were duplicates of `opp faceoffs`, I've changed the first to `your faceoffs` to get the proper dynamic content. 

After above change, it should be ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/386

**Comment by adavila17** [comment]
@kelvin-im, can you reverse that the first faceoffs in the layer list refers to team 2/opponent and the 2nd "opp faceoffs" refers to your team.

**Comment by kelvin-im** [comment]
The above change was made. Should be ready for review/testing @ValentineRain, when you have the chance.

**Comment by ValentineRain** [comment]
Starting on this now!

@adavila17 , it looks like the background space needs to be confined to the top of the ScoreShot, or else photos are impossible to position.

![top kek](https://user-images.githubusercontent.com/26412274/32750799-bf5cc80a-c891-11e7-95b7-fc5b4eb94802.png)

**Comment by ValentineRain** [comment]
The above screenshot also illustrates that the "Shots on Goal" numbers per period, as well as the final scores and audience, are not being calculated. According to Rick, each of those items is present in the XML file. If that turns out not to be the case, or you have any questions about it, ask, um, not me. I don't do hockey.

I'm going to break my own rule and tag this for a second thing.

**Comment by ValentineRain** [comment]
Also I noticed it's missing a logo space for the social media icons!

**Comment by adavila17** [comment]
attendance was a manual input as noted in the meeting shots on goal per period should be somewhere in the xml. Let me dig.

**Comment by adavila17** [comment]
Also Kelvin's development side probably overwrote my side and checked the full image background box at the top of the admin creation.

**Comment by ValentineRain** [comment]
We fixed the background image part! 
Disregarding the audience count, then all that leaves is the final scores space, and the shots-on-goal-per-period. I took a look at it with @adavila17 , and it looks like that should all be in the file.

**Comment by ValentineRain** [comment]
@adavila17 just came in here to mention that the second team's "shots on goal per period" stuff is wayyyy down in the file for some reason. So, just something to keep an eye out for! :buttshrug:

**Comment by adavila17** [comment]
Look for: 
shotline="##,##,##" first number indicates period 1 second number perioid 2 third period 3 please note there can be overtime/an additional period.

**Comment by kelvin-im** [comment]
Alright, the shots on goal, shots on goal by period, and final scores have all been revised on Dev side. Give it another test @ValentineRain @adavila17, when you have the chance. Same PR as above.

**Comment by ValentineRain** [comment]
All issues are fixed! I see you found that attendance number, too, fancy that. ;P

**Comment by Aubron** [comment]
Merged to live. @ValentineRain handling preview image.

**Comment by adavila17** [comment]
Looks like goaltending circle graphs need attention based off the orange screen grab. If what is being captured by the xml is correct we could have numbers of:

30/31 which is 30 saved shots/31 shots on goal and the number inside the graph would be .968 giving a much fuller circle. 

other side would be:
23/28 which is 23 saved shots/28 shots on goal and the number inside the graph would be .821

**Comment by kelvin-im** [comment]
Per offline discussion with Adam, I've modified the goaltending and penalty kill graphs to display based on the proper calculations. Ready for review/testing @ValentineRain and @adavila17.

**Comment by kelvin-im** [comment]
New PR: https://github.com/Aubron/scoreshots/pull/401

**Comment by ValentineRain** [comment]
@adavila17 and I reviewed this again! It's looking good. We'll merge it again and I'll close this once the preview image is added.

**Comment by ValentineRain** [comment]
It's fixed, in the engine, and available! Thanks for your hard work, @kelvin-im and @adavila17 !
