### ISSUE TITLE
XML Integration for Basketball Statshot

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#118]
### Requested by:
Internal, Rick Perko
Due November 10th.

## Template Description:

This is an update to an existing template, 391, to accept XML files.

![391](https://user-images.githubusercontent.com/26412274/32004026-d620ce4c-b96e-11e7-8ee4-70f52d0e328c.jpg)

## Dynamic Considerations:

I mean this whole thing really is a dynamic consideration, isn't it?

## Additional Materials

[Here's a link to a sample XML file](https://drive.google.com/a/imsports.com/file/d/0BwH5-fbQakiyRHpTX0FKd1BKalk/view?usp=sharing).

**Comment by ValentineRain** [comment]
Due Friday, November 10th.

**Comment by kelvin-im** [comment]
I'll work on this.

**Comment by kelvin-im** [comment]
This template has XML integration. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/382

**Comment by ValentineRain** [comment]
This looks correct; I'm going to review it with Adam or Rick to make sure the stats make sense!

**Comment by ValentineRain** [comment]
Reviewed with both of them, looks like it's calculating everything correctly!
Thanks!

**Comment by Aubron** [comment]
Merging!

**Comment by adavila17** [comment]
already available to clients just added dynamic code
