### ISSUE TITLE
Arkansas State, Minimalist Basketball FinalShot

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#119]
### Requested by:
Arkansas State, Mark Taylor

## Template Description:

> Val,
> 
> Any chance you guys could do something similar to this for our hoops final graphic? And it can be used for anybody.
> 
> We just like the simplicity of it. Just let me know
> 
> Thanks!

Just emphasizing that this is not their design, so we do have to tweak it some (though I realize it's a little bare to begin with!)

## Dynamic Considerations:
None

## Additional Materials:

![unnamed](https://user-images.githubusercontent.com/26412274/32108556-133488a4-bb00-11e7-86b2-0dd70c08e6bc.jpg)

**Comment by ValentineRain** [comment]
I've reached out them in return for a due date on this and pointed them toward what we already have in basketball just in case.

**Comment by ValentineRain** [comment]
They're actually in need of this pretty soon and asked about it again already, so I'm flagging it for high prio for @adavila17 in the morning.

**Comment by adavila17** [comment]
I got it. It's on my agenda for today.

**Comment by adavila17** [comment]
![ss_basketball_finalshot](https://user-images.githubusercontent.com/26416133/32283905-09bc4a5a-befc-11e7-88b5-834b9d72166d.jpg)

**Comment by ValentineRain** [comment]
Looks good! And great turnaround.
Let me send this their way and make sure it jives with them.

**Comment by adavila17** [comment]
well I made a change last minute but oh well. 

![ss_basketball_finalshot](https://user-images.githubusercontent.com/26416133/32284131-9b848f4c-befc-11e7-9e2b-0c67419a982e.jpg)

**Comment by ValentineRain** [comment]
Well, actually, what you said might relate to their feedback. Can you review this and make sure it satisfies what he's asking for?

> This is good start. Could we “square off” the triangle by putting black/grey behind the numbers in case photo is light at the bottom

**Comment by ValentineRain** [comment]
Sent it to him because I do think its what he wants.

**Comment by ValentineRain** [comment]
His response was this. 

> Could we just make logos actual size in line with the numbers in those shaded boxes?

I'm afraid I don't understand what that means. Ideas?

**Comment by adavila17** [comment]
I think I know what they want. Let me re-engineer the template. Uno segundo.

**Comment by adavila17** [comment]
Let's try this. It has the inline aspect I think they are looking for?

![ss_basketball_finalshotv2](https://user-images.githubusercontent.com/26416133/32331798-3791a074-bfba-11e7-97da-37312355920c.jpg)

**Comment by adavila17** [comment]
@ValentineRain  test temp ID: 710

**Comment by ValentineRain** [comment]
It works, I'm adding a preview image. Keep an eye out if they ask for corrections while I'm away! Closing for now.
