### ISSUE TITLE
FSU Volleyball Post Match

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#12]
**Template ID 614** needs a dynamic treatment with a drop down labeled "Number of Sets" user can choose between 2-5 sets. 5 sets will look like the preview image provided. If less than 5 sets keep sets pinned to the left hide any additional sets and content.

![2017-fsu-volleyball-finalshot](https://user-images.githubusercontent.com/26416133/28877433-57606ba8-776a-11e7-9fb4-24a6ae0b8339.jpg)

**Comment by ericmoore1** [comment]
This is a done deal. Ready for testing, and review.

**Comment by adavila17** [comment]
@aubron ready to test.

**Comment by Aubron** [comment]
Please add a Preview image for this to be finalized.
