### ISSUE TITLE
Team-Neutral Variant of the Panda Bear Template 

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#121]
![695](https://user-images.githubusercontent.com/26412274/32245288-ac27093e-be51-11e7-897c-fc8c71f3bb02.jpg)

### Requested by:
MAAC, Rob DeVita

## Template Description:

> Hi –
>  
> I was wondering if there was a way to make the logos in the template attached evenly proportioned? I am also wondering if there could be more matchup graphics that cater to conferences? We are looking for more neutral graphics that highlight each institution evenly.
>  
> Thanks!
> Rob

![wsoc matchup](https://user-images.githubusercontent.com/26412274/32245115-1c89ee9a-be51-11e7-8cb8-9352888ccbda.png)

This is template 695, in Football. This can be our first attempt to provide some options specifically for conferences; it seems like maybe it'll need to go in a general category like Media Relations (though that's not a 100% perfect fit, either).

I've reached out to Mr. DeVita for what other things he'd like us to consider in terms of conference templates. I'll make separate threads for them if I hear back.

Skipping the review step on this one because @rocksprings already discussed and cleared this concept.

## Dynamic Considerations:
None

**Comment by rocksprings** [comment]
Good on you, Mate.

**Comment by ValentineRain** [comment]
Thanks for reminding me to link this on Zendesk.

**Comment by adavila17** [comment]
![ss_matchup_previewshot](https://user-images.githubusercontent.com/26416133/32282475-04d34844-bef8-11e7-9646-cb5ca4930ac4.jpg)

**Comment by adavila17** [comment]
@ValentineRain, for now test I used our old method it seems to work I think the other 2 will have a greater need for the new BG polygon tool. 

Temp ID: 712

**Comment by ValentineRain** [comment]
This works! I'll go ahead and add a preview image. Thank you!
