### ISSUE TITLE
FSU final/snapshot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#124]
What client likes

![wvu_final](https://user-images.githubusercontent.com/26416133/32457487-4c88163a-c2f7-11e7-92ff-f3eda1ade34e.jpg)

**Comment by adavila17** [comment]
![fsu_basketball_finalshotv3](https://user-images.githubusercontent.com/26416133/32458316-0ef8d202-c2fa-11e7-997b-c5e3d2b242cb.jpg)

**Comment by kelvin-im** [comment]
I'll take a look.

**Comment by kelvin-im** [comment]
Dynamicized. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/387

**Comment by ValentineRain** [comment]
Starting on this one.

**Comment by ValentineRain** [comment]
This one works!

**Comment by ValentineRain** [comment]
It'll need a preview image after being merged.

**Comment by Aubron** [comment]
merrrrged

**Comment by adavila17** [comment]
thanks! preview added closing!
