### ISSUE TITLE
Ragin Cajuns, Basketball Final Score

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#128]
### Requested by:
Ragin Cajuns, Jeff Schneider
Public Use

## Template Description:

This is a final score template for Basketball. They do not own the original design, so we'll need to alter it a bit, but they like the general style of it. They also are not requesting this be specifically branded to them, so we can share it.

I'm a little concerned about the colored overlay; I'm not convinced this is currently possible in our engine, though a multiply-styled one may be. Let me know if you run into any stumbling blocks on this one.

They'd like it to be usable by **November 28th.**

## Dynamic Considerations:
N/A Currently

## Additional Materials

![1 by 24th michigan final](https://user-images.githubusercontent.com/26412274/32570677-e209ddf0-c492-11e7-8c2d-f73f94cafbde.jpg)

**Comment by adavila17** [comment]
blah...

![ss_basketball_finalshot11](https://user-images.githubusercontent.com/26416133/32616216-c47bdc68-c53f-11e7-99fd-cd491f70abf0.jpg)

**Comment by ValentineRain** [comment]
Adam to update preview to signify which team is which somehow.
Then send to Jeff.

**Comment by adavila17** [comment]
There @ValentineRain now leave me alone! 

![ss_basketball_finalshot11](https://user-images.githubusercontent.com/26416133/32671151-60a4972c-c614-11e7-98d8-ab96090ec215.jpg)

**Comment by adavila17** [comment]
ready to test temp ID: 718

**Comment by adavila17** [comment]
This is ready for Ragin peeps @ValentineRain just test today so people tonight can use. If they don't like it oh well.

**Comment by ValentineRain** [comment]
It also needs to be sent to them for approval; I mean if you've built it then at this point we can add it either way, but that's an important step.

**Comment by ValentineRain** [comment]
Hey, lets go ahead and push forward on this. I haven't been given any feedback on it but I see no reason to stall, we can make edits later if something isn't right.

**Comment by ValentineRain** [comment]
Jeff approved this template this afternoon.

I've done some testing and it seems to work just fine. There's one behavior which is weird, but doesn't necessarily break anything. @adavila17 might be able to take a look at this.

Basically, every text element on the canvas behaves as if it had a stroke. The stroke is not displayed until you adjust the slider for it, but it's on by default. This stroke matches that which you applied to the "##" symbols in the center.

![stroke](https://user-images.githubusercontent.com/26412274/32750109-9cdc5aea-c88f-11e7-9041-dd33e3168dc6.png)

If you adjust the slider, the text will suddenly have a white stroke.

Can you check and make sure you don't have any stroke overrrides enabled for the other items?
This might not be an issue exclusive to this template, if not.

I'm gonna flag this for design again but this really isn't an issue worth stalling the template over, so you can go ahead and finalize it after you double check your text settings. Just let me know what the result is so I know whether I need to write a report.

**Comment by adavila17** [comment]
Sounds like a dev thing. I did duplicate the "##" to keep the same shear angle because matching twice to 5 times is a pain. So that probably is what's happening but I set everything to 0 for stroke.

**Comment by adavila17** [comment]
I have added the preview but will leave this open in case we want dev or Aubron to patch something.

**Comment by ValentineRain** [comment]
Okay. I'm cool with it being released in this state. It's a really minor issue.

Dinging @Aubron to chime in whenever he has time on whether this is worth fixing. I'm actually kind of leaning toward _no_.

**Comment by ValentineRain** [comment]
@adavila17 says he's also experiencing difficulty adding a preview image. It isn't showing up in the template list even when one has been added. He checked the category formatting and stuff to. I'm not familiar with the back end so I can't offer any advice on that one.

**Comment by ValentineRain** [comment]
Thanks for fixing this @Aubron ! Can confirm it's in there and ready to go.

**Comment by adavila17** [comment]
yay preview shows up now.

**Comment by Aubron** [comment]
"ready to go"

Labels.
Please.
Sounds like it's done, so actually, closing?

**Comment by ValentineRain** [comment]
Yeah, I forgot to flag this for finalization. First time for everything.
It's good now. Closing.
