### ISSUE TITLE
Ragin Cajuns, Halftime

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#129]
### Requested by:
Ragin Cajuns, Jeff Schneider
Public Use

## Template Description:

This is a halftime template for Basketball. They do not own the original design, so we'll need to alter it a bit, but they like the general style of it. They also are not requesting this be specifically branded to them, so we can share it.

His favorite part of this template is the blue-to-clear shift over the background photo. I'm not 100% sure we are capable of reproducing this effect, but it's worth a try. Let me know what you run into.

They'd like it to be usable by **November 28th.**

## Dynamic Considerations:
N/A Currently

## Additional Materials

![2 uconn halftime](https://user-images.githubusercontent.com/26412274/32570756-23726faa-c493-11e7-8703-7fe80f3dd21a.jpg)

**Comment by adavila17** [comment]
So that's an @Aubron question for gradients in templates because you can also see a gradient in the logo backgrounds. Cool but we no has tool. 

I can fake it with a black mist looking overlay but it wouldn't be transparent.

**Comment by adavila17** [comment]
![ss_basketball_snapshot13](https://user-images.githubusercontent.com/26416133/32845794-ab079714-c9f3-11e7-9fb9-0700326dd8a0.jpg)

**Comment by adavila17** [comment]
@ValentineRain test temp ID: 733

**Comment by ValentineRain** [comment]
I sent this one to Jeff. I'm going to test it in the meantime.

**Comment by ValentineRain** [comment]
Jeff likes it! 

The center elements are defaulting to ScoreShots green; it might be intentional in this case but can you confirm?

![ss green](https://user-images.githubusercontent.com/26412274/33082034-cadd3336-cea9-11e7-90ab-f952bdb03dde.png)

**Comment by ValentineRain** [comment]
I think the logos are on too high of a layer, too. They're not getting that neat little effect you gave them in the preview.

![ss green 2](https://user-images.githubusercontent.com/26412274/33082213-38f155aa-ceaa-11e7-85b4-be225cd0de44.png)

Everything else looks good!

**Comment by adavila17** [comment]
Fixed, try again. Do not pass go and definitely don't collect $200.

**Comment by ValentineRain** [comment]
But I want 200$.

**Comment by ValentineRain** [comment]
Yep, both issues are fixed. This is set.

**Comment by ValentineRain** [comment]
Preview image added, template is available.
Closing!~
