### ISSUE TITLE
FSU Soccer GameDay

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#13]
![preview-full-image 1](https://user-images.githubusercontent.com/26412274/28879671-c351a4c0-7770-11e7-911c-85a18debff6e.png)

### Requested by:
Florida State University
### Due Date:
2017-08-01

## Template Description:
Description from client:

I have sent you guys a score graphic file. We would like to base all the graphics on the elements on the drop boxed file. I have attached a list of templates we will need.         

## Dynamic Considerations:
Skewed logo clipping boxes.

**Comment by ValentineRain** [comment]
This template is with development, awaiting functionality described in [this thread](https://github.com/Aubron/scoreshots/issues/206).

**Comment by adavila17** [comment]
Again push back @lisajohnson11 to share with client new idea/thoughts on using volleyball previewshot for soccer.

![ss_fsu_soccer_gameday](https://user-images.githubusercontent.com/26416133/28891946-38f3db5c-779a-11e7-98d1-d5feebb176bc.jpg)

**Comment by lisajohnson11** [comment]
Approved by client.
