### ISSUE TITLE
Ragin Cajuns, Preview

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#130]
### Requested by:
Ragin Cajuns, Jeff Schneider
Public Use

## Template Description:

This is a preview template for Basketball. They do not own the original design, so we'll need to alter it a bit, but they like the general style of it. They also are not requesting this be specifically branded to them, so we can share it.

I don't see anything super worrying about this one, but the Cajuns will probably want to tweak the color of the lower colored area, so a solid, unchangable PNG on top of the template probably isn't the right solution. You might have to play with this a bit.

They'd like it to be usable by **November 28th.**

## Dynamic Considerations:
N/A Currently

## Additional Materials

![3 notre dame next up](https://user-images.githubusercontent.com/26412274/32570916-c0384b5c-c493-11e7-865a-00c021db3879.jpg)

**Comment by adavila17** [comment]
Again @Aubron only thing I can suggest is a 50/50 gray overlay that is available to the user to add colorize filter onto. Would show up as a png overlay to the client.

**Comment by adavila17** [comment]
@ValentineRain @Aubron 

So I made a 50% gray smokey looking overlay and uploading it in the logo step and added a colorize filter to create what's uploaded below. If we can somehow when I am creating this template allow the client to see the overlay and made color changes that would make this template workable. 

PNG overlay:
![smokey-overlay2](https://user-images.githubusercontent.com/26416133/32735765-9c350f78-c863-11e7-8797-16e1e199a591.png)

Results from adding from logo step and colorizing:
![jtjbrbt](https://user-images.githubusercontent.com/26416133/32735791-adf88be0-c863-11e7-9741-adf09438ea6d.jpg)

Thoughts?

**Comment by ValentineRain** [comment]
I like this solution, but I can only speak theoretically since I don't know if this is actually possible.

**Comment by adavila17** [comment]
![ss_basketball_previewshot13](https://user-images.githubusercontent.com/26416133/32857794-12fd60a6-ca17-11e7-9f71-303ea6ee47eb.jpg)

**Comment by adavila17** [comment]
@Aubron 
Already in engine as template ID: 729 need to pull the template in the library of Jackson Donald and overwrite it so that it has the smokey overlay in the background step template is called "template with smoke".

**Comment by adavila17** [comment]
@Aubron nag list.

**Comment by Aubron** [comment]
Template in engine, 729. Please review.

**Comment by adavila17** [comment]
works. just need @ValentineRain to test.

**Comment by ValentineRain** [comment]
One weird bug which occurs with this one; you can resize the white smoke PNG, and some really weird stuff happens. You can do it with the full background, too.

I don't see any reason to delay the template over this, just wondering if you have any controls admin side that might prevent it. This probably happens with other multi background templates anyway.

If not, go ahead and add a preview image to it.

**Comment by adavila17** [comment]
preview added not sure we can lock scaling. I'll look into it later.

**Comment by ValentineRain** [comment]
Cool, leaving this open til we know one way or another. I'll let Jeff know it's ready.

**Comment by ValentineRain** [comment]
Actually I'm going to go ahead and close this for now. If it becomes an issue we'll open a ticket. Nobody is going to try this.
