### ISSUE TITLE
Ragin Cajuns, Branded Halftime

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#131]
### Requested by:
Ragin Cajuns, Jeff Schneider
Private Use

## Template Description:

This is a halftime score template, which they intend to use for multiple sports.
It should be branded to match the last Cajuns template we made for them. Jeff was very adamant that he liked the style of the bottom scoreboard. They don't own the original, though, so we will have to modify it a little.

The due date for this one is December 8th.

## Dynamic Considerations:
N/A Currently

## Additional Materials

![4 dec 8th cajuns only louisville halftime](https://user-images.githubusercontent.com/26412274/32571543-c53041f8-c495-11e7-8f0b-f86f1d6effec.jpeg)

**Comment by adavila17** [comment]
![cajuns_basketball_snapshot](https://user-images.githubusercontent.com/26416133/32611023-7368463e-c532-11e7-8d98-c5fa767efb0a.jpg)

**Comment by adavila17** [comment]
ready to test Temp ID: 722

**Comment by ValentineRain** [comment]
Jeff would like to begin using this immediately. I took a look at it and I don't see any issues! Let's add a preview image and send it his way.
