### ISSUE TITLE
Multi-Player Awards Template

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#133]
### Requested by:
ECAC, Ed Krajewski
Public Use

## Template Description:

The ECAC would like a new take on the multi-player awards templates we produced a while back. No specifics were given, so you can set your imagination free on this one! In order to future proof it, let's aim for something we can scale from 1-6 players. That way we're not asked to produce 5 more variants.

I should stress that whatever it is should not be something currently available in the engine.

No due date provided on this one yet, I don't think. Maybe ask Rick, it came from him.

## Dynamic Considerations:
Should scale from 1-6 players.

## Additional Materials
Here's the one they've been posting regularly.

![unnamed](https://user-images.githubusercontent.com/26412274/32571937-1c0e8916-c497-11e7-8a74-b73d25be2802.jpg)

**Comment by adavila17** [comment]
![ss_mediarelations_playershotsv1](https://user-images.githubusercontent.com/26416133/32731436-c8c0c1a6-c857-11e7-9da4-2ed50cf07b40.jpg)

**Comment by adavila17** [comment]
@ValentineRain don't forget to send off to ECAC guy for approval

**Comment by adavila17** [comment]
Ready for Dev Temp ID 734

Dropdown Labeled "Number of Players" List 2-6
If 2 players template dimensions should be 682 x 576
If 3 players template dimensions should be 1024 x 576
If 4 Players template dimensions should be 1365 x 576
If 5 players template dimensions should be 1706 x 576
If 6 players templates dimensions should be 2018 x 576

Let Val and I know if this is possible before tackling. Or try and tackle and call us out when it no worky.

**Comment by kelvin-im** [comment]
I'll take a look and see.

**Comment by kelvin-im** [comment]
I was able to properly resize the canvas based on above values. Had to write some slightly different methods to keep the objects properly sized. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/415

**Comment by ValentineRain** [comment]
I confess I forgot to send this to Mr. Krajewski until this morning.
Sent it along just now; going to continue testing in the meantime.

**Comment by ValentineRain** [comment]
Hey, so this technically works, though there's some weirdness.

First, the "Number of Players" item is appearing before the background step. I understand why this is desirable; it'll change the canvas size. However, the template still defaults to the "Background" step and the user has no reason to suspect there would be an item before it. I actually spent about a minute looking for the additional, dynamic step before realizing that's where it was.

![thing](https://user-images.githubusercontent.com/26412274/33140720-d1c92030-cf7e-11e7-92f8-41e38208f2a3.png)

So what needs to happen here is that either the template needs to initialize on the "Number of Players" step (which might have some unintended consequences and may still end up confusing users who were expecting background controls like with every other template) or the "Number of Players" step needs to appear in an order consistent with our other dynamic templates.

Either of those solutions is fine, really.

Oh, one other note; the Media Manager button is not responding within this template. This might not be related to anything in this particular template, since we're tracking a few bugs right now related to it. I wanted to point it out just in case though. There's no associated console error.

**Comment by ValentineRain** [comment]
Also this just came in from Mr. Krajewski:

> Val-
> 
> It looks great.
> 
> Can we also have a small line under each player’s name for stats?
> 
> Thanks.

**Comment by kelvin-im** [comment]
Alright, the "Number of Players" has been moved underneath the Background step. The Media Manager didn't have the current Media Manager feature changes, causing the above issue. Branch has been updated now, so Media Manager should work.

Give it another go @ValentineRain.

**Comment by ValentineRain** [comment]
So, this looks good! Let's shelve this until we can chat with @Aubron , though. I think we might need to develop an additional feature to make this future proof.

Basically, what's happening is that since the dynamic positioning dropdown is directly changing the canvas size, it's massively screwed whenever the user decides to adjust the canvas size manually. [Here's a video of this happening](https://drive.google.com/a/imsports.com/file/d/1R5OBuGRhaVFcxRAj8QZWVxYGwF6qNUQv/view?usp=sharing); basically after the first adjustment, it is impossible to restore the template to its original proportions. 

After thinking about it for a bit, I understand why it works this way, and forcibly resetting template elements when the dropdown is changed might have some undesired consequences. I can also see this (admittedly specific) workflow coming up a lot by users who are simply modifying library templates, which may have been made by their peers. In summation, I don't really consider this a bug so much as an unintended side effect of us deciding to make the positioning dropdown affect canvas size.

Unless Aubron has a better idea, I think the safest answer might be to disable the clients ability to resize templates which have dynamic positioning states which correspond to canvas sizes. Is this extra work? Yes, but it's work we'll re-use later when clients like USA Baseball want to lock down those features for their own use anyway.

Thoughts?

**Comment by ValentineRain** [comment]
Oh also @adavila17 was supposed to add that stat field which will necessitate some dev tweaks. I don't think that's happened yet.

**Comment by adavila17** [comment]
this has been updated kelvin you'll need to do a hide/show thing to the new text fields that were added in I think.

**Comment by kelvin-im** [comment]
The Stats text will hide/show when the user changes "Number of Players." Code doesn't need any changes; should still be good for testing.

**Comment by ValentineRain** [comment]
Oh, that's right. I forgot that's the way this one works, nothing is being repositioned. Thanks for the reminder.

As per RTB this morning, we're leaving this one on hold til @Aubron gets back.

**Comment by ValentineRain** [comment]
Hey @kelvin-im , I met with @Aubron and we're going to push forward on the solution of disabling manual template resizing on templates with dynamic elements that do so.

- Add a flag to the statshot for "Can Resize"
- On false, this should hide template resizing.

If I catch you before I leave, we can chat about this but otherwise look to Aubron for guidance on this one!

**Comment by Aubron** [comment]
@ValentineRain - I went ahead and did this. Same PR.

**Comment by ValentineRain** [comment]
Hey, looks good! Let's merge it.
It will need a preview image, as well.

If this is done before EOD I can deliver to Mr. Krajewski and tie a bow on this.

**Comment by adavila17** [comment]
let me know when merged.

**Comment by Aubron** [comment]
@adavila17 - is merged.

**Comment by adavila17** [comment]
preview added
