### ISSUE TITLE
Basketball SS for video

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#135]
Make a SS.

Due date next week.

**Comment by rocksprings** [comment]
Yes, but sooner the better since the hoops season has started.

**Comment by adavila17** [comment]
![ss_basketball_snapshot12](https://user-images.githubusercontent.com/26416133/32662731-8ac9c326-c5f9-11e7-8fcc-37d5b032f571.jpg)

**Comment by rocksprings** [comment]
Please remove Adidas logo.

**Comment by adavila17** [comment]
![ss_basketball_snapshot12](https://user-images.githubusercontent.com/26416133/32663547-4a88c462-c5fc-11e7-87de-97007bb7513a.jpg)

**Comment by ValentineRain** [comment]
Create this for category: ScoreShot.
It should have text for like "Dunk" or something.

**Comment by adavila17** [comment]
So my bad here is a "ScoreShot" template for Basketball.

![ss_basketball_scoreshot](https://user-images.githubusercontent.com/26416133/32670876-2df593ae-c613-11e7-9d16-5b63a1145f17.jpg)

**Comment by rocksprings** [comment]
I don't totally love the scoreboard feature in lower right, I just sort of like it a lot.
Any other opinions on this?
Let's try to make sure it's in the engine by next Friday's Pistons demo.
Gracias.

**Comment by ValentineRain** [comment]
The "12:13 1st Half" will not be visible over any type of video without a solid background behind it.
Might be better to omit.

**Comment by adavila17** [comment]
ready to test @ValentineRain Temp ID: 720

**Comment by ValentineRain** [comment]
Everything in this template is functioning. Can you add a preview image and we'll ship it?

**Comment by adavila17** [comment]
donzo preview added

**Comment by Aubron** [comment]
Reopening this issue, and reverting to review needed. Continued target date of Friday.

**Comment by rocksprings** [comment]
Trying to provide closure on this before weekly SS, if possible.

1. Please change the player's name to something not recognizable.
2. Make the scoreboard in the horizontal way that we have for the football scoreshot.

Hopefully, that will work and get this pushed ahead.
Thanks.
Rick

**Comment by Aubron** [comment]
Per Basecamp, this template is targeted for EoD Thursday.

**Comment by rocksprings** [comment]
As long as we have one preview image that looks like the attached, then I am fine (but it must have the corrections).
![basketball preview image](https://user-images.githubusercontent.com/26558545/32807702-c195b05a-c95e-11e7-9712-265c25b1c679.JPG)

**Comment by Aubron** [comment]
...
......

Okay. So. When you say 'looks like the attached'. do you mean it needs the name changed? or that we need to make a preview image out of a still of a video, instead of something made with the image engine? I think the one @adavila17 has with the filter is a far more compelling case for the template, especially considering that most of our posts are images, but I want to make sure we push this ahead right. Finally.

**Comment by Aubron** [comment]
You also say 'one preview image' as if we can add multiple preview images. That is not a feature. Looking for clarification.

**Comment by adavila17** [comment]
![ss_basketball_scoreshot](https://user-images.githubusercontent.com/26416133/32836403-aa17dff6-c9d7-11e7-81a9-93d6686e95ac.jpg)

**Comment by rocksprings** [comment]
Reposting comments from above:
Trying to provide closure on this before weekly SS, if possible.

Please change the player's name to something not recognizable.
Make the scoreboard in the horizontal way that we have for the football scoreshot.
Hopefully, that will work and get this pushed ahead.

Thanks.
Rick

**Comment by adavila17** [comment]
![ss_basketball_scoreshotv2](https://user-images.githubusercontent.com/26416133/32840324-50053406-c9e5-11e7-946a-57f6d20b4a24.jpg)

like the format two posts above better.

**Comment by rocksprings** [comment]
I didn't see this above, but it's fine with me.
Was trying for football ScoreShot category scoreboard, but I should have included a screen shot from my snipping tool.
Let's get this into the engine and live by EOD tomorrow.
Thanks.

**Comment by adavila17** [comment]
In engine already changed to new approved format. @ValentineRain test temp ID: 720

**Comment by rocksprings** [comment]
We just gave a demo and it wasn't in the engine as a live template.
Just making sure we all are tracking.

**Comment by ValentineRain** [comment]
Rick, it's in the engine _for testing_.
It has the "Testing Needed" flag.

Please let me handle it.

**Comment by ValentineRain** [comment]
Everything in this template functions and matches the new preview image.
I went ahead and made it visible. It's up now.

**Comment by rocksprings** [comment]
It functioned very well during the demo this morning. Emoji.
