### ISSUE TITLE
Snapshot basketball

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#136]
This one was review earlier today nothing wrong with it was just the wrong template the RP wanted originally.

![ss_basketball_snapshot12](https://user-images.githubusercontent.com/26416133/32673600-ce43e432-c61d-11e7-9bb4-16574467e2f2.jpg)

**Comment by adavila17** [comment]
@val can you test before I leave at the very least trying to get this in the engine for basketball people tonight

**Comment by adavila17** [comment]
Temp ID: 719

**Comment by ValentineRain** [comment]
The score text fields should be generic numbers; they're initializing as 44 and 40.
"Half" should probably also be "Period".

![thing](https://user-images.githubusercontent.com/26412274/32674077-b89e14a2-c61f-11e7-85db-41f2fa9e0f07.png)

**Comment by ValentineRain** [comment]
Preview image can be added after that; this looks really good with video.

**Comment by adavila17** [comment]
It's half in Basketball.

**Comment by adavila17** [comment]
yeah fixing the other thing

**Comment by ValentineRain** [comment]
Cool, thanks for checking me on that. I dunno sports words.

**Comment by adavila17** [comment]
preview added
