### ISSUE TITLE
OKC Thunder Branded SS

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#137]
Here's what they do for gameday:

![doc34l4ueaa_yyu](https://user-images.githubusercontent.com/26416133/32745884-102decba-c882-11e7-93fd-7f3666f898b3.jpg)

Here's what we did:

![scoreshot_okcthunder_previewshot](https://user-images.githubusercontent.com/26416133/32745918-297fc6a2-c882-11e7-8de6-8505531db699.png)

@Aubron to move Template from our library into OKC Thunder Library

**Comment by adavila17** [comment]
This is in Jacksondonald's account labeled as: OKC Thunder PreviewShot 11.15

**Comment by rocksprings** [comment]
Can you add the TV network please?

**Comment by adavila17** [comment]
![ss_okc_thunder_preivewshot](https://user-images.githubusercontent.com/26416133/32747260-34247a54-c886-11e7-9514-3afbb17a77cf.png)

**Comment by rocksprings** [comment]
I like this.
It can be created in the engine, right?

**Comment by adavila17** [comment]
Yup worked with Aubron to only apply a branded .png overlay and a player cutout to an existing SS as tasked/mentioned.

The .png overlay in the background can be colorized to their other colors as well. It can be white or one of the two blues they use.

**Comment by adavila17** [comment]
White:
![okc thunder white](https://user-images.githubusercontent.com/26416133/32747554-1d6fda28-c887-11e7-87c2-8e505ec4f463.png)

Blue 1:
![okc_thunder_lightblue](https://user-images.githubusercontent.com/26416133/32747628-5db26718-c887-11e7-87dc-caeb9a10da91.png)

Blue 2:
![okc_thunder_darkblue](https://user-images.githubusercontent.com/26416133/32747729-a96a7ca4-c887-11e7-9a5f-67db2c50d536.png)

**Comment by Aubron** [comment]
This is in the engine as template 721, part of the new category Oklahoma City Thunder. I have added this new category to their demo account.

**Comment by Aubron** [comment]
PS @adavila17 - I figured out what was wrong with the dang thing. You deleted a lot of things with filters, and things that are 'deleted' in the client engine aren't anymore. They're hiding behind the scenes in case they need to be undone. This template loads super fast now.
