### ISSUE TITLE
OKC Branded FinalShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#138]

**Comment by adavila17** [comment]
I will knock this out first thing in the AM 11.14

**Comment by adavila17** [comment]
![ss_finalshot_okc_thunder](https://user-images.githubusercontent.com/26416133/32785872-87631e10-c920-11e7-89b8-e798a639ef9e.jpg)

**Comment by rocksprings** [comment]
We'll need to use Git to approve today unless we want to get together and discuss.
I am fine with this.
Other thoughts by 11am please. . .

**Comment by Aubron** [comment]
Given that this isn't a real template, but just a modified one, I'm fine circumventing protocol for this one. I'm also fine with the template. Standing by to add it to the OKC Thunder category when we're ready.

**Comment by rocksprings** [comment]
Let's add. . .

**Comment by ValentineRain** [comment]
Doesn't hurt my feelings 👍

**Comment by Aubron** [comment]
This has been added to the engine, under the OKC category.

**Comment by adavila17** [comment]
You don't have feelers 🐜 @ValentineRain
