### ISSUE TITLE
Madonna, XC Snapchat and IG 

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#139]
Requested by:

Zach Shore
Available to everyone

Template Description:

![xc-snap-ig-postgame](https://user-images.githubusercontent.com/26416040/32802724-096757e0-c94f-11e7-9c26-b27ab574dcf8.png)

This is a post game template for cross country meets. It lists the overall score of the team and then individual places as well. They would like this size because they use this frequently for snapchat and instagram. 

I think this is the perfect opportunity to begin to add these size templates into the system. Snapchat and Instagram stories are becoming a HUGE deal. 

**They'd like it to be usable ASAP!**

Dynamic Considerations:

I suppose this could be dynamic. For instance how many players you want to showcase. I would imagine we could fill the whole frame up with these lines (we've been getting requests for templates without the need of photos) all the way down to one or two lines.

**Comment by lisajohnson11** [comment]
They also need this for bowling. 
![bowl-snap-ig-postgame](https://user-images.githubusercontent.com/26416040/32841611-ce661682-c9e8-11e7-93dd-27a600c6c825.png)

**Comment by lisajohnson11** [comment]
![golf-snap-ig-postgame](https://user-images.githubusercontent.com/26416040/32841765-38c8cd4e-c9e9-11e7-8b88-6e2cf7f0aa9d.png)

**Comment by adavila17** [comment]
![ss_xcountry_finalshot_poster](https://user-images.githubusercontent.com/26416133/32962015-ce0761a8-cb98-11e7-8409-23f0084e78c5.jpg)

**Comment by ValentineRain** [comment]
Hey, @lisajohnson11 , did we ever get approval for this? I'd like to move forward with testing.

**Comment by lisajohnson11** [comment]
Sent an email to Zach just now. He's usually quick with response!

**Comment by ValentineRain** [comment]
Thank you thank you.

**Comment by lisajohnson11** [comment]
Client approved!

**Comment by lisajohnson11** [comment]
@adavila17 can you send over a template ID when it's ready for @ValentineRain to test please. Thank you!

**Comment by adavila17** [comment]
Test Temp ID: 743

**Comment by Aubron** [comment]
Tested.

**Comment by adavila17** [comment]
preview added.

**Comment by ValentineRain** [comment]
Client contacted, closing!
