### ISSUE TITLE
FSU Soccer Halftime

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#14]
![preview-full-ss_fsu_snapshot_bigscorev2](https://user-images.githubusercontent.com/26412274/28879804-17509356-7771-11e7-99a8-24dfdf2d5c5e.jpg)

### Requested by:
Florida State University
### Due Date:
2017-08-01

## Template Description:
Description from client:

I have sent you guys a score graphic file. We would like to base all the graphics on the elements on the drop boxed file. I have attached a list of templates we will need.         

## Dynamic Considerations:
Skewed logo clipping boxes.

**Comment by ValentineRain** [comment]
This template has been approved by the client and is awaiting development of a skewed logo clipping areas, which can be tracked [here](https://github.com/Aubron/scoreshots/issues/206).

**Comment by adavila17** [comment]
Got some push back since the template didn't really match up well with Volleyball or Cross Country which they like those templates so this is the solution for @lisajohnson11 to send to client for another review.

![ss_fsu_soccer_finalshot](https://user-images.githubusercontent.com/26416133/28891628-2dee909a-7799-11e7-8141-b5e681a585ef.jpg)

**Comment by lisajohnson11** [comment]
Approved by client.

**Comment by ValentineRain** [comment]
Cool, so I just tested this one, and it's good.

Lisa mentioned that maybe these have all been tested already, which would explain why it's going so smoothly? But this one has only had the testing needed flag for 10 hours as of writing.

I'm going to finish testing these FSU templates in the morning; if there are any which have already had work done by a masked stranger, please let me know before I spend any additional hours on them.

**Comment by adavila17** [comment]
done
