### ISSUE TITLE
Madonna, XC Postgame 

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#140]
Requested by:
Zach Shore
Available to everyone

Template Description:

XC Postgame Wide Template 

This is a post game template for cross country meets. It lists the overall score of the team and then individual places as well.

They'd like it to be usable ASAP!

Dynamic Considerations:

I suppose this could be dynamic. For instance how many players you want to showcase.
![xc-postgame](https://user-images.githubusercontent.com/26416040/32841550-9ca7ce88-c9e8-11e7-825a-2e8dda1af2ab.png)

**Comment by lisajohnson11** [comment]
![bowl-postgame](https://user-images.githubusercontent.com/26416040/32841796-530e32e8-c9e9-11e7-9820-fcc360910f3f.png)

**Comment by lisajohnson11** [comment]
![player-golf-postgame](https://user-images.githubusercontent.com/26416040/32841825-6bc4e408-c9e9-11e7-8670-555379d9909c.png)

**Comment by ValentineRain** [comment]
We're going to do a non-dynamic version of this first and we'll return to it later if we need to.

**Comment by adavila17** [comment]
![ss_xcountry_finalshot_1024x576](https://user-images.githubusercontent.com/26416133/32949981-bfeb7350-cb72-11e7-87e2-6942078aa9d8.jpg)

**Comment by adavila17** [comment]
@lisajohnson11 I have a real hard time liking what they sent I modified to at least a 97% approval rating by myself. I think we ship over to them and see how they like it...?

**Comment by lisajohnson11** [comment]
@adavila17  I don't really think that's a good idea, but I'll do it if you're not going to make another one. Is that slanted line object one color? 

I'll send it off right now.

**Comment by adavila17** [comment]
welllllll........ it's in the engine ready to test temp ID: 730

**Comment by lisajohnson11** [comment]
Our client's response.... 

> Lisa,
>  
> Is there a way to either added the lines by the name and times or to make the place/time then the name different colors?
>  
> Thanks

**Comment by adavila17** [comment]
did that in engine with the text editor.

![5jv2pel](https://user-images.githubusercontent.com/26416133/33024390-f57bc58e-cdd8-11e7-9e05-410c1bc9d3c1.png)

**Comment by lisajohnson11** [comment]
I sent an email asking if the multi text color would suffice. Let you know as soon as I hear back.

**Comment by lisajohnson11** [comment]
> Is there no way to add even white separation lines between each set of words?

The above is from Madonna.

**Comment by adavila17** [comment]
I'm just going to put what they want in a category to them and them alone.

**Comment by lisajohnson11** [comment]
I'm going to leave that up to you and @ValentineRain

**Comment by adavila17** [comment]
![ss_xcountry_finalshot_1024x576_v2](https://user-images.githubusercontent.com/26416133/33039042-a56f681c-ce04-11e7-8245-babdc03d2233.jpg)

**Comment by adavila17** [comment]
@ValentineRain only time I'll ask for an emergency test other than tomorrow as well. Cause High Prio.

**Comment by ValentineRain** [comment]
> I'm going to leave that up to you and @ValentineRain
I'm of the opinion we should develop these to client specs. I have a feeling I'm going to be overruled on this one, though. 

Unfortunately, I can't see which category this is going in when I test, or who it will be visible to, so I'm only looking at functionality. At any rate I'm testing it now.

**Comment by ValentineRain** [comment]
I could be wrong, but shouldn't a template like this have its background confined to the space between these lines? Otherwise you cannot adjust to include the far left or right bounds of the image.

![bounds](https://user-images.githubusercontent.com/26412274/33040657-be1ac67c-ce09-11e7-8e29-831d930952e9.png)

**Comment by ValentineRain** [comment]
Logo spaces 2 and 3 need to be in a higher layer, or they will be obscured by other template objects.

![logos](https://user-images.githubusercontent.com/26412274/33040769-164a158c-ce0a-11e7-880d-7ad8d3ddbbc4.png)

**Comment by ValentineRain** [comment]
Just as a quick note for @lisajohnson11 , assuming this is the publically viewable version of this template, @adavila17 's solution for the clients stripes or whatever is pretty good. It's a layer in the palette step, so they can add in solid ones if they want with one click:

![solution](https://user-images.githubusercontent.com/26412274/33040946-aa37904e-ce0a-11e7-921b-fbb382794b69.png)

Do you think this'll do it for them?

**Comment by ValentineRain** [comment]
No other issues. I think I can fix at least one of these by myself, hold on.

**Comment by ValentineRain** [comment]
Hey, so in today's episode of "Val Learns How to Use the Admin Panel", I fixed both the background image clipping (thanks Adam!) and also the logo/text overlap. I dragged the "Image 3" layer beneath the logo and text layers, but above everything else.

Preview image is added; @lisajohnson11 , you can contact your client and let them know it's in the X-Country category! Please point out the stripey thing I pointed out above or they'll think we didn't follow directions. I want happy clients! :DDDDD
