### ISSUE TITLE
Madonna, Basketball FinalShot IG and Snap Story 

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#143]
Requested by:

Zach Shore
Available to everyone

Template Description:

Basketball FinalShot IG and Snapchat Story

I feel like this FinalShot could also be customizable to any sport. 

I think this is the perfect opportunity to begin to add these size templates into the system. Snapchat and Instagram stories are becoming a HUGE deal.

They'd like it soon, but not super important.

Dynamic Considerations:

We could make this dyanmic. They've been using the volleyball FinalShot. 

> The vb final shot is where I got the idea, however, when I went to resize it in scoreshots they white lines all disappear and the date, stadium, location all move, it just didn’t resize properly. Is there a way to create that template in the 1080X1920 size?

![bball snap-insta story postgame](https://user-images.githubusercontent.com/26416040/32844195-bf595e2c-c9ef-11e7-869b-391682591f8d.png)

**Comment by adavila17** [comment]
Soo.... they took our SS and made their own because that's a red flag immediately. Or is this a resize version of our SS.

**Comment by lisajohnson11** [comment]
Well @adavila17 if you read the whole description you would see where it says that they resized the template.

**Comment by adavila17** [comment]
Actually, our's failed to resize and they copied the design.

**Comment by adavila17** [comment]
![r0xuts4](https://user-images.githubusercontent.com/26416133/32844912-8814459c-c9f1-11e7-8b84-7a6413558c86.png)

fails pretty badly too

**Comment by adavila17** [comment]
Temp ID: 744

Need to make this dynamic with a drop down named as "Number of Sets" and a list going from 1 set to 5 sets.

If 3 sets then hide sets 4 and 5.

**Comment by adavila17** [comment]
@lisajohnson11  this is with dev.

**Comment by kelvin-im** [comment]
Dynamics are in. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/455

**Comment by ValentineRain** [comment]
No problems with the dynamic elements of this template! I think we can merge this thing, but one item which @adavila17 will need to review; there's nothing behind the top and bottom of these templates, such that if it is ever resized, there will be a gap (check the corners).

![untitled](https://user-images.githubusercontent.com/26412274/34886318-a62cc53c-f790-11e7-8664-30c2961c9777.png)

I think this is happening because the objects you placed there are skewed in angle, so they don't scale on the X axis normally. Placing a normally oriented square of the same color behind them should do the trick.

**Comment by adavila17** [comment]
We already have a square version of this template the task was to make a poster variation because our resizing tool fails. And here it is failing to do the opposite poster to a square.

**Comment by ValentineRain** [comment]
Hm, that's a fair point @adavila17 . I concede.
I'm tagging this for a merge!

**Comment by Aubron** [comment]
Merged. Will go out with monday deployment.

**Comment by lisajohnson11** [comment]
Hi, I'm still in a holding pattern to tell the client correct?

**Comment by ValentineRain** [comment]
Actually, as of this morning, it's in the engine. @adavila17 just needs to add a preview image; he said it'll be in volleyball with the original.

@adavila17 , if you could update us when that's done, @lisajohnson11 will be good to contact the client and we can clear this one off.

**Comment by adavila17** [comment]
![ss_volleyball_previewshot_poster](https://user-images.githubusercontent.com/26416133/35238055-5b6fc70a-ff7a-11e7-94d8-6d179d5678c3.png)
