### ISSUE TITLE
XML-Capable Basketball Variant of Football Snapshot

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#144]
![645](https://user-images.githubusercontent.com/26412274/32847650-99ca3826-c9f8-11e7-95ae-7162e717dea2.jpg)

## Requested by:

Jeff Schneider, Louisiana Ragin Cajuns
Public

## Template Description:

> Can we update the football stat graphic for basketball to look like the following so when we import the xml file it works.
 I saw the basketball one you had and would prefer to use the football one modified for basketball if possible. Thanks 

## Dynamic Considerations:

This template would need to accept XML files. Obviously we will need to change the base stats of this template to be related to basketball rather than football in order to accommodate this.

## Additional Materials

[Here is an XML file](https://drive.google.com/a/imsports.com/file/d/1PKEL_g9V1z5s1sUmUnBboAHbXSpTnJ6V/view?usp=sharing) from Statcrew that we already had on hand for the last template.

**Comment by ValentineRain** [comment]
Rick has already approved of this so we'll move straight into design. We'll need to duplicate the template into Basketball and replace the stats with relevant ones.

**Comment by adavila17** [comment]
blah blah blah

**Comment by adavila17** [comment]
Ready for dev team temp ID: 728

I am going to assume the XML is working for both men's and women's basketball. The only reason why I bring it up is that men's basketball goes by halves and women's by quarters.

**Comment by adavila17** [comment]
![slack-imgs](https://user-images.githubusercontent.com/26416133/32892506-6bdb892c-caa4-11e7-9f58-1e89855237fb.png)

**Comment by adavila17** [comment]
Making the preview image now.

**Comment by adavila17** [comment]
Preview image made:

![ss_basketball_snapshot14](https://user-images.githubusercontent.com/26416133/32893350-20d93d68-caa7-11e7-99c3-33b6a5f83b22.jpg)

**Comment by kelvin-im** [comment]
I can work on this. @ValentineRain @adavila17 just to confirm; would the XML for both men's and women's be the same as the above file?

**Comment by ValentineRain** [comment]
I am positive I am not qualified to answer that question. @adavila17 might know.

**Comment by adavila17** [comment]
This game has:

<lineprd prd="1" score="31"></lineprd>
<lineprd prd="2" score="37"></lineprd>

indicating a men's game. So the question is does a women's game give an additional two "lineprd prd=...." fields.

**Comment by kelvin-im** [comment]
Dynamics and XML integration has been added for the above XML template. I've used the totals for each team for the calculations. Ready for review/testing @ValentineRain @adavila17. Let me know if this will work for both above cases.

PR: https://github.com/Aubron/scoreshots/pull/408

**Comment by adavila17** [comment]
I'm going to suspect we will want to ask for a women's basketball XML file preferably from the same person who supplied the men's variant.

**Comment by ValentineRain** [comment]
@adavila17 , that's not a bad idea! For the time being though, I don't think the Ragin' Cajuns have requested that. I also don't have one of those on hand. I'm inclined to push this forward for now, and then make edits to it later when we get another XML file.

Insofar as functionality goes, this template works with the statcrew XML files we've been provided already. It can be merged!
