### ISSUE TITLE
Copy Template 694 to Media Relations

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#145]
## Requested by:

Internal, Rick Perko

## Template Description:

We already did this template so we'll just be copying it to Media Relations.

## Dynamic Considerations:

Same behavior found in 694.

## Additional Materials

![694](https://user-images.githubusercontent.com/26412274/32848055-89a3529c-c9f9-11e7-9180-81c714e4079d.jpg)

**Comment by adavila17** [comment]
Even if we copy dynamic code needs to be placed in again.

**Comment by adavila17** [comment]
copied over.

@kelvin-im add dynamic code to template ID: 727

**Comment by ValentineRain** [comment]
Yeah, I know! I'll reach out to development once the base template is in place.

**Comment by ValentineRain** [comment]
Oh, or you could do it, that was fast. Thanks! 👍

**Comment by kelvin-im** [comment]
Copied. Ready for review/testing @adavila17 @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/404

**Comment by ValentineRain** [comment]
Ready for merge.
