### ISSUE TITLE
FSU Soccer Promotions

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#15]
![preview-lightbox-ss_fsu_scheduleshot_v1](https://user-images.githubusercontent.com/26412274/28879927-6b7754ec-7771-11e7-8013-cb9ac6ffa0d7.jpg)

### Requested by:
Florida State University
### Due Date:
2017-08-01

## Template Description:
Description from client:

I have sent you guys a score graphic file. We would like to base all the graphics on the elements on the drop boxed file. I have attached a list of templates we will need.         

## Dynamic Considerations:
Skewed logo clipping boxes.

**Comment by ValentineRain** [comment]
This template has been approved by the client and is awaiting development of a skewed logo clipping areas, which can be tracked [here](https://github.com/Aubron/scoreshots/issues/206).

**Comment by adavila17** [comment]
Just waiting on Aubron's logo clipping solution.

![hju3bzd](https://user-images.githubusercontent.com/26416133/28885938-a3708030-7785-11e7-849c-b2b3b1f5e51e.png)

**Comment by adavila17** [comment]
Still working on this but we did have a change they wanted a social shot not a season schedule no urgency on the schedule till spring.

Anywho redesign to send off to Elliot..

![ss_fsu_soccer_promotions](https://user-images.githubusercontent.com/26416133/28921712-0a28df8a-7825-11e7-8641-382d301766ba.jpg)

**Comment by lisajohnson11** [comment]
Approved by client.

**Comment by adavila17** [comment]
@ValentineRain test both template id's 617 & 622

**Comment by adavila17** [comment]
@ValentineRain test right meow!

**Comment by ValentineRain** [comment]
So I'm working on one of these now. It seems like this one is configured to accept a background photo, and those look fine but it doesn't match the preview image, which is solid-colored.

![untitled](https://user-images.githubusercontent.com/26412274/29225876-ef40eed6-7e9d-11e7-9226-c4f94e4e48c8.png)

That's not really the same as this:

![28921750-2d15913c-7825-11e7-9a05-be8b3ff9956c](https://user-images.githubusercontent.com/26412274/29225883-f707f380-7e9d-11e7-8120-7374da89134b.jpg)

You can manually change the background to have a solid color, but it's kind of a pain in the ass. Would it be possible to add a solid color background in their red, behind the background photo? That way, if they don't add one, they get a solid ScoreShot?

**Comment by ValentineRain** [comment]
Still gonna test this in the other browsers.

**Comment by ValentineRain** [comment]
The "FSU V STAN" line is also team colored rather than set to their branding, which probably works for them if their team colors are set in the right place but I'm not sure.

**Comment by ValentineRain** [comment]
No other observations for that template.

**Comment by adavila17** [comment]
Unfortunately, we can not have a solid color background because if the client were to want an image background we have covered that viewing space. The background is the first layer on all templates before we add objects to the layering menu on the admin side.

**Comment by ValentineRain** [comment]
Cool, then this is done.

**Comment by adavila17** [comment]
donzo
