### ISSUE TITLE
USA Baseball, "Twitter Logo Only"

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#150]
![ntistwitter-logoonly](https://user-images.githubusercontent.com/26412274/33038040-5a9476e6-ce01-11e7-82f4-4a65f341d825.jpg)

## Requested by:

USA Baseball, Brad Young
Private

## Template Description:

> Val,
> 
> I have four PSD files in a Dropbox file that we’d like to turn into templates on ScoreShots.  We do not want these available to everyone.
> 
> How long will it take for these to be transferred into the system?
> 
> https://www.dropbox.com/sh/tjluk2yevn3b01n/AABFLDT8EVzDw-xxcZk7nAr0a?dl=0
> 
> Let me know if you have any issues.
> 
> Thank you!
> 

## Dynamic Considerations:

N/A

## Additional Materials

[Here's a link to their PDF file for this template.](https://drive.google.com/a/imsports.com/file/d/1cXwpaF3EN9bS_ZGU8MW18yEs9FuGsFzw/view?usp=sharing)

**Comment by adavila17** [comment]
5 mins.

**Comment by adavila17** [comment]
this is done Temp ID: 732

**Comment by ValentineRain** [comment]
Testing complete. Took maybe 45 seconds; this template has almost no elements.

**Comment by ValentineRain** [comment]
I added the preview image, but let's leave this open. There's currently an issue adding this category to clients. Frankly, we might want to just make them a new category anyway, given its legacy status and old name. I can't be sure other clients don't have access to it, either.

**Comment by ValentineRain** [comment]
Made the category available to the client; Aubron confirmed they are currently the only ones with access.
Closing!
