### ISSUE TITLE
USA Baseball, "Twitter Paragraph"

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#151]
![ntistwitter-paragraph](https://user-images.githubusercontent.com/26412274/33038072-78f432a2-ce01-11e7-8b8f-be2e732f933f.jpg)

## Requested by:

USA Baseball, Brad Young
Private 

## Template Description:

> Val,
> 
> I have four PSD files in a Dropbox file that we’d like to turn into templates on ScoreShots.  We do not want these available to everyone.
> 
> How long will it take for these to be transferred into the system?
> 
> https://www.dropbox.com/sh/tjluk2yevn3b01n/AABFLDT8EVzDw-xxcZk7nAr0a?dl=0
> 
> Let me know if you have any issues.
> 
> Thank you!
> 

## Dynamic Considerations:

N/A

## Additional Materials

[Here's a link to their PDF file for this template.](https://drive.google.com/a/imsports.com/file/d/1t560GGGxJJt0GXkwmeGhz4W8k2ZUbD7W/view?usp=sharing)

**Comment by adavila17** [comment]
technically the same as another one just with a bigger text box. 30 mins or so.

**Comment by adavila17** [comment]
@ValentineRain done test temp ID: 735

**Comment by ValentineRain** [comment]
I had to adjust the layering of the logo space; it was appearing behind the gradient and white shine effect.
Everything works; I'm making it visible to the client so they have the thing. Will close when I get feedback.

**Comment by ValentineRain** [comment]
> Val,
> 
> I was able to test out the templates that you loaded onto our account and I think these are very close to what we’ll need. No problem with not being able to do the gradient map to a certain portion of the image, I was just hoping that would be possible since I did notice you had the “spotify” effect already built in. 
> 
> Brad and I will meet Monday to discuss any other tweaks or restrictions we will want to build in to limit how much regional directors can manipulate. Thanks so much for getting these templates created. I hope you have a great Thanksgiving!
> 
> Thanks,

Will update when I hear back from them again.

**Comment by ValentineRain** [comment]
They're supposed to get back to me sometime this week. They're using the templates though and it sounds like they just want us to update them if we ever get the ability to apply filters to selective areas of an image. Closing for now.
