### ISSUE TITLE
USA Baseball, "Twitter Short Content 4-Line"

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#153]
![ntistwitter-shortcontent-4line](https://user-images.githubusercontent.com/26412274/33038211-e13765c8-ce01-11e7-8ec7-1a3d6dd9b7ad.jpg)

## Requested by:

USA Baseball, Brad Young
Private

## Template Description:

> Val,
> 
> I have four PSD files in a Dropbox file that we’d like to turn into templates on ScoreShots.  We do not want these available to everyone.
> 
> How long will it take for these to be transferred into the system?
> 
> https://www.dropbox.com/sh/tjluk2yevn3b01n/AABFLDT8EVzDw-xxcZk7nAr0a?dl=0
> 
> Let me know if you have any issues.
> 
> Thank you!
> 

## Dynamic Considerations:

N/A

## Additional Materials

[Here's a link to their PDF file for this template.](https://drive.google.com/a/imsports.com/file/d/1ysqXV8tod7qaLOnCbIsm3Hk9Pyawisma/view?usp=sharing)

**Comment by ValentineRain** [comment]
This is the last of the requests. Please let me know before EOD if any of these contain elements you think are troubling (I'm a little worried about the selective color overlay), and a date by which you think you could have them completed.

**Comment by adavila17** [comment]
30 mins

**Comment by adavila17** [comment]
this is what we can do. That gradient mask, known as the Spotify filter in our engine, is being applied to a specific area and we can't do that. This is the absolute best I can do. Please see what they say.

![playershot out of engine](https://user-images.githubusercontent.com/26416133/33074044-c98bb6d6-ce92-11e7-82cd-d08c1aa17be7.png)

**Comment by ValentineRain** [comment]
Thanks @adavila17 ; I'm gonna send it their way and make sure they're okay with it. I think it looks pretty damn close.

**Comment by ValentineRain** [comment]
I haven't received any complaints on this, though they've gone a little dark this week.
I'd like to push forward on this. Template ID?

**Comment by adavila17** [comment]
Temp ID: 731

**Comment by ValentineRain** [comment]
This is good to go, please put a preview image on it.
