### ISSUE TITLE
Pistons - Player of the Game Template

### ISSUE THREAD

**Issue by marissab1** [Aubron/scoreshots-templates#156]
## Requested by:

Detroit Pistons, Douglas Wernert
Private, Due December 4th
1 of 6 Prepaid

## Template Description:

![playerofthegame_jeep](https://user-images.githubusercontent.com/31700405/33441185-111d436e-d5c0-11e7-9642-352523c0dfc0.jpg)

[This is a link to the PSD file.](https://drive.google.com/a/imsports.com/file/d/1vDanNbw6Gi4_Q_hL3h-DvBnVxubUQUaP/view?usp=sharing)

**Comment by marissab1** [comment]
[](https://drive.google.com/a/imsports.com/file/d/1vDanNbw6Gi4_Q_hL3h-DvBnVxubUQUaP/view?usp=sharing)

**Comment by adavila17** [comment]
@ValentineRain test temp ID: 738

**Comment by ValentineRain** [comment]
This one is pretty good but doesn't match their specs!
They're displaying a template with 2 background photo spaces, and we're giving them one with one background, and a clipped player cutout.

![pistons](https://user-images.githubusercontent.com/26412274/33500952-becc499a-d6a8-11e7-9242-d5941dd2a59c.png)

I do like the thought you put in by including a player cutout in this space if they need it! I don't see any reason we can't keep that as an alternative. But it doesn't match what they're looking for, and looks kind of odd without the accompanying right hand background.

Also the dividing lines between the scores are a little thinner in our version.

Other than that it looks good.

**Comment by ValentineRain** [comment]
Okay, I see what you mean now about the cutout space.
I don't like this solution so I'd like to revise this once you get the background polygon tool.

In that case, take a look at the right-hand side of that right-hand cutout, which is off just a few pixels on the edge. You can see a gap.

**Comment by adavila17** [comment]
fixed adding preview. Someone needs to add category to client account and inform them template is ready.

**Comment by ValentineRain** [comment]
Thanks. Category has been added. I'm going to reach out to them to let them know where to find it.
