### ISSUE TITLE
Beach Volleyball?!

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#159]
## Requested by:

UNCW, Tom Riordan
Public

## Template Description:

> Good afternoon!
> I’ve attached a PSD of a starting lineup for beach volleyball. Yes, beach volleyball. We’re one of about 70 schools with the sport and it’s growing. I’d be happy to share with the other clients. No xml integration is needed, pretty simple design. The font used is Forza, but any font would/should work.
>  
> Thanks!

Uh, this could go in ... in Volleyball I think?

## Dynamic Considerations:

N/A

## Additional Materials

[Here's a link to his PSD file.](https://drive.google.com/a/imsports.com/file/d/15phbWs8jJd-8zKg7uPbyOBEBKLOTBo1s/view?usp=sharing) We might consider putting our own spin on it instead, since he isn't requesting it to-order.

**Comment by ValentineRain** [comment]
Hey @adavila17 , can confirm client has specified this one is public.
[He also gave us this second PSD](https://drive.google.com/a/imsports.com/file/d/1lTWN2ckFD7QGgC9p6ebrfz4gLYb8FT7j/view?usp=sharing) which is a little more filled out. Maybe this will help you?

This might need some dynamic shenanigans after all. I will reserve judgement until I see your version.

**Comment by adavila17** [comment]
Well, that font cost $199 for one user sooo........ they'll just have to change it on their end.

**Comment by adavila17** [comment]
@Aubron another template with an overlay png on the background step. We will need you to replace the template coming out of the admin side with the template saved in the library as "beach volleyball".

Thanks,

**Comment by Aubron** [comment]
Done. add ur preview image.

**Comment by adavila17** [comment]
Preview added

**Comment by ValentineRain** [comment]
Client has been contacted. Closing!
