### ISSUE TITLE
FSU Cross Country National Day

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#16]
![preview-full-ss_fsu_xcountry_previewshot](https://user-images.githubusercontent.com/26412274/28880005-ad2a06dc-7771-11e7-9992-fca421701bd0.jpg)

### Requested by:
Florida State University
### Due Date:
2017-08-01

## Template Description:
Description from client:

I have sent you guys a score graphic file. We would like to base all the graphics on the elements on the drop boxed file. I have attached a list of templates we will need.         

## Dynamic Considerations:
Skewed logo clipping boxes.

**Comment by ValentineRain** [comment]
This has been sent to FSU for approval.

**Comment by adavila17** [comment]
Temp ID 619

**Comment by adavila17** [comment]
@aubron need template ID 619 changed from a FinalShot to a PreviewShot.
