### ISSUE TITLE
Golf ScoreShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#160]
Any comments? template only took like 5 mins to create on the back end.

![ss_golf_scoreshot_v1](https://user-images.githubusercontent.com/26416133/33673651-5facab40-da7b-11e7-96ae-e92d8c2c8545.jpg)

**Comment by rocksprings** [comment]
I think this looks great, Adam.
But maybe spell Michael with the "a" before the "e."
Can we get this live in the engine by end of day, Wednesday for our PGA Tour demo?
Rick

**Comment by adavila17** [comment]
updated here.

![ss_golf_scoreshot_v2](https://user-images.githubusercontent.com/26416133/34114415-bd433cb0-e3e0-11e7-83aa-098117d37131.jpg)

**Comment by adavila17** [comment]
@Aubron test temp ID: 740

**Comment by rocksprings** [comment]
Grassy ass.

**Comment by Aubron** [comment]
Testing complete, looks good. 👍

**Comment by rocksprings** [comment]
Demo is Thursday at 11:30.
Can we have this live in the engine sometime tamale?

**Comment by adavila17** [comment]
preview added.
