### ISSUE TITLE
FSU Cross Country Results

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#17]
![preview-full-ss_fsu_xcountry_playershot](https://user-images.githubusercontent.com/26412274/28880109-0259a22a-7772-11e7-9b9c-836d8d22d1e1.jpg)

### Requested by:
Florida State University
### Due Date:
2017-08-01

## Template Description:
Description from client:

I have sent you guys a score graphic file. We would like to base all the graphics on the elements on the drop boxed file. I have attached a list of templates we will need.         

## Dynamic Considerations:
Skewed logo clipping boxes.

**Comment by ValentineRain** [comment]
Has been sent to FSU and is awaiting approval.

**Comment by adavila17** [comment]
I'll wait for Lisa to switch the label but the templates for Cross Country are approved via email from FSU.

**Comment by adavila17** [comment]
Template ID 618

**Comment by adavila17** [comment]
@Aubron ready to test
