### ISSUE TITLE
FSU Volleyball Match Preview

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#18]
![preview-full-ss_fsu_volley_previewshot_v1](https://user-images.githubusercontent.com/26412274/28880176-365cb03a-7772-11e7-8bdf-cff0e1038081.jpg)

### Requested by:
Florida State University
### Due Date:
2017-08-01

## Template Description:
Description from client:

I have sent you guys a score graphic file. We would like to base all the graphics on the elements on the drop boxed file. I have attached a list of templates we will need.         

## Dynamic Considerations:
Skewed logo clipping boxes.

**Comment by ValentineRain** [comment]
Was sent to FSU and approved. Next step is to design within ScoreShots engine for testing.

**Comment by adavila17** [comment]
Temp ID 615

**Comment by adavila17** [comment]
@Aubron this is ready to test.
