### ISSUE TITLE
FSU Volleyball Post Match

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#19]
### Requested by:
Florida State University
### Due Date:
2017-08-01

## Template Description:
Description from client:

I have sent you guys a score graphic file. We would like to base all the graphics on the elements on the drop boxed file. I have attached a list of templates we will need.         

## Dynamic Considerations:
Skewed logo clipping boxes.

**Comment by ValentineRain** [comment]
Closing, was made before I got here. Ignore.
