### ISSUE TITLE
FSU Volleyball AVCA Rankings

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#20]
![preview-full-ss_fsu_volley_pollshot](https://user-images.githubusercontent.com/26412274/28880355-cbaf3cac-7772-11e7-86b9-15ce697614c2.jpg)

### Requested by:
Florida State University
### Due Date:
2017-08-01

## Template Description:
Description from client:

I have sent you guys a score graphic file. We would like to base all the graphics on the elements on the drop boxed file. I have attached a list of templates we will need.         

## Dynamic Considerations:
Skewed logo clipping boxes.

**Comment by ValentineRain** [comment]
Approved by FSU, awaiting design in engine for testing.

**Comment by adavila17** [comment]
Temp ID 616

**Comment by adavila17** [comment]
@Aubron this is ready to test today.
