### ISSUE TITLE
Volleyball StartingShot with Formations

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#21]
### Requested by:
Internal
### Due Date:
2017-08-04

## Template Description:
Rick's original description: Create StartingShot for volleyball that lists the six players on the court (like our soccer one).

## Dynamic Considerations:
One dropdown for selecting player formations.

## Additional Files
Here's a preview of the soccer one, on which this should be based.

![597](https://user-images.githubusercontent.com/26412274/28880570-7c714602-7773-11e7-8a96-708e30c74b4e.jpg)

**Comment by adavila17** [comment]
![ss_volleyball_startingshot4](https://user-images.githubusercontent.com/26416133/29027585-4b154f38-7b4f-11e7-92f4-94f89fea63de.jpg)

**Comment by ValentineRain** [comment]
Half court, add a net because Aubron doesn't know where it goes.

**Comment by adavila17** [comment]
![ss_volleyball_startingshot4](https://user-images.githubusercontent.com/26416133/29123283-37df70ac-7ce3-11e7-82bf-db6fd12c1c24.jpg)

**Comment by ValentineRain** [comment]
Add Val to the preview image please he wants to play women's volleyball. Rick really wants Erica Moore.

**Comment by ValentineRain** [comment]
Maybe Kelvinitta.

**Comment by adavila17** [comment]
Will wrap this up on monday fo sho.

**Comment by adavila17** [comment]
test temp ID 626

**Comment by ValentineRain** [comment]
This is testing well so far. Just want to point out that the logos/text are not evenly spaced. Are they supposed to be?

(The red bars are a single, duplicated object for perspective)
![untitled-1](https://user-images.githubusercontent.com/26412274/29385039-4e0bb13a-82a4-11e7-83f2-02091dae8a7e.png)

**Comment by ValentineRain** [comment]
I would also expect the top two logos to appear in the logo list before all of the player ones, since they'll be viewed first chronologically. Currently they're at the bottom. This might be a thing that I can fix, actually.

![untitled](https://user-images.githubusercontent.com/26412274/29385132-a1495a82-82a4-11e7-83eb-5aea1f04eed2.png)

**Comment by ValentineRain** [comment]
Final note, and I think I've asked @Aubron about this before so sorry if it's repetitive, but this template has a background step with no place to put a background. Even the blue here is configured in the palette step. Is it possible to remove that step entirely or will that break stuff?

...it sounds like it would break stuff

**Comment by ValentineRain** [comment]
On final review, the first two issues above should be looked at by Adam; the first one might be intentional, so I leave that to you. The second one should be fixable by the admin panel.

**Comment by adavila17** [comment]
@ValentineRain you just need to be testing to make sure things work. The layer order is how it's always been player cut-outs and then logos.

**Comment by adavila17** [comment]
Fixed the one issue I see.
