### ISSUE TITLE
Square Variant of QuoteShot #1

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#22]
### Requested by:
CACC Athletics
### Due Date:
2017-08-04

## Template Description:
Doug Debiase of CACC says:

He would like a square version of these created. His reasoning is that he likes the design, and wants to use one version as a sort of preview image, while incorporating the other (with full text) into the article itself. He would like them to appear as if they were of the same "series".

## Dynamic Considerations:
N/A

## Additional Materials:
![preview-full-preview-full-ss_mediarelations_quoteshot2](https://user-images.githubusercontent.com/26412274/28880782-10bbe2ae-7774-11e7-8eaa-f25c3ad008f2.jpg)

**Comment by adavila17** [comment]
square version quick 10 min update.

![ss_mediarelations_quoteshot2_square](https://user-images.githubusercontent.com/26416133/28930181-21d97926-7840-11e7-84bb-34dd26f073d0.jpg)

**Comment by ValentineRain** [comment]
Good to go.

**Comment by adavila17** [comment]
Test ID 623

**Comment by ValentineRain** [comment]
This one works!
