### ISSUE TITLE
Square Variant of QuoteShot #2

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#23]
### Requested by:
CACC Athletics
### Due Date:
2017-08-04

## Template Description:
Doug Debiase of CACC says:

He would like a square version of these created. His reasoning is that he likes the design, and wants to use one version as a sort of preview image, while incorporating the other (with full text) into the article itself. He would like them to appear as if they were of the same "series".

## Dynamic Considerations:
N/A

## Additional Materials:
Preview of original, rectangular.
![preview-full-preview-full-ss_mediarelations_quoteshot1](https://user-images.githubusercontent.com/26412274/28880762-0448a048-7774-11e7-9020-3af229846b2b.jpg)

**Comment by adavila17** [comment]
quick 10 min update

![ss_mediarelations_quoteshot1_square](https://user-images.githubusercontent.com/26416133/28930308-91e31312-7840-11e7-8505-f5da3297d918.jpg)

**Comment by ValentineRain** [comment]
Adam to remove attribution object and replace with styled text.

**Comment by adavila17** [comment]
Test temp 624

**Comment by ValentineRain** [comment]
This one is also ready to go.
