### ISSUE TITLE
Baseball Previewshot

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#24]
### Requested by:
CACC Athletics
### Due Date:
2017-08-04

## Template Description:
Doug Debiase of CACC says:

He really likes the template below, for a variety of reasons, and would like to see a square previewshot with the same design. 
His request would have the following features:

- The same dual-image setup. He wants to apply team-colored filters to both sides.
- Not be focused on pitchers. Instead of "head to head pitching" and stats, he will use it as a previewshot, with game information
- Retain the angled layout, as well as the half-floating team logo positioning
- Be square

## Dynamic Considerations:
N/A

## Additional Materials
Statshot, original:
![preview-full-493](https://user-images.githubusercontent.com/26412274/28880920-76f9cc8e-7774-11e7-9bfb-8f8f59cc2a03.jpg)

**Comment by adavila17** [comment]
I'm going to suggest we push for the rectangle and not square.

![ss_baseball_previewshot8](https://user-images.githubusercontent.com/26416133/29073431-94436468-7c19-11e7-97a6-2f44b325d599.jpg)

**Comment by ValentineRain** [comment]
To send to client for approval. Is probably fine.

**Comment by adavila17** [comment]
Any word on this?

**Comment by ValentineRain** [comment]
Sent five days ago, no response.
I consider his grace period passed in terms of ability to object.

**Comment by adavila17** [comment]
I mean I can make it and it'll be ready in the engine. Odd that there's been no response.

**Comment by ValentineRain** [comment]
He finally responded, he was out of the office.

> Hi Val:
>  
> Sorry for the delay in responding. I was on vacation when you sent this and it got lost in my inbox. I really like the gameday preview in baseball. It's simple and clean and will come across great in social media.
>  
> Thanks for your help with this,
> Doug

Sounds like he loves it! Let me know when it's available for testing.

**Comment by ValentineRain** [comment]
Ready to test this whenever it's prep.

**Comment by ValentineRain** [comment]
Hey @adavila17 , this one fell off my radar. Can I get you to fast-track this one for me please?

**Comment by adavila17** [comment]
test temp id 681

**Comment by ValentineRain** [comment]
There's only one background space! There should be two, each clipped to its respective part of the template.

![bg](https://user-images.githubusercontent.com/26412274/31091941-bb3e5e42-a77a-11e7-94e4-f853a7c06ac3.png)

Everything else looks good. Could you tweak that, add a preview image, and let me know when it's good to go?

**Comment by ValentineRain** [comment]
Thanks Adam, it needs a preview image.
