### ISSUE TITLE
Long-Lost Scheduleshot

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#29]
![28929026-f16c0662-783c-11e7-88b3-b4c3ac9a5e5c](https://user-images.githubusercontent.com/26412274/29081400-7cf4c4de-7c30-11e7-90d0-6a1b85856f8d.png)

### Requested by:
Rick, Internal

## Template Description:
This is the scheduling template which sort of vanished off of everyone's radar.

## Dynamic Considerations:
Number of games should be configurable via dropdown from 10, down to (presumably) 2.

**Comment by ValentineRain** [comment]
This template is currently in development [here](https://github.com/Aubron/scoreshots/issues/123).

**Comment by ericmoore1** [comment]
This item is ready for review. See https://github.com/Aubron/scoreshots/pull/234

**Comment by adavila17** [comment]
Adding preview image now.

**Comment by adavila17** [comment]
@ValentineRain this can be closed.

**Comment by ValentineRain** [comment]
Got it, thanks!
