### ISSUE TITLE
Conference Standings Template

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#3]
## Requested By:

Internal, by Rick Perko. August 4th delivery date.

## Sharing & Intended Use:

Public, presumably Media Relations.

## Template Description:

Description from Rick:
> It would be dynamic and include wins and losses for both conference play and overall. It will also need bifurcation into two divisions (e.g., east and west). Would be very cool if there was a way to modify by simply bumping a team up or down.

## Dynamic/Programming Considerations:

- Dropdown, number of games : 5 , 6, 7 and 8 (not necessarily symmetrical)

## Example Images / Additional Resources:

Here's a screenshot of a website Rick linked as an example for this task.
![standings](https://user-images.githubusercontent.com/26412274/28692795-2452e188-72f0-11e7-822b-a6dc8d516dfe.png)

**Comment by Aubron** [comment]
Meeting 8/2/17: Adam to make non-dynamic version to start, and approach dynamic stuff later.

**Comment by adavila17** [comment]
Designed.

![ss_conference_standings_v1](https://user-images.githubusercontent.com/26416133/28981669-aecf33da-7920-11e7-9efe-3cd163f63e0b.jpg)

**Comment by ValentineRain** [comment]
Mocks will be made by Adam showing 5v5 and 6v6, this will be dynamic now.

**Comment by adavila17** [comment]
![ss_conference_standings_ 5](https://user-images.githubusercontent.com/26416133/29132426-31add2bc-7cfe-11e7-9844-85b111bcbae9.jpg)

![ss_conference_standings_ 6](https://user-images.githubusercontent.com/26416133/29133006-0c3d7d8c-7d00-11e7-9a65-4c1bc94b61c8.jpg)

![ss_conference_standings_v1](https://user-images.githubusercontent.com/26416133/29133010-0f76a442-7d00-11e7-9011-c29323533ed1.jpg)

![ss_conference_standings_ 8](https://user-images.githubusercontent.com/26416133/29133584-f094dae2-7d01-11e7-9fce-fc2622be1f6d.jpg)

**Comment by adavila17** [comment]
Make Dynamic Template ID 627

User selects drop down labeled "Number of Teams" 10-16
Template arranges itself based on the preview images above.

**Comment by adavila17** [comment]
media relations

**Comment by ericmoore1** [comment]
This item is ready for testing.

**Comment by ValentineRain** [comment]
This works perfectly, @ericmoore1 ! Thanks a bunch.
We can go ahead and merge this, @Aubron ; I don't think it's super urgent but one of Marissa's clients is asking for it. 

I'll have two edits for @adavila17 ; the first will be to add a preview image after the merge. The second is to consider changing the layering of the conference logo, which is currently below 1/2 of the template objects. One bar is above it, the other below. Illustrated below.

![centerlogo](https://user-images.githubusercontent.com/26412274/29635441-147b2f8c-881b-11e7-84c0-845838d24bb7.png)

**Comment by Aubron** [comment]
Merged. Preview image?

**Comment by ValentineRain** [comment]
Confirmed that all this is missing is a preview image from @adavila17 .

**Comment by adavila17** [comment]
preview added
