### ISSUE TITLE
UNCW Starting Lineup With Cutouts

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#30]
![img_2404](https://user-images.githubusercontent.com/26412274/29179869-e35f01fa-7dc3-11e7-9162-28f3ffbdd2ef.PNG)

### Requested by:
Eric Rhew, UNCW, Public

## Template Description:

> Hi Val,
>  
> Over the last few days, I have seen these graphics for soccer and baseball come through on my Twitter feed and wondered if these might be something that could be made as a template for Scoreshots (or something similar to it).
>  
> Definitely open to everyone being able to use these.
>  
> Please let me know what you think.
>  
> Thanks and I hope all is well.

## Dynamic Considerations:
N/A, but possibly the number of players represented.

**Comment by ValentineRain** [comment]
Will be taking a look at this before the meeting to see if it matches anything we already have.

**Comment by ValentineRain** [comment]
I think this is the closest match, and it's still pretty different.

![266](https://user-images.githubusercontent.com/26412274/29180348-902bc890-7dc5-11e7-91a8-9291c3b5ce0e.jpg)

**Comment by ValentineRain** [comment]
Set Adam loose on this one to do what he's excited about.

**Comment by adavila17** [comment]
@kelvin-im @ericmoore1 

Drop zones have been added this **template ID 625** can be found in **"Developmenttest"** category.

Please take template ID 625 and make the player image drop zones dynamic with their corresponding text fields underneath/in front of them.

After making the template dynamic please merge 625 with 597 with a dynamic toggle for if the client wants player images or not.

**Comment by kelvin-im** [comment]
I'll do this one. Meh...

**Comment by kelvin-im** [comment]
Dynamicized. See PR for details. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/235

**Comment by ValentineRain** [comment]
Can I get Adam to take a look at this real quick? Everything is working fine, I just want to make sure this is what he had in mind.

![overlap](https://user-images.githubusercontent.com/26412274/29383603-0531c97c-829f-11e7-8a33-d5616e5111a3.png)

**Comment by ValentineRain** [comment]
Well I just noticed Adam isn't even here. I think I'm going to press on with testing since the spacing in a square template is more or less unavoidable. 💃

**Comment by ValentineRain** [comment]
One thing I will note is that un-checking the "show player images" checkbox does not hide any logos previously added. This may be a little bit overkill (since the formation step comes first) but in the interest of diligence, is this something that could potentially be hidden @kelvin-im ?

**Comment by kelvin-im** [comment]
I will revise that, if needed. Shouldn't be too heavy of a lift.

**Comment by ValentineRain** [comment]
Okay! Sorry to be a pain but I think that's what the average user would expect to happen. The alternative is that they have to click each one and delete them one at a time (since they can no longer be removed from the logo step panel).

Let's go ahead and do that.

**Comment by adavila17** [comment]
Need to make sure we space out for when player images are added. Can't expect the user to move these elements.

**Comment by ValentineRain** [comment]
Yeah, I kind of suspected that was going to be the case. Some more vertical spacing is needed, then. :/

**Comment by kelvin-im** [comment]
Alright, the images should now be hidden with the dropzone when "Show Player Images" is unselected. I've added vertical spacing between the image and text as well. Give it another go @ValentineRain, same PR.

**Comment by ValentineRain** [comment]
This is much better. I'm enclosing another screenshot in case @adavila17  wants to take a look at it; there's still some overlap but in a square format it can't really be spaced out any further. I think it's reasonable to expect the user to make a couple of adjustments depending on the number of player cutouts they'd like to use.

![untitled](https://user-images.githubusercontent.com/26412274/29429884-38b8eee4-8360-11e7-984e-f2d01423167a.png)

Still need to run just a few more tests on alternate browsers yet.

**Comment by ValentineRain** [comment]
Provided Adam is cool with the spacing, this one is good to go.
I'll want to test it in safari after the merge because of the usual security bug.

Also, I just wanted to ask because this has been confusing me; we're merging this into 597, right? What extra work needs to be done, and by whom, to make this happen?

**Comment by adavila17** [comment]
I think it just needs to be merged?

**Comment by ValentineRain** [comment]
Correct. Dinging @Aubron for this one. He probably won't add it til we have something substantive to patch.

**Comment by ValentineRain** [comment]
This one's been merged. Closing.
