### ISSUE TITLE
UNCW Box Score

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#31]
![img_2409](https://user-images.githubusercontent.com/26412274/29179966-33a0e1e2-7dc4-11e7-896e-66ae051be3df.JPG)
![img_2410](https://user-images.githubusercontent.com/26412274/29179965-339f23e8-7dc4-11e7-958f-d88059a32913.JPG)

### Requested by:
Eric Rhew, UNCW, Public

## Template Description:

> Hi Val,
>  
> Over the last few days, I have seen these graphics for soccer and baseball come through on my Twitter feed and wondered if these might be something that could be made as a template for Scoreshots (or something similar to it).
>  
> Definitely open to everyone being able to use these.
>  
> Please let me know what you think.
>  
> Thanks and I hope all is well.

## Dynamic Considerations:
N/A

**Comment by ValentineRain** [comment]
This was originally two, but I think they're similar enough to be condensed into one.
I'll be reviewing this before the meeting to see if it matches anything we already have.

**Comment by ValentineRain** [comment]
These are probably closest.

![420](https://user-images.githubusercontent.com/26412274/29180421-cc034bfe-7dc5-11e7-8b77-caf874bb6de1.jpg)
![462](https://user-images.githubusercontent.com/26412274/29180422-cc0d5dce-7dc5-11e7-9d28-0c41e4afb8d8.jpg)

**Comment by adavila17** [comment]
![ss_baseball_finalshot12_wide](https://user-images.githubusercontent.com/26416133/29468868-00dc42b4-8414-11e7-85be-90e27bea8f32.jpg)

**Comment by Aubron** [comment]
This one's good.

**Comment by adavila17** [comment]
Val text template ID 642

**Comment by ValentineRain** [comment]
This one tested well and looks great!
I noticed we missed the sponsor/conference spaces we usually add in the review meeting. Do you think you could add those real quick so we don't have to come back to this later?

**Comment by adavila17** [comment]
added logos preview image added
