### ISSUE TITLE
UNCW Final Score

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#32]
![img_2408](https://user-images.githubusercontent.com/26412274/29180055-838057ce-7dc4-11e7-8a02-3d8158b01acd.JPG)

![img_2407](https://user-images.githubusercontent.com/26412274/29180056-849a29dc-7dc4-11e7-8fe9-e985ae8ddeb9.JPG)

### Requested by:
Eric Rhew, UNCW, Public

## Template Description:

> Hi Val,
>  
> Over the last few days, I have seen these graphics for soccer and baseball come through on my Twitter feed and wondered if these might be something that could be made as a template for Scoreshots (or something similar to it).
>  
> Definitely open to everyone being able to use these.
>  
> Please let me know what you think.
>  
> Thanks and I hope all is well.

## Dynamic Considerations:
N/A, but possibly the number of players represented.

**Comment by ValentineRain** [comment]
Will be reviewing this before today's meeting to determine if it matches anything we already have.

**Comment by ValentineRain** [comment]
Although we have templates for box scores, I think this is substantially different.

**Comment by ValentineRain** [comment]
Ask client for specific things they like and whether any existing templates match.

**Comment by ValentineRain** [comment]
> Hi Val,
>  
> Thanks for the quick response on this.
>  
> In terms of the first design, I like the runs-hits-errors capability along with having the team name and logos in place.
>  
> I certainly would not be opposed to modifying the existing template you have in place.
>  
> In the second design, I like the home plate headshot and having the team logos and game information below it. But, again, I am not opposed to seeing the existing templates modified if that helps.
>  
> Thanks again and I appreciate your help on this.
>  
> Eric

Passing this to Adam now that we have all of the information asked for.

**Comment by adavila17** [comment]
Overkill? I mean I can do basic if need be this is a low priority anyway we can leave for at least 2 months. 

![ss_baseball_finalshot10_wide](https://user-images.githubusercontent.com/26416133/29380912-73ca1088-8295-11e7-8482-db0b158915b3.jpg)

**Comment by ValentineRain** [comment]
Whooooooaaaah!
That's some ESPN level shit right there. I really like it. How much of this is client configurable?

**Comment by ValentineRain** [comment]
Damn, the more I look at this the more impressed I am.

**Comment by adavila17** [comment]
The only thing a client would need to do is add in logos, text and color. Would really want to lock the gray colors that need to be left alone because I don't want to see horrible configurations.

**Comment by ValentineRain** [comment]
Neat, I'm gonna flag this one for review. I'd personally like to see this implemented real bad.

**Comment by Aubron** [comment]
Rick says it's reaaaaaally cute.

**Comment by adavila17** [comment]
Rick is dead to me.

**Comment by adavila17** [comment]
Test val template ID 644

**Comment by ValentineRain** [comment]
This looks good so far! It's a candidate for the new logo clipping, though. It'd work well here:

![clipping](https://user-images.githubusercontent.com/26412274/29786761-69cace6a-8bfa-11e7-9fb7-fb736205d88e.png)

**Comment by ValentineRain** [comment]
Also I do really like that you've left them color-alterable after all. I think this was the right choice, even if the default black still looks best.

![colorshenans](https://user-images.githubusercontent.com/26412274/29786973-206215ac-8bfb-11e7-8275-c5073478aa2a.png)

**Comment by ValentineRain** [comment]
No issues to report here, but if you add the logo clipping I'll be your best friend.

**Comment by adavila17** [comment]
preview image added
