### ISSUE TITLE
UNCW Lower Third Final Score

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#33]
![unnamed](https://user-images.githubusercontent.com/26412274/29180111-bac9f15e-7dc4-11e7-9c96-bc7bada20a08.jpg)

### Requested by:
Eric Rhew, UNCW, Public

## Template Description:

> Hi Val,
>  
> Over the last few days, I have seen these graphics for soccer and baseball come through on my Twitter feed and wondered if these might be something that could be made as a template for Scoreshots (or something similar to it).
>  
> Definitely open to everyone being able to use these.
>  
> Please let me know what you think.
>  
> Thanks and I hope all is well.

## Dynamic Considerations:
N/A

**Comment by ValentineRain** [comment]
Will be reviewing before the meeting to determine if this matches anything we already have.

**Comment by ValentineRain** [comment]
We probably don't need to make this one, we have this:

https://scoreshots.com/index.php/template/choosetemplate/29637#showpic

**Comment by adavila17** [comment]
![ss_baseball_finalshot11_wide](https://user-images.githubusercontent.com/26416133/29411719-0ba9c482-8324-11e7-9121-4b0bfacd3eaa.jpg)

**Comment by ValentineRain** [comment]
Neat, adding a review tag.

**Comment by Aubron** [comment]
Add sponsor and conference logo.

**Comment by adavila17** [comment]
Val test template ID: 643

**Comment by ValentineRain** [comment]
Moving on to this one

**Comment by ValentineRain** [comment]
This template is good! When we get a preview image on it, we can push it out.

**Comment by adavila17** [comment]
preview added.

**Comment by ValentineRain** [comment]
You actually added this (and another template) to the wrong category. Pictured below.

I'm still going to close this task 'cause we're flooded but we should probably move them.
