### ISSUE TITLE
UNCW Baseball Starting Lineup

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#34]
![img_2406](https://user-images.githubusercontent.com/26412274/29180186-feb7120c-7dc4-11e7-81a1-3a8b24c3ae00.JPG)

![img_2412](https://user-images.githubusercontent.com/26412274/29180188-00fe17ea-7dc5-11e7-9e85-318d9e23b773.JPG)

### Requested by:
Eric Rhew, UNCW, Public

## Template Description:

> Hi Val,
>  
> Over the last few days, I have seen these graphics for soccer and baseball come through on my Twitter feed and wondered if these might be something that could be made as a template for Scoreshots (or something similar to it).
>  
> Definitely open to everyone being able to use these.
>  
> Please let me know what you think.
>  
> Thanks and I hope all is well.

## Dynamic Considerations:
N/A

**Comment by ValentineRain** [comment]
Will be reviewing this before the meeting to see if it matches anything we already have.

**Comment by ValentineRain** [comment]
Closest match:

![422](https://user-images.githubusercontent.com/26412274/29180590-3c496952-7dc6-11e7-9aa0-a405d9d06059.jpg)

**Comment by ValentineRain** [comment]
Point out above template to client. Ask are you suuuuuuuuuuuuuuure?

**Comment by ValentineRain** [comment]
Response from client:

Hi Val,
 

> Thanks for the quick response on this.
>  
> In terms of the first design, I like the runs-hits-errors capability along with having the team name and logos in place.
>  
> I certainly would not be opposed to modifying the existing template you have in place.
>  
> In the second design, I like the home plate headshot and having the team logos and game information below it. But, again, I am not opposed to seeing the existing templates modified if that helps.
>  
> Thanks again and I appreciate your help on this.
>  
> Eric

It seems like the client really wants this feature but is okay with just modifying it if we want to.
I don't know if that's a good idea, still, because it was originally requested by another client and we'd be changing their template under them. 

Either way, as determined in the last meeting @adavila17 is to push forward on a design via either method.

**Comment by adavila17** [comment]
blah blah blah.... here ya go.

![ss_baseball_startinshot6](https://user-images.githubusercontent.com/26416133/30978886-ebe032b6-a449-11e7-80c0-f055892469ee.jpg)

**Comment by adavila17** [comment]
test temp ID: 422

**Comment by ValentineRain** [comment]
The only new element is the clipping, which works in all browsers.
Needs a preview image; dont close it just yet so I can let UNCW know when it's available along with the other one.

**Comment by adavila17** [comment]
preview added

**Comment by ValentineRain** [comment]
Sent to client! Closing.
