### ISSUE TITLE
UNCW Baseball Statshot

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#35]
![img_2411](https://user-images.githubusercontent.com/26412274/29180235-2e12e030-7dc5-11e7-9adc-b94eb2573aa2.JPG)

### Requested by:
Eric Rhew, UNCW, Public

## Template Description:

> Hi Val,
>  
> Over the last few days, I have seen these graphics for soccer and baseball come through on my Twitter feed and wondered if these might be something that could be made as a template for Scoreshots (or something similar to it).
>  
> Definitely open to everyone being able to use these.
>  
> Please let me know what you think.
>  
> Thanks and I hope all is well.

## Dynamic Considerations:
This one has graphs.

**Comment by ValentineRain** [comment]
I think that this one is unique enough to warrant review without digging through the engine.

**Comment by ValentineRain** [comment]
Tell client we're studying this and will circle back next week.

**Comment by ValentineRain** [comment]
Task Rick with this later.

**Comment by ValentineRain** [comment]
Rick has been tasked with querying for this one.

**Comment by adavila17** [comment]
Any move on this?

**Comment by ValentineRain** [comment]
Yeah, there was an email chain between him and the client.
I don't think Rick is going to post it here so I'll probably come back in the next day or two and add them myself. There's a lot to dig through.

**Comment by ValentineRain** [comment]
Following Rick's querying, this task is being closed in favor of reworking an existing template. Track this [here](https://github.com/Aubron/scoreshots-templates/issues/69).
