### ISSUE TITLE
Eckerd College Player of the Week & Happy Birthday

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#38]
![happybirthday2 1](https://user-images.githubusercontent.com/26416040/29276876-fc8c5c0a-80dd-11e7-9be4-3187963de0bb.png)
![potw 1](https://user-images.githubusercontent.com/26416040/29276877-fc8ccfaa-80dd-11e7-849c-86c04ccb007f.png)

**Comment by adavila17** [comment]
Player of week is temp ID 631

**Comment by adavila17** [comment]
Happy Birthday temp ID 632

**Comment by adavila17** [comment]
Combine templates 631 & 632

Needs drop-down menu labeled "Template"
"Player of the Week" & "Happy Birthday" as the titles inside drop-down.

631 is Player of the Week
632 is Happy Birthday

**Comment by kelvin-im** [comment]
I'll work on this one.

**Comment by kelvin-im** [comment]
@adavila17, I had to modify one of the layers in the Admin section to get the dynamic code to work. The first "Rectangle 5" was changed to "Rectangle 6" to keep layers different for both templates 631 and 632. It probably needs this change in LIVE as well. I've used template 631 to make dynamic.

After the above change, this template should be ready for review/testing @ValentineRain. 

PR: https://github.com/Aubron/scoreshots/pull/243

**Comment by lisajohnson11** [comment]
Hey guys, any update on when this is going to be done? @ValentineRain @kelvin-im

**Comment by ValentineRain** [comment]
I'm taking care of testing this morning just as soon as I finish payroll~

**Comment by ValentineRain** [comment]
Hi @kelvin-im , there's just one bug with this one!

![thing](https://user-images.githubusercontent.com/26412274/29575697-52bf7cf0-8733-11e7-8e83-279d039db122.png)

See that one blue bar that's kind of out of place in the middle? You forgot to translate that to the left with everything else.

**Comment by kelvin-im** [comment]
Alright, that should be fixed. Had to add that element in the list with the others. Give it another go @ValentineRain.

**Comment by ValentineRain** [comment]
All good!

**Comment by ValentineRain** [comment]
When you get the chance, @Aubron , please merge [this pull request](https://github.com/Aubron/scoreshots/pull/243). Client is waiting on it.

**Comment by Aubron** [comment]
This has been merged, and will be deployed momentarily. Preview image is probably still needed.

**Comment by ValentineRain** [comment]
Thanks. I'm ready to add a preview image when it's set to go. Adam warned me about that already.

**Comment by adavila17** [comment]
yeah i did that already this morning

**Comment by adavila17** [comment]
So yeah we need to look at Happy Birthday again the elements jumped they are too far over to the left than the preview.

**Comment by adavila17** [comment]
Nvm we are good.
