### ISSUE TITLE
Golf FinalShot, Update Behavior and Variant

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#39]
This is template 435, it looks pretty okay:

![435](https://user-images.githubusercontent.com/26412274/29291455-a7131924-8111-11e7-8b0f-d8a8d0428758.jpg)

This is template 236, it doesn't:

![236](https://user-images.githubusercontent.com/26412274/29291495-c60510e4-8111-11e7-9773-cae06cf16180.jpg)

Our task is to copy the design from the former to the latter.
Then, we will update both to display a user-defined number of rounds. This will require a pass through development.

**Comment by ValentineRain** [comment]
Adam, I think the first step is for you to copy the design elements from the first template to the second. Then we'll pass it to development. Probably.

**Comment by adavila17** [comment]
Just make it dynamic USGA has a certain style they have to the revamp does not meet. I'll look at it and see if giving the font more weight will do. I don't think a background underneath the score cards will jive with them.

**Comment by adavila17** [comment]
Eh, maybe it does but I'm getting rid of the texture that doesn't work.

**Comment by adavila17** [comment]
630 do what ever I don't care.

**Comment by ValentineRain** [comment]
Hi Adam, can I get some clarification on what you want me to do with this? Is it ready to be passed to development?

**Comment by adavila17** [comment]
Needs the same task as the other template in "Golf" category.

**Comment by ValentineRain** [comment]
This one got a little lost but after poking around I think I understand where it's at.
Passing this to development, as this template needs dynamic treatment. There should be a dropdown which reads "Number of Rounds". Presumably, the min value is 1 and the max is 4, which corresponds to the number of "RD" text fields and associated numbers displayed. I'd imagine they should be centered.

**Comment by kelvin-im** [comment]
I'll work on this one.

**Comment by kelvin-im** [comment]
This template is dynamic. It needs a slight change into LIVE before testing, @ValentineRain.

@adavila17, I had to make some slight changes to the template on the Admin side. I needed to change the Divider Bar names to `Divider Bar 1, Divider Bar 2, and Divider Bar 3` for each one. This needs similar treatment on your end. Afterwards, template is dynamic and ready for review.

PR: https://github.com/Aubron/scoreshots/pull/279

**Comment by adavila17** [comment]
done

**Comment by ValentineRain** [comment]
So I have a couple of concerns about this one. From the top:

- The "Number of Rounds" dropdown (which is correct) is labeled "Number of Sports" in its main heading.

![number of sports](https://user-images.githubusercontent.com/26412274/30346667-8ad1df0c-97d7-11e7-8150-b528991e338d.png)

- Attempting to use the dropdown results in no change on screen, and the following console error:

```
Uncaught TypeError: Cannot read property 'setVisible' of undefined
    at temp_trace (630.js?time=1505247620915:74)
    at Object.ClientUtil.temporary_trace [as statshot] (630.js?time=1505247620915:169)
    at Object.ClientUtil.execute_module (lib-client-util.js?1.0.74342rs47_2423:7233)
    at HTMLSelectElement.<anonymous> (lib-client-app.js?1.0.74342rs47_2423:465)
    at HTMLSelectElement.dispatch (jquery.min.js:3)
    at HTMLSelectElement.i (jquery.min.js:3)
```

- While we're on this topic, the dashboard for this PR is doing weird stuff. This might be related more to it being on a test server, because this is just happening across PR's today (not just this one). I'm not really sure what's going on and the error message itself is illegible. This is almost certainly a non-issue but I didn't want to risk not mentioning it.

![dash](https://user-images.githubusercontent.com/26412274/30346669-8f58f984-97d7-11e7-9daf-1688fefccf75.png)

- Finally, I notice we're working on a PR for a completely new template (ID 630) rather than altering the behavior of either of the two existing ones (435 or 236). I realize now, perhaps too late, that @adavila17 made this split intentionally, and I don't understand why. Are we deleting the old templates? I ask this because 630 does not contain all of the design elements of 435 or 236, and is instead somewhere in between them. If this is actually a good idea, then cool, let's push forward with it, but I would still like to understand why in case I'm questioned about it later.

**Comment by kelvin-im** [comment]
Alright, the Number of Games title has been properly changed. 

For that dropdown error, the template dividers are still named the same on template 630. I've changed the names stated above on that template, and it works on my end. Template 630 may need another look through @adavila17. After that, give it another go @ValentineRain.

**Comment by ValentineRain** [comment]
@adavila17 , can you confirm when you've done what Kelvin has described above? I'd like to finish this one. :DD

**Comment by adavila17** [comment]
okie dokie done

**Comment by ValentineRain** [comment]
That did it! The behavior is fixed.
I'm going to flag this one for an ahead-of-schedule merge.

Just so that we're clear, @adavila17 ; this is the USGA version, right? I'm wondering if we'll be able to easily copy these same behaviors into the non-USGA template with the background once we're done.

**Comment by adavila17** [comment]
Should be. The code only reacts to layers that need to move or be hidden. I can freely add layers that are not dynamic to dynamic templates that have been created and used for months. Does nothing to the dynamic behavior.

**Comment by ValentineRain** [comment]
Cool, thanks for the information! In that case, here are the steps that still need to be taken to close this task:

- 630 needs to be duplicated in its current state (without the background) to be included in the USGA category, so they have a dynamic version of this template that fits within their branding guidelines.
- The background objects/textures/stuff should be added to 630, which will appear in just Golf.
- The old template (435) should have its preview image removed (but not be deleted), to reduce clutter without breaking client drafts.

**Comment by adavila17** [comment]
Can we not just add the coding to Template ID 435? 
It's ready to go with corrected layer names

Then I will duplicate template ID 630 to USGA and then have the dev team add the code to that template ID. 
The old USGA one is outdated.

**Comment by ValentineRain** [comment]
Tasking development to copy the dynamic positioning code from template 630 to template 435.  ❤️

**Comment by kelvin-im** [comment]
Copied. Ready for review/testing.

PR: https://github.com/Aubron/scoreshots/pull/398

**Comment by ValentineRain** [comment]
This one is good!

**Comment by ValentineRain** [comment]
These changes are in!
