### ISSUE TITLE
Quote Graphics, Paired

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#40]
![ss_mediarelations_quoteshot3_square](https://user-images.githubusercontent.com/26416133/29463026-34c59bda-83ff-11e7-9c47-155dff53d9f6.jpg)

![ss_mediarelations_quoteshot4_square](https://user-images.githubusercontent.com/26416133/29463305-3a6a4d78-8400-11e7-94fa-53b6a970847f.jpg)

**Comment by ValentineRain** [comment]
They look good! Quick question about the second one; is that actually what it will look like when a semi-transparent bar is laid over the left side of that photo? Or as it been color-adjusted? It looks similar to what we can produce with a filter but obviously we can't apply a filter to half of a photo.

**Comment by adavila17** [comment]
Yeah that's a multiply filter. Wish we had that as an option for shapes in the backend. Updated it to reflect how the engine will make that area.

**Comment by ValentineRain** [comment]
👍

**Comment by Aubron** [comment]
Meeting today, these are good.

**Comment by adavila17** [comment]
Val test you whore <3

**Template IDs 638 & 639** 

Don't worry about the font that matches with the templates I will get Aubron to add them to the engine when I can.

**Comment by ValentineRain** [comment]
I'll test this today. Thanks for the reminder.

Also this is a public repository so careful with the language. I've modified it already so no worries.

**Comment by ValentineRain** [comment]
Tempalte 638 is good to go. 639 is broke, real bad.

![untitled](https://user-images.githubusercontent.com/26412274/29625029-9b5bbc10-87f8-11e7-89a1-48b358fc1d2e.png)

**Comment by ValentineRain** [comment]
Sorry, wasn't done commenting yet, didn't mean to submit it.

Anyway, looking at this error I'm not really sure what's going on with it, I admit.
@adavila17 , do you have any weirdly named layers or anything in the Admin side? I was under the impression this was a normal template with nothing unusual to it. If not we might need to pass this to development.

**Comment by adavila17** [comment]
i probably maybe forgot the scoreshots logo

**Comment by adavila17** [comment]
so a font was messing it up

**Comment by ValentineRain** [comment]
I'll retry it.

**Comment by ValentineRain** [comment]
Done with followup testing. I'd be curious to know what exactly you changed about these to fix it if it turned out not to be the font issue after all, just in case we ever run into it again!

Either way, they work perfectly. Can you please add some preview images to them and we'll wrap this up?

**Comment by adavila17** [comment]
preview images added in
