### ISSUE TITLE
Volleyball StatShot, XML-Enabled

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#41]
![preview-lightbox-ss_volleyball_statshot1](https://user-images.githubusercontent.com/26412274/29535981-041f471e-868a-11e7-977e-07d931a5e407.jpg)

### Requested by:
None, Internal

### Due Date:
N/A

## Template Description:
A statshot for Volleyball. 

## Dynamic Considerations:
In addition to drawing graphs, this template will need to be capable of reading XML files. The number of sets or whatever that is at the bottom should also scale depending on the data received from the XML file, but presumably the user should be able to manually select this from a dropdown in the event they aren't importing one.

**Comment by ValentineRain** [comment]
This template has been approved for work. Shame on all of you for using Basecamp.
Next step is for Adam to design the various components in the engine, and then it will be passed to development.

**Comment by adavila17** [comment]
digging into this now design wise at least.

**Comment by adavila17** [comment]
Temp ID is 640

Kills, Digs, Blocks & Aces adjust to maximum number put into the number section not only within the stat but also to the 4 areas.

Additional we'll need a drop down called "Number of Games" 1 match in volleyball can go from 2-5 games before someone wins. This is to correspond to the box score at the very bottom of the template where 1-5 are shown if a match only goes to 4 games then take away the last area and re-center horizontally.

![ss_volleyball_statshot1v3](https://user-images.githubusercontent.com/26416133/29580582-831fbe44-8744-11e7-9545-b4faa9b3c8b5.jpg)

![ss_volleyball_statshot1](https://user-images.githubusercontent.com/26416133/29580585-85c689ca-8744-11e7-9f3b-10ff9f545c3f.jpg)

**Comment by ValentineRain** [comment]
Moving on to this one next. I don't see an XML feed provided here so I'll try to dig up the test one on basecamp.

**Comment by ValentineRain** [comment]
This one's just a note for Adam. 

The top headline and the borders around the set table at the bottom default to team colors, but if a teamcolor is white, it renders all of the text they contain illegible.

Normally I consider this a "them" problem, but it's not unreasonable that their team colors might contain white. Is there a way we can force the white background to not collapse into others, but still be changable by the user?

![test1](https://user-images.githubusercontent.com/26412274/29790521-2cfbe1b4-8c08-11e7-9eac-3099f59bf0b0.png)
![test2](https://user-images.githubusercontent.com/26412274/29790522-2cfd314a-8c08-11e7-90e2-9ed1b9382f3c.png)

**Comment by ValentineRain** [comment]
Another note for @adavila17 : We can probably achieve the above by making the background just slightly off from white, at a hex code that someone is unlikely to use exactly.

Also this template is currently missing the text for Kills, etc, over each bar graph.

Note for @ericmoore1 :

I really like your solution for keeping the text items visible on bar graphs!

Chatted with @Aubron and this drop down should probably be at the top of the stats step for consistency, though you were definitely right to put it here to begin with since it's the last thing the client will edit.

![dropdown](https://user-images.githubusercontent.com/26412274/29791528-3d7d44d0-8c0b-11e7-9d6d-bd48c860795c.png)


Can you capitalize the n in "Number" and change the language to "Number of Sets"? which @lisajohnson11 says is the correct thing that they're called. Sports words! I dunno 'em.

Finally, this template should be able to take XML files like this one in. I think this is the right one? This has been done already in template ID 314, which you can maybe use as a model for how this will work. Ask @Aubron if you have any questions, admittedly I don't know much about it.

**Comment by adavila17** [comment]
added missing txt fields.

**Comment by ValentineRain** [comment]
Thanks. This is waiting for dev treatment for the above.

**Comment by ericmoore1** [comment]
This has been updated and re-pushed up.

**Comment by ValentineRain** [comment]
Thanks! Flagging for testing today.

**Comment by ValentineRain** [comment]
Following our meeting today, this actually does need to spend more time in development for XML integration.

**Comment by Aubron** [comment]
I am going to be adding in the XML integration to this today. Thanks.

**Comment by ericmoore1** [comment]
This is ready for review. See https://github.com/Aubron/scoreshots/compare/master...template-640

**Comment by adavila17** [comment]
Sooooo.... how is this live if it's in a review state?

**Comment by Aubron** [comment]
Shut up adam no one cares.
