### ISSUE TITLE
New Template Ideas 2

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#42]
The Same template just a variation from one sport to the other.

![ss_baseball_previewshot10_wide](https://user-images.githubusercontent.com/26416133/29571760-107169ea-8728-11e7-9659-af5679e17790.jpg)

![ss_football_previewshot10](https://user-images.githubusercontent.com/26416133/29571773-20c12e2a-8728-11e7-9560-5d8f9b46f530.jpg)

**Comment by ValentineRain** [comment]
Damn, I like these a lot, too. You've gotten really serious about these lately.

**Comment by Aubron** [comment]
Adam to add sponsor logo to both and shrink ScoreShots logo. Then this is good to go!

**Comment by adavila17** [comment]
@ValentineRain test football temp ID 641 i was working on it already ^_^

**Comment by ValentineRain** [comment]
Starting on this now.

**Comment by ValentineRain** [comment]
This is testing well so far. Can we re-order the logos please? Currently the big, prominent player cutout is wedged in the order between "Team 1" and "Team 2", which makes it annoying add via double clicking.

Can we just display the player image slot first?

**Comment by ValentineRain** [comment]
Are the logos supposed to be clipped to those boxes?

![thing 4](https://user-images.githubusercontent.com/26412274/29724079-25e01ef6-8995-11e7-8bbe-2ad025ee6427.png)

**Comment by ValentineRain** [comment]
Everything else here looks good to me. Just waiting on a response to the above~

**Comment by adavila17** [comment]
Wasn't planning on it since it's a large area for logos. I mean I can just give me a minute working on some stuff for Lisa and FSU.

**Comment by ValentineRain** [comment]
Yeah, no worries. If you don't think it'll look good, then don't worry about it, but I figure we might as well since there will be little pentagons up there in the variant that will almost certainly need it.

**Comment by ValentineRain** [comment]
Just noting that this is still waiting on logo clipping!

**Comment by adavila17** [comment]
val test template ID: 668
category basebal

**Comment by ValentineRain** [comment]
Everything on 668 is good to go, with the exception of logo clipping on the team1 and team2 space.

![clip](https://user-images.githubusercontent.com/26412274/30450163-038293a0-995f-11e7-9015-7b36a8934736.jpg)

Fix that and it should be shippable!

**Comment by adavila17** [comment]
Yeah, they don't do that in baseball. That would be awkward.

**Comment by ValentineRain** [comment]
They don't confine logos to geometric spaces in baseball?
That's oddly specific.

**Comment by ValentineRain** [comment]
Well, at any rate this needs a preview image!

**Comment by adavila17** [comment]
mmmmtay
