### ISSUE TITLE
FSU Golf Scorecard 

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#43]
The two rectangle graphics you have under Golf are good for formatting purposes. On the Card Shot, I don’t think we would need hole-by-hole scores.
 
On the squares I like the Snap Shot, which could also be the same format for the final shot.
 
Attached a couple others. Design should remain consistent with the templates created so far. Thanks

**Comment by lisajohnson11** [comment]
![golf2](https://user-images.githubusercontent.com/26416040/29584511-f8d1170c-8751-11e7-9663-167f85ede10f.JPG)
![golf](https://user-images.githubusercontent.com/26416040/29584514-fce69dbc-8751-11e7-92f7-65d225cf1f9d.JPG)

**Comment by adavila17** [comment]
OMG I'M GONNA DIE!!!!

**Comment by adavila17** [comment]
Hope this works for them. 

![ss_fsu_golf_snapshot](https://user-images.githubusercontent.com/26416133/29674015-f0bf6c8a-88be-11e7-8de6-bd3728f6f2fa.jpg)

**Comment by lisajohnson11** [comment]
Hi Adam, looks great! Just curious, does this have the same tribal print on the bottom as the others did?

**Comment by adavila17** [comment]
or this....

![ss_fsu_golf_snapshotv2](https://user-images.githubusercontent.com/26416133/29678056-354dcaf2-88cb-11e7-9cbf-cfcb074fcdab.jpg)

**Comment by adavila17** [comment]
Closing this because it has become [this task](https://github.com/Aubron/scoreshots-templates/issues/51).
