### ISSUE TITLE
Lubbock Christian, "Week's Schedule" with Logos

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#44]
![dg5nt83vyaib-ys 3](https://user-images.githubusercontent.com/26412274/29627263-86cb4dae-87ff-11e7-951c-816f5898d778.jpg)

### Requested by:
Chris Due, Lubbock Christian.
Probably public.

## Template Description:

> I am trying to find a template like the one attached to use as a “This Week’s Schedule of Sporting Events,” etc.  Do you know where a template like this may be or if another school is currently using one that may be visible on their admin page but not ours?

> Id like one with the option to have logos and broadcast logos like the NBA one if that’s possible with the boxes etc.  I just don’t now how that would work whether there are 3 events or 10 events that week, if that makes sense. If that is possible with the example you sent me, just let me know the easiest/best way to do that.

## Dynamic Considerations:
Probably needs to scale to the number of games or whatever displayed.

**Comment by Aubron** [comment]
Adam to create single-school variant of this first, and we'll return to this format for conferences later.

Dynamic specs will be minimum to 3, and maximum is whatever Adam can fit in there. Maybe a dozen.

**Comment by adavila17** [comment]
![ss_mediarelations_scheduleshot4](https://user-images.githubusercontent.com/26416133/29827426-00a5d520-8ca8-11e7-9c56-6b7c602dd907.jpg)

**Comment by Aubron** [comment]
14 version please
Shrink ScoreShots logo.

**Comment by adavila17** [comment]
made it 15 

![ss_mediarelations_scheduleshot4_v2](https://user-images.githubusercontent.com/26416133/29971780-98180be8-8ef7-11e7-826c-fb6414e832d6.jpg)

**Comment by adavila17** [comment]
Temp ID 661 ready for dynamism.
Category Media Relations.

**Comment by adavila17** [comment]
This needs to be worked on we have a client that's been waiting awhile for this.

**Comment by kelvin-im** [comment]
I'll give it a go.

**Comment by kelvin-im** [comment]
Dynamicized. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/292

**Comment by ValentineRain** [comment]
This is good. I'd like to see this merged today if we can!

**Comment by Aubron** [comment]
Merged to live. Waiting on @adavila17 for preview image.

**Comment by adavila17** [comment]
preview added
