### ISSUE TITLE
Scheduleshot With More Than 13 Games

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#45]
### Requested by:
A lot of people.
Public.

## Template Description:

A lot of people are asking for a scheduling template that can display over 13 games. How many? Good question. Rick will probably have an opinion.

## Dynamic Considerations:
Dropdown for number of games.

**Comment by Aubron** [comment]
Adam to contact Aubron if he feels he needs more space than a 1024x576 image.

**Comment by Aubron** [comment]
@rocksprings to provide some placement ideas or pictures of cats. It's whatever.

**Comment by rocksprings** [comment]
So I want to use the Florida State theme (with our own twist) of placing all opponents logos in bounding boxes with space below to indicate the opponent and the date and time. It would have a maximum of 35 drop zones. So this would presumably be dynamic with a minimum of 25 drop zones. Can you create a draft of this, Adam, or do you need more information?

**Comment by adavila17** [comment]
working in on this but @Aubron admin side is broken/needs a major overhaul cause it hasn't been updated in forever/please.

**Comment by ValentineRain** [comment]
Issue referenced above is now being tracked [here](https://github.com/Aubron/scoreshots/issues/263). Will set this to blocked until resolved.

**Comment by adavila17** [comment]
Don't get too excited working through some bugs with text.

![v2zntvs](https://user-images.githubusercontent.com/26416133/29976705-e5ad57ee-8f08-11e7-9519-b013c0bbb199.png)

**Comment by rocksprings** [comment]
Any value in stacking these logos in some fashion so they can be a bit bigger/easier to see?

**Comment by ValentineRain** [comment]
Would be interested to know how this is going! Marissa was asking about it earlier.

**Comment by adavila17** [comment]
I mean I made it in engine so it's underway but we have bugs that need to be worked out because it is very unique to 2.0

Bugs can be tracked here:

[Bug 1](https://github.com/Aubron/scoreshots/issues/263)

[Bug 2](https://github.com/Aubron/scoreshots/issues/264)

**Comment by adavila17** [comment]
And another one but we have to wait till bugs are fixed.

![scheduleshot](https://user-images.githubusercontent.com/26416133/30179972-5d49a3ca-93dc-11e7-8e3c-454ce83019a4.jpg)

**Comment by rocksprings** [comment]
I like the general direction of this a lot, but wonder if we can distinguish by month. . .
And I still like the theme of not having to blow up SS to see the information, meaning I think the logos might be too small.
We can discuss in next template review, I suppose.

**Comment by ValentineRain** [comment]
Okay~ Flagged for review, and for bugs blocking development.

**Comment by adavila17** [comment]
Every full schedule social graphic that exists is made to be clicked on and expanded. Additional these posts are meant to drive a user to an athletics page to get more information.

**Comment by rocksprings** [comment]
To date, no one has argued my long-documented proposition that all info in a SS should be visible without clicking on it.
So please humor me and provide what I've requested.
If you want to discuss at next weekly meeting, please feel free to do so.

**Comment by ValentineRain** [comment]
I don't find it difficult to believe that someone might want otherwise, provided the design is nice.
I think in order to structure this discussion for maximum efficiency and minimum hurt feelings, it might help to bring to the next weekly some examples of schools posting graphics which are not visible without being enlarged. Then we'll have some data on whether this is a trend, and how we can accommodate.

@adavila17 , if you'd like help checking for this kind of image, let me know. I'll be happy to lend a hand.

**Comment by rocksprings** [comment]
Not sure I follow, Val.
Adam, please provide what I've requested.
Thank you.

**Comment by adavila17** [comment]
Bigger by 20px.

![scheduleshot_v2](https://user-images.githubusercontent.com/26416133/30547968-d71032b6-9c5e-11e7-8274-62a34f22d926.jpg)

**Comment by rocksprings** [comment]
From my post above:
I like the general direction of this a lot, but wonder if we can distinguish by month. . .
(Can we organize by month, please)?

**Comment by rocksprings** [comment]
Let's go ahead and scrap this template for now.
It seems like it's too much work right now.

We can just come back to it later.

**Comment by rocksprings** [comment]
Thought better of letting it sit since folks are asking for us. I've attached my artwork for feedback and review.
![schedule shot 091817](https://user-images.githubusercontent.com/26558545/30563640-8054b168-9c90-11e7-9a20-1d947fa45da0.jpg)

**Comment by ValentineRain** [comment]
Adding the "Design Needed" flag. It looks like Rick forgot.
Any update on this?

**Comment by rocksprings** [comment]
I didn't forget.
I just didn't know how to trigger a flag being erect.
Can we also change this to High Priority.

**Comment by ValentineRain** [comment]
Not a problem. Changing the priority flag now.
For your future reference, you would do so by clicking the gear symbol next to "Labels" in the top left corner of the page, and adding the label you want to apply.

**Comment by BillPate** [comment]
Here is the Template for review.

Thanks
Bill
![aubron-alligators](https://user-images.githubusercontent.com/31041645/31180057-9b1255f2-a8eb-11e7-96c4-4c37bf5f4117.jpg)

**Comment by rocksprings** [comment]
I like this but would also like to see something like the original sketch so we have a comparison.
Maybe we can offer two versions.

**Comment by BillPate** [comment]
Design closer to drawing.
![aubron-alligators2](https://user-images.githubusercontent.com/31041645/31196171-c0dac34e-a91a-11e7-9734-4f033a2fdd67.jpg)

**Comment by rocksprings** [comment]
I thought there was a stacked version of this we did for Florida State, but I don't see that one in their templates. Can you please check to see if you can locate it?
Thanks.
Rick

**Comment by adavila17** [comment]
This is a bug related to the template that is still needing to be addressed by the dev team here is the thread.

**Link:**
https://github.com/Aubron/scoreshots-templates/issues/28

**Comment by Aubron** [comment]
Proceed with design 1, beware of 1 pixel skinny thing on left.

**Comment by BillPate** [comment]
New template.
![aubron-alligators3](https://user-images.githubusercontent.com/31041645/31396223-cd2d7584-adb0-11e7-8303-1a2eeeb44496.jpg)

**Comment by rocksprings** [comment]
I like this. . .
Just wondering if we need any spacing between dates both horizontally and vertically.
I don't really know. . .
Let's push this to creation not later than after Friday's weekly.

**Comment by adavila17** [comment]
@billpate please be sure you are tracking on this as this will be your first template. Please see me for any and all questions.

**Comment by BillPate** [comment]
@rocksprings do you want the spacing? Or leave it as is? Also thanks @Aubron for tagging me..

**Comment by rocksprings** [comment]
Interested in hearing from others on this question. . .

**Comment by ValentineRain** [comment]
Safest answer is to try it with the spacing, post it again, and see how it compares.

**Comment by BillPate** [comment]
Ok with added spacing.
![aubron-alligators4](https://user-images.githubusercontent.com/31041645/31463049-c16ececc-ae9c-11e7-882f-363cdc53a377.jpg)

**Comment by rocksprings** [comment]
Where did you add the spacing?

**Comment by ValentineRain** [comment]
I was going to make a joke about your eyesight but actually I cant see it either.

**Comment by BillPate** [comment]
I legit added 4 and 4 on the top and left. I will go and add in more
though  for sure..

Bill

**Comment by BillPate** [comment]
![aubron-alligators5](https://user-images.githubusercontent.com/31041645/31496675-5aff3148-af2a-11e7-8cf0-ad63a9caf692.jpg)


more space

**Comment by rocksprings** [comment]
Where has the more space been added? I still don't see it.
Could we see some obvious separation between each date horizontally so they are not each connected?

**Comment by BillPate** [comment]
![aubron-alligators5](https://user-images.githubusercontent.com/31041645/31499323-75505376-af32-11e7-9e86-d58e48661e4b.jpg)

**Comment by rocksprings** [comment]
Still don't see it. . .

**Comment by rocksprings** [comment]
Can you please make sure each item is NOT connected to the other so that there is background space between each item?

**Comment by ValentineRain** [comment]
Hey! So I just talked to @BillPate , I think I understand where the miscommunication was.
He thought we meant the physical number for the date within each box. Now that he's told me, I can totally see it.

I asked him to separate the logo boxes and add the spaces there instead. Keep an eye out for another draft shortly. Sorry about that Bill! We could have been clearer.

**Comment by BillPate** [comment]
My mistake everyone. I read this as you wanted the numbers moved, and not the boxes. My mistake.
![aubron-alligators5](https://user-images.githubusercontent.com/31041645/31501873-74892592-af39-11e7-91a3-f5a638ee6e3a.jpg)

**Comment by rocksprings** [comment]
I like this.
Let's review as is tamale at the weekly meeting.

**Comment by ValentineRain** [comment]
Replace #Biteme with something. No chomping, either. Apparently that's a Florida thing.
Decrease ScoreShots logo and vertical spacing on bottom bar.

After this, go straight to design.

**Comment by BillPate** [comment]
Changes made, being put in the Engine.
![aubron-alligators5](https://user-images.githubusercontent.com/31041645/31555369-c641b7ca-b00e-11e7-8ba0-153cfb4ab5ea.jpg)

**Comment by adavila17** [comment]
👍

**Comment by rocksprings** [comment]
Approved as far as I am concerned.
Let's move on!

**Comment by BillPate** [comment]
Testing needed.. Template 696

@ValentineRain

**Comment by adavila17** [comment]
@ValentineRain this is not ready for your eyes.

@BillPate 

**Changes needed:**

1) Make 10 logo/border areas across all rows organize them in the layer preview in order. You will need to move logos if they are seated on the layer below.
2) Remove "Cropped Logo" from all layer names Layer Naming should be as follows: Opponent 1 Logo all the way to 60 once you have the missing spaces added in.
3) Numbers/Days of the month will need to be generic so all dates will be relabeled as "##"
4) Months will be generic relabel them as "Month"
5) Stroke color default is white until Aubron adds in our fix for selecting primary secondary or tertiary colors to stroke.
6) Hashtag default naming is "#hashtag"
7) Get rid of the green boxes you clicked the wrong icon for logo drop zones see image below for the correct tool.
8) The bottom bar needs to be team colored refer to image below to apply team colors to shapes.


**Refer to #7 change**
![qv6ipwf](https://user-images.githubusercontent.com/26416133/31620773-223ae7dc-b266-11e7-8cd3-2540eb814015.png)

**Refere to #8 change**
![wp88u00](https://user-images.githubusercontent.com/26416133/31621176-1893f056-b267-11e7-8b3c-62c33341baba.png)

More to come after these are changed.

**Comment by ValentineRain** [comment]
Thanks for the heads up. Adjusting labels.

**Comment by BillPate** [comment]
Ok I have made the requested updates.. I beleive this is ready for review with @ValentineRain 

Template 694

**Comment by BillPate** [comment]
My mistake I meant testing with @ValentineRain

**Comment by Aubron** [comment]
@ValentineRain to test
@BillPate to regenerate preview image.

**Comment by BillPate** [comment]
![aubron-alligators6](https://user-images.githubusercontent.com/31041645/32060559-0fd2d350-ba3d-11e7-88a6-ca96dfe5395d.jpg)

**Comment by BillPate** [comment]
Updated per @Aubron and @ValentineRain requests

**Comment by ValentineRain** [comment]
Thanks for updating the preview.
After a brief review, this template does not seem to have gone through development yet. It is not ready for testing.

Here are the dynamic positioning behaviors we're looking for in this one (it's a little different!):

- First, there will be a dropdown for "Starting Month". Options will range from January to December; the user's selection will go in the Month 1 space, and then continue linearly from there. If there are months left to display after December (because the user chose a late starting month), it should loop back around to January again.

- What follows this are 5 dropdowns, labeled for "Month 1", "Month 2", etc. Each will provide the user with a range from 0-10, with the text for 0 reading "No Games". This will determine the number of logo, text, and frame objects which are listed horizontally next to that month. 

- Selecting "No Month" will hide any of those logo, text or frame objects in that row, along with the month text. All objects that remain will be re-centered horizontally. So for example, if the user selects "No Games" for February in this image...:

![edit](https://user-images.githubusercontent.com/26412274/32073996-08729b3a-ba66-11e7-972a-c7b18b057257.jpg)

...That entire row will go bye-bye, and everything will be re-centered and spaced such that January is adjacent to March.

This one is complicated and we've argued about implementation internally on it for a long time so if you have any questions, let me or Adam know!

**Comment by ValentineRain** [comment]
Hey, this just in from @adavila17 , who has a different idea on how the dynamic steps should be handled. It might be less complicated for the user; can someone in development weigh in on this?

He'd like to just provide an option for "Number of Months", rather than starting month, which will affect the number of rows. The actual "Month" text will be just regular text fields which the user can fill in. That will more easily facilitate schedules with gaps in them, so users don't have to select "0" for a specific month of the year and do a bunch of shenanigans.

Easier? Harder?

**Comment by ValentineRain** [comment]
Also @adavila17 stop doing work on your vacation, I will fire you.

**Comment by BillPate** [comment]
Ok I apologize. I am confused as to what specifically I need to do to this..

Thanks

Bill

**Comment by ValentineRain** [comment]
Oh, @BillPate , none of those things are for you. Sorry! This is flagged for development.
You did your bit!

**Comment by Aubron** [comment]
That's fine. It's not my favorite, but it will facilitate quick turnaround. Unfortunately there were be unused dropdowns, but that's not the end of the world. (set to 3 rows, the 4th row month number of games dropdown will still exist.

@kelvin-im - please tackle this once @ValentineRain gets you an updated spec.

**Comment by ValentineRain** [comment]
Thanks, if you're good with this solution I'll redraft dynamic specs.

6 Dropdowns Total
1st one is named "Number of Months", range is 1-5.  At "5", all five rows of Month text, Logos, numbers, and border objects are visible. At "4", the bottom row of objects is hidden, and the remaining rows are re-centered vertically. This repeats as the list continues.
2nd-6th dropdown menus are labeled "Number of Games". Range is 1-10. Each additional step adds a logo and associated text/template objects to the row, beginning on the left .

The title and main logo might look a little weird as the row count decreases but the user can move them so I'm not going to stress about it.
Disregard everything else discussed above.

**Comment by kelvin-im** [comment]
Starting work on this one.

**Comment by kelvin-im** [comment]
Template should now have dynamic code. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/379

**Comment by ValentineRain** [comment]
Thanks @kelvin-im .

@adavila17 , if I could pretty please get you to take a run through here, create some custom rulers and re-align each of the text elements? They're all slightly out of either vertical or horizontal alignment. I also made a few edits here and there where I noticed things were out of place, but I just don't think I've got the eye for detail and you could do it much more efficiently than I can.

**Comment by adavila17** [comment]
I fixed the alignment issues this needs another dev pass for dynamicism.

**Comment by kelvin-im** [comment]
Modified dynamics based on alignment. Give it another go, @ValentineRain. Same PR as before.

**Comment by ValentineRain** [comment]
One issue I encountered; the logo spaces for hidden games are not being hidden. So you can set a given month to say, 4, then double click from the media manager and still add ten logos.

![not hidden logo](https://user-images.githubusercontent.com/26412274/32629703-135ee3a2-c568-11e7-94a1-b0b605d0f768.png)

On the bright side, they _are_ re-hidden if you change the total number of months!

**Comment by kelvin-im** [comment]
Alright, images should now be hidden along with it's corresponding row.

**Comment by kelvin-im** [comment]
Give it another go @ValentineRain, when you get the chance. Same PR as before.

**Comment by ValentineRain** [comment]
Hey, thanks, that issue is fixed!

It kills me to say this, but there's one more bug I just hit that needs to be fixed before we can release. It turns out that if you use the number of games dropdown before setting the number of months (as in, without touching the month dropdown), the number of displayed games will not update.

If you then change the number of months, everything updates to where it's supposed to be.
There's no console error either. It's kind of weird so [here's a video](https://drive.google.com/a/imsports.com/file/d/1cG0LkgTEWIfwki3nYybLCN0Kzj9hVlIz/view?usp=sharing).

**Comment by kelvin-im** [comment]
Alright, I've defaulted the number of rows to 5 if user hasn't selected a row yet. Should fix the above issue.  Give it another go @ValentineRain.

**Comment by ValentineRain** [comment]
Looks good! Let's ship this one.

**Comment by Aubron** [comment]
Merging.

**Comment by adavila17** [comment]
preview added but "Schedule Stats" needs to be changed to just "Schedule".

**Comment by ValentineRain** [comment]
@adavila17 , could you clarify what that means? I don't see that text anywhere on the preview.

**Comment by adavila17** [comment]
Because it's not in the preview image issue it's a layer name issue.

**Comment by rocksprings** [comment]
Yes, we do need to change "Schedule Stats" to "Schedule."

**Comment by kelvin-im** [comment]
@ValentineRain @adavila17, "Schedule Stats" has been changed to "Schedule" and has been updated on Dev side.

PR: https://github.com/Aubron/scoreshots/pull/400

**Comment by Aubron** [comment]
Schedule Stats change to Schedule has been merged, deployed to live. I think that's it?

**Comment by ValentineRain** [comment]
Yep, just double checked, everything still works.
I'm closing this task, hallelujah, and will be making another, separate thread to task copying this to Media Relations. I remember this being said verbally outside of a meeting at some point, and I'd like to preempt any further confusion on this template.
