### ISSUE TITLE
Arkansas State Media Relations Scoring Template

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#46]
![unnamed](https://user-images.githubusercontent.com/26412274/29678424-889bfd7c-88cc-11e7-9a85-b11cd869eb18.jpg)

### Requested by:
Mark Taylor, Arkansas State

## Template Description:

> Val,
> 
> We are trying to figure out graphics for in game football for a touchdown without having to use a photo. We like this look (without a photo) where you can play up the color template options with it just saying touchdown and then a short description of who scored while having the score at the bottom. An option for a picture would be nice but we don't expect to have enough photos to make it work. A simple background picture like a stadium shot perhaps.
> 
> Thanks for the help!

## Dynamic Considerations:
Probably none.

**Comment by ValentineRain** [comment]
I noticed this is missing some vital information. Below are the questions I have already asked the client, and am waiting on a response for.

> Hi there, Mark...
> 
> ...I've got a few questions though, to make sure I understand your needs. You'd like something similar to the attached image, but you'd like it to have just one background space for a stadium? And it should include text on who scored along with maybe some stats for that player?
> 
> It'd also be helpful for me to know whether you wanted this template to be exclusive to your school or not. For public templates, we'd need to it be generally useful enough that anyone could benefit, so we'd probably need to go the route of providing a background space which could house a stadium photo (which you would add during creation). If you were interested in creating an exclusive A-state branded template, however, we could add whatever static stadium image you wanted, since nobody else would be using it.

**Comment by ValentineRain** [comment]
Here's his response. This is a public template. I think we have everything we need.

> Simple text to describe the scoring play is all that’s needed.
>  
> Not looking for exclusive here. Background space is fine, just thought the lines/shapes on the attached image made for a cool effect which colors would be changed in the palette area.

**Comment by adavila17** [comment]
![ss_football_scoreshot3](https://user-images.githubusercontent.com/26416133/29776742-a7484d8a-8bd7-11e7-94bc-74fe0f3ebd04.jpg)

**Comment by ValentineRain** [comment]
I like it and will make sure we take a look at it at next review! One thing I will say though, is judging from the client's description, they don't own what this is based on. We might need to change it more overall.

**Comment by adavila17** [comment]
It's been changed enough. 10% or more qualifies as new.

**Comment by Aubron** [comment]
We've got to tweak this a little more.
And also use different stats than the example image :P

**Comment by adavila17** [comment]
There it's different I don't want to hear another word.

![ss_football_scoreshot3v2](https://user-images.githubusercontent.com/26416133/29839703-32fcf8b2-8ccd-11e7-9f7a-3efa7039883d.jpg)

**Comment by adavila17** [comment]
Val test temp ID 646

**Comment by ValentineRain** [comment]
I'm going to send this the client's way.

**Comment by ValentineRain** [comment]
Client likes this and wants to use it immediately. 🤷‍♀️

**Comment by ValentineRain** [comment]
The white "quarter" text in the top right is illegible by default due to it overlapping with the white logo boxes.

![thingo](https://user-images.githubusercontent.com/26412274/29844259-a481afc8-8cdc-11e7-99b7-21ea7cc0b127.png)

**Comment by ValentineRain** [comment]
Is it possible to set defaults for user logos in the admin panel yet?
It's possible to make the upper left logo in the clipped space work with a bit of work, but it might be more convenient to set it up with a colorize filter of the user's primary if that's possible! Otherwise you get this by default and have to tweak it (which is also fine)

![thing 2](https://user-images.githubusercontent.com/26412274/29844502-82a0cce4-8cdd-11e7-90f7-1df1c3808fe7.png)

**Comment by adavila17** [comment]
Val no that's petty nonsense. If the user can't grab their logo and appropriately resize that's on them.

**Comment by adavila17** [comment]
also I forgot the damn player cutout.

**Comment by adavila17** [comment]
ok done test again.

**Comment by ValentineRain** [comment]
This template is very, extremely broken in one specific way that will probably not affect most users, but [should still be priority fixed](https://github.com/Aubron/scoreshots/issues/267).

(Actually I lied Arkansas State already noticed this and I asked them to please pretend they didn't).

For future reference we should not add preview images to things that aren't verified to be ready, however, this is more my fault than anyone else's because I would not have caught this anyway.

**Comment by ValentineRain** [comment]
Man, look at that jumbled salad of labels.

**Comment by adavila17** [comment]
Did this bug get fixed @ValentineRain?

**Comment by ValentineRain** [comment]
Yeah, it did! This thread needs to be closed. Thanks for the reminder.
