### ISSUE TITLE
🎉🎊🎈 Arkansas Tech, Football Halftime Graphic

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#47]
![halftime-stats](https://user-images.githubusercontent.com/26412274/29717188-399784ca-897c-11e7-898c-b1732b2070d3.jpg)

### Requested by:
Paul Smith, Arkansas Tech

## Template Description:

> Hey Rick – had an idea on a scoreshot that might help us tremendously – a “halftime stats” scoreshot for football…
>  
> I’ve attached kind of an inspiration. Do you think this is something you would be able to put together?
>  
> Paul

> Thank you much. My preference would be for something rectangular. Think I could shoot this up to my video board and it’d look really sharp. Thanks again!

## Dynamic Considerations:
Probably none.

**Comment by ValentineRain** [comment]
Rick has already given the go-ahead on this one, so we'll skip straight to producing a design.

**Comment by ValentineRain** [comment]
I'm tired this morning, sorry.

**Comment by adavila17** [comment]
blah.....

![ss_football_snapshot3](https://user-images.githubusercontent.com/26416133/29790689-accca22a-8c08-11e7-9681-20972f6af004.jpg)

**Comment by Aubron** [comment]
Share this thing with Paul.

**Comment by Aubron** [comment]
Ping this to Rick.

**Comment by adavila17** [comment]
Ready for XML integration.

Temp ID 645

**Comment by ValentineRain** [comment]
Do we need to provide any specific instructions about how to handle different XML states? We might want to get a football expert to do so if necessary.

**Comment by adavila17** [comment]
@ValentineRain Did this get done?

**Comment by adavila17** [comment]
In any case this has fallen again. Not good.

**Comment by ValentineRain** [comment]
This one is still in development. Let's take a look at it on Monday to make sure we're all on the same page.

**Comment by Aubron** [comment]
This is in engine, template 645, but the auto-quarter features are not working. need Paul or someone to send us an XML file from an incomplete match, so I can determine the quarter from the XML file. Other than that, everything is working, and this is in engine. I have reached out to paul for the xml file.

**Comment by ValentineRain** [comment]
This template has been in the engine since September. I didn't notice it because it has the dev flag on it.
I'm going to go ahead and close it. If there's anything we still need to gather to fine-tune this, please make a basecamp thread.
