### ISSUE TITLE
Uniform Template Concept

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#48]
### Requested by:
Rick, Internal

## Template Description:

> Come up with a template design that showcases uniform top, bottom helmet, pants, etc. and maybe with a related theme (e.g., Black Out). Will use for football and M&W basketball I am thinking. Place draft in Git. Medium priority.

## Dynamic Considerations:
Probably none.

**Comment by adavila17** [comment]
![ss_football_previewshot_11](https://user-images.githubusercontent.com/26416133/29786751-611ab532-8bfa-11e7-9ea1-80217c6eaa9f.jpg)

**Comment by rocksprings** [comment]
Positive reply from NDSU, MSU, FSU, U8One2, so let's push ahead.

**Comment by adavila17** [comment]
@ValentineRain test sometime so it's ready before the this weekend

**Comment by ValentineRain** [comment]
Sorry I didn't make it to this one before the weekend. Taking care of it now.

**Comment by ValentineRain** [comment]
I think you forgot to set the logo clipping on this one:

![clipping](https://user-images.githubusercontent.com/26412274/30072681-17ace9d4-9239-11e7-9a60-dd2982ba9fd8.png)

It's also missing the background step entirely:

![bg step](https://user-images.githubusercontent.com/26412274/30072728-3e8a82dc-9239-11e7-879d-ee1143d56ba6.png)

Finally, for consistency the player cutout should probably be ordered before or after Team Logo's 1 and 2, but not between.

**Comment by adavila17** [comment]
@val retest

**Comment by ValentineRain** [comment]
Retesting now.

**Comment by ValentineRain** [comment]
This is good to go. Both the background issue and the logo clipping are fixed!

**Comment by ValentineRain** [comment]
This just needs a preview image and to be put into an appropriate category. What were you going to place it in, Adam?

**Comment by adavila17** [comment]
preview added

**Comment by ValentineRain** [comment]
Confirmed this is where it should be, under the football previewshots. I preemptively veto the suggestion to create a "UniformShot".

Just as a reminder, the task requests this be placed in the Basketball category as well. Can you duplicate this and tweak the preview image a bit? Going to leave this task open until it's everywhere it needs to be.

**Comment by ValentineRain** [comment]
👍 Sounds good.
I was going to suggest it but decided I didn't have enough sports knowledge.

**Comment by rocksprings** [comment]
Please let me know when it's in.

**Comment by ValentineRain** [comment]
Will do.

**Comment by adavila17** [comment]
In Media Relations. Working on BBall preview.

**Comment by adavila17** [comment]
Basketball Uniform preview image.

![ss_basketball_previewshot_uniform](https://user-images.githubusercontent.com/26416133/30337556-aa1cd874-97b6-11e7-9f57-93db28c75fa0.jpg)

**Comment by adavila17** [comment]
Is in Basketball

**Comment by ValentineRain** [comment]
It has been properly cloned to Basketball as well as Media Relations. I will send Rick a message about this on Slack, or he'll never see it.

The clipped logo zones work properly when cloned. Hooray! I'm closing this task.
