### ISSUE TITLE
FSU Golf StartingShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#49]
@ValentineRain test temp ID: 649

![ss_fsu_golf_startingshot](https://user-images.githubusercontent.com/26416133/29878668-1d6d4c0a-8d71-11e7-896f-4de1fd25110e.jpg)

**Comment by lisajohnson11** [comment]
Waiting to hear back if we can use same starting five for Basketball.

**Comment by ValentineRain** [comment]
Testing done. Everything works.

**Comment by adavila17** [comment]
@ValentineRain preview added
