### ISSUE TITLE
FSU Golf SnapShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#50]
@ValentineRain test temp ID: 647

![ss_fsu_golf_finalshot](https://user-images.githubusercontent.com/26416133/29878861-98f859dc-8d71-11e7-8b5c-8f87039794e8.jpg)

**Comment by ValentineRain** [comment]
The "Name" field in this template needs to have its layer raised above the "5&4" bit, or it is unclickable due to overlap.

**Comment by ValentineRain** [comment]
This is done. No other issues. Flag me again when the text is fixed?

**Comment by adavila17** [comment]
@ValentineRain done.

**Comment by ValentineRain** [comment]
Perfect. 
It's already got a preview image, no need to finalize.
