### ISSUE TITLE
FSU Golf Rectangle SnapShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#51]
![ss_fsu_golf_snapshotv2](https://user-images.githubusercontent.com/26416133/29878978-d84ac70a-8d71-11e7-8951-221ccbe0ef2b.jpg)

**Comment by adavila17** [comment]
@ValentineRain test temp ID: 652

**Comment by ValentineRain** [comment]
No issues. Preview image and then we're good to go.

**Comment by adavila17** [comment]
@ValentineRain preview added
