### ISSUE TITLE
FSU FinalShot Round by Round

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#53]
![fsu_golf_roundbyround](https://user-images.githubusercontent.com/26416133/29881651-310ec830-8d79-11e7-99ed-b05e19a52c18.jpg)

**Comment by lisajohnson11** [comment]
Approved.

**Comment by adavila17** [comment]
Needs dynamic treatment - **Temp ID: 653**

Drop down labeled "Number of Rounds" 2-4 rounds to select from.

Center horizontally & keep name box over round 1 at all times.

**Comment by kelvin-im** [comment]
I'll work on this one.

**Comment by kelvin-im** [comment]
Dynamicized. Ready for testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/278

**Comment by ValentineRain** [comment]
Starting on this one.

**Comment by ValentineRain** [comment]
Dynamic elements of this one work great. However, the score boxes, which are transparent in the preview, are defaulting to solid during creation, so that should probably adjusted. 

Let's lump that in with adding a preview image. Flagging this for merging!

**Comment by adavila17** [comment]
This one sucks to say.... 

@ValentineRain I had to add more shapes, background shapes that is because the opacity slider which was set to the solid/fill color was set to .6 or 60% and not working with the solid stroke around the object. 

We have this fixed for text with stroke and opacity on the fill color but not objects/shapes. 

This will need to go back to the Dev team since I added additional shapes that are not coded.

**Comment by ValentineRain** [comment]
Damn. Well, that's life.
Sorry @kelvin-im , we'll have to get you to return to this when you get the chance. :(((

**Comment by kelvin-im** [comment]
Alright, the code has been updated to the PR for the additional shapes. Give it another test @ValentineRain.

**Comment by lisajohnson11** [comment]
Client sent an email asking about this one. It is possible for it to be tested today?

**Comment by ValentineRain** [comment]
Sure thing.

**Comment by ValentineRain** [comment]
This is good to go! Sorry for the delay, there was some color weirdness we had to sort.
For record keeping purposes, the boxes had their color override set to "Primary", but also had a custom opacity set. The result was two fill boxes, which were collapsing strangely with object stroke in the palette step. We resolved this by unchecking the color override for each object.

**Comment by ValentineRain** [comment]
This will need a merge, tasked shortly, followed by a preview image. Please don't close 'til those are confirmed, kthnxbai

**Comment by Aubron** [comment]
This is going to live. keeping open.

**Comment by adavila17** [comment]
donzo

**Comment by lisajohnson11** [comment]
Okay! I'm good to share with the client? Thanks guys for pushing this through today.

**Comment by ValentineRain** [comment]
Yep!
