### ISSUE TITLE
FSU BirthdayShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#54]
![unnamed](https://user-images.githubusercontent.com/26416133/29881736-6a10e640-8d79-11e7-99d4-f3aca0d652bc.jpg)

**Comment by adavila17** [comment]
@ValentineRain test temp ID: 651

**Comment by ValentineRain** [comment]
This one is testing well (give me a few minutes), but it looks like the default stoke isn't set to the right color. It looks like it is neither Team-Colored, nor the FSU yellow pictured above.

See below: it's this dark gray, which is not currently in my team colors either.
The font itself is team colored and that's probably perfect for the client.

![stroke color](https://user-images.githubusercontent.com/26412274/30074570-05c2dc54-9240-11e7-8f42-8b7c46363780.png)

**Comment by ValentineRain** [comment]
Actually, I dunno, maybe this is right?

![thingo](https://user-images.githubusercontent.com/26412274/30074625-3a123ce8-9240-11e7-9d15-4b86172ba9bb.png)

**Comment by ValentineRain** [comment]
No other issues with this template. 
If this is how you intended, it'll just need a preview image and is otherwise ready to go.

**Comment by adavila17** [comment]
preview added
