### ISSUE TITLE
FSU Soccer StatShot

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#55]
Talked to Elliott this afternoon and they are good with the StatShots we already have with the FSU branding. Let's tweak a tiny bit if possible.

**Comment by adavila17** [comment]
![fsu_soccer_statshot](https://user-images.githubusercontent.com/26416133/29934927-ff366142-8e4a-11e7-92ea-bc6796793b63.jpg)

@lisajohnson11 send NAO!!

**Comment by lisajohnson11** [comment]
Sent for approval.

**Comment by lisajohnson11** [comment]
Approved by the client 9/12 email.

**Comment by adavila17** [comment]
@ValentineRain test template ID: 666 <---- DEVIL TEMPLATE!!!!!!!!!!

**Comment by ValentineRain** [comment]
Unless there's a PR I can't see, this actually needs to go to development next. Currently it has no dynamic elements; no XML, no stat step, nothing. There's nothing to test.

Changing flags.

**Comment by kelvin-im** [comment]
I'll work on this one.

**Comment by kelvin-im** [comment]
This template should now have the dynamic and XML code. Should function similarly to the Soccer template we currently have.

Also found a fix for soccer template 314 issue (will comment later). Apparently resetting the palette of the bar graphs restores the proper positioning of the bar graphs. I believe we ran into this issue before, it seems familiar...

Anyways, was able to kill two birds with one stone on this one. Ready for review/testing @ValentineRain. 

PR: https://github.com/Aubron/scoreshots/pull/290

**Comment by ValentineRain** [comment]
There's a mysterious layer appearing here, which is transparent by default. When interacted with (by changing its color) it ends up looking like this.

![thingo](https://user-images.githubusercontent.com/26412274/30703531-f9fbdaa8-9ebd-11e7-92aa-cd0d8b4fa56f.png)

What is this layer for, and can we get rid of it? I dunno if this is a design or a development issue.

**Comment by ValentineRain** [comment]
Also the [secondary issue is definitely resolved](https://github.com/Aubron/scoreshots/issues/248) in this one! So good job on that.

**Comment by ValentineRain** [comment]
Shouldn't the "School Name" field be filled in via XML as well?

**Comment by kelvin-im** [comment]
@ValentineRain, above was a Dev issue. The transparent fill color was somehow added to the palette step for those circles. I've changed the way it's filled, so it should be hidden now.

For the XML values, the School Names aren't filled with the original Soccer template either. Right now both are consistent with one another.

Give it another go when you have time. Same PR.

**Comment by ValentineRain** [comment]
> For the XML values, the School Names aren't filled with the original Soccer template either. Right now both are consistent with one another.

That's good enough for me!

The above changes were successful, too. This is ready to merge, and then needs a preview image.

**Comment by Aubron** [comment]
Merged to live. Waiting on @adavila17 for preview image.

**Comment by adavila17** [comment]
preview added
