### ISSUE TITLE
FSU Volleyball StatShot

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#56]
Talked to Elliott this afternoon he's good with using the Volleyball StatShot and throwing on the FSU branding.

**Comment by adavila17** [comment]
BLLLLLLLLLLLAAAAAAAAAAAAAAAAAHHHHHHHHH

**Comment by adavila17** [comment]
![fsu_volleyball_statshot](https://user-images.githubusercontent.com/26416133/29932885-998f4144-8e43-11e7-8664-2eb4bf33e628.jpg)

**Comment by adavila17** [comment]
@lisa send to client

**Comment by adavila17** [comment]
nvm wait gotta change the name of the player

**Comment by adavila17** [comment]
![fsu_volleyball_statshot](https://user-images.githubusercontent.com/26416133/29932962-e0f86aa6-8e43-11e7-821a-f97d902c79f2.jpg)

@lisajohnson11 send this one over

**Comment by lisajohnson11** [comment]
waiting for soccer StatShot to send both over at the same time @adavila17

**Comment by lisajohnson11** [comment]
sent for approval.

**Comment by lisajohnson11** [comment]
Approved by the client 9/12 email.

**Comment by adavila17** [comment]
Last stat shot until we do another...... ^_^

TEMP ID: 669

**Comment by adavila17** [comment]
Copy statshot code from template 640 into this one!

**Comment by kelvin-im** [comment]
On it.

**Comment by kelvin-im** [comment]
Dynamicized. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/293

**Comment by ValentineRain** [comment]
Couple of edits needed for this one. I think they're for @adavila17 on the admin side.

The background drop zone is a few pixels too high, so you can see  a gap in the objects over it. Screenshot below, bottom left.

![background clipping](https://user-images.githubusercontent.com/26412274/30702291-92e0509a-9eba-11e7-935d-1758aeba5c96.png)

Second is that the background area is not clipped to that space, so I can only use the very left side of my photo.

**Comment by adavila17** [comment]
Fixed that.
It is the dumb duplicate button thing where I have to uncheck it for full bg image again.... annoyance.

**Comment by ValentineRain** [comment]
Good to go!

**Comment by Aubron** [comment]
Template merged to live. Please add preview image.

**Comment by adavila17** [comment]
preview added.
