### ISSUE TITLE
FSU Big Play: Homerun

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#59]

**Comment by adavila17** [comment]
![fsu_scoreshot](https://user-images.githubusercontent.com/26416133/29927013-106bd13a-8e33-11e7-8b99-6c12cd971a6e.jpg)

Not done waiting on Lisa to give me cutout

**Comment by adavila17** [comment]
closing bc this template will exist as another template that can be specified for any other sport.
