### ISSUE TITLE
Sports-Agnostic Playershot

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#6]
![preview](https://user-images.githubusercontent.com/26412274/28725556-cf5139a4-738b-11e7-92f2-910fdf28ff9e.png)

## Requested By:

Internal, 8/4/17

## Sharing & Intended Use:

Public, Media Relations. Could optionally be made available in individual sports.

## Template Description:

Description from Adam below.

> Adding this one into the mix it's a PlayerShot. Very typical in MLS and other leagues to announce the best XI players in the league per position each week. If someone wanted to change the left bar's text they could do so and make it a quote from the player.

## Dynamic/Programming Considerations:

N/A

**Comment by ValentineRain** [comment]
This template sort of fell off of everyone's radar. Adam was tasked to add a space for a conference logo and at least two generic stat fields.

**Comment by adavila17** [comment]
Temp ID 620

**Comment by ValentineRain** [comment]
Hey, it looks good. But unless I'm missing something, you didn't actually add either of the things Rick requested above.

![whyadamwhy](https://user-images.githubusercontent.com/26412274/29141039-9b2e2d42-7d1a-11e7-9473-d3aaca127410.png)

`Adam was tasked to add a space for a conference logo and at least two generic stat fields.`

**Comment by ValentineRain** [comment]
My bad, didn't mean to close.
