### ISSUE TITLE
Conference Standings Template, But Smaller

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#61]
## Requested By:
Brandon Trip, Heartland Conference
Public Template

## Template Description:

> I saw that one standing graphic is up online. Are they coming out with templates that do not divide into divisions?

@adavila17 proposes that we reduce the original rectangular version to a single column. I second this. It should be an easy edit.

## Dynamic/Programming Considerations:

- Dropdown, number of games. On the requested number:

> We are in an odd position. The max number we would need is 9 for a single-division format. Additionally, we need a three-division format since we have affiliate members in men's soccer in which the maximum is 4 in each division.

The 3 division variant is outside the scope of this task. Let's take them one at a time please.

## Example Images / Additional Resources:

Original, rectangular version to be modified:

![627](https://user-images.githubusercontent.com/26412274/29934566-b34aa85c-8e49-11e7-9e35-887a1e9efcd1.jpg)

**Comment by ValentineRain** [comment]
Tag Marissa to research how our conference partners display their standings.

**Comment by ValentineRain** [comment]
Also tell the client we'll do the square.

**Comment by marissab1** [comment]
![cacc conference standings1](https://user-images.githubusercontent.com/31700405/30173075-8f1e14c0-93c4-11e7-9cee-94db6dcbfebe.PNG)
![maac mini standings](https://user-images.githubusercontent.com/31700405/30173072-8f1ad36e-93c4-11e7-9a9c-ab29c45c60cb.PNG)
![pacweststandings](https://user-images.githubusercontent.com/31700405/30173074-8f1da4ea-93c4-11e7-9927-0958f3e145e8.PNG)
![psac standings](https://user-images.githubusercontent.com/31700405/30173073-8f1c692c-93c4-11e7-9165-97cf17b0bf22.PNG)
![redriverstandings](https://user-images.githubusercontent.com/31700405/30173076-8f251b80-93c4-11e7-8956-920f2c2c7e64.PNG)
![sac mini standings](https://user-images.githubusercontent.com/31700405/30173077-8f27de60-93c4-11e7-988e-5096af07338b.PNG)
![sac standings](https://user-images.githubusercontent.com/31700405/30173080-8f3472a6-93c4-11e7-9680-a71f2614454a.PNG)
![skylinestandings](https://user-images.githubusercontent.com/31700405/30173078-8f2ad5fc-93c4-11e7-9066-e9fea8a76738.PNG)
![skylinestandings2](https://user-images.githubusercontent.com/31700405/30173079-8f2b72d2-93c4-11e7-9ff0-773b44cd49a7.PNG)

**Comment by ValentineRain** [comment]
Thanks Marissa!

**Comment by adavila17** [comment]
Ready for review. Really be nice if there was an XML but I think Rick said there was no such thing.... anyway 18 teams. I don't want to hear about needing more. It is not going to happen.

![ss_conference_standings_v1_square](https://user-images.githubusercontent.com/26416133/30281390-3e6f49f8-96e0-11e7-95c1-95a6243f9148.jpg)

**Comment by adavila17** [comment]
I'm going to start making this on the admin side. If we need to add fields or whatever I'll readjust we need to get this one out the way.

**Comment by adavila17** [comment]
Done. Until further notice. Temp ID: 671

**Comment by ValentineRain** [comment]
This template will need the ol' dynamic treatment, to show or hide each logo and its corresponding lines of text. Should go from 1-18.

**Comment by ericmoore1** [comment]
This is ready for testing. See https://github.com/Aubron/scoreshots/pull/294

**Comment by ValentineRain** [comment]
I think this template is good to go but I want to take another pass in at least one more browser.
It is being affected by [this bug](https://github.com/Aubron/scoreshots/issues/300), but it is not specific to this template, so I don't believe it should block deployment.

Will get back to this in just one sec.

**Comment by ValentineRain** [comment]
Yep, it's good! Thanks @ericmoore1 !

**Comment by Aubron** [comment]
Live.
