### ISSUE TITLE
Ragin Cajuns, Scoring Template

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#62]
### Requested by:
Jeff Schneider, Louisiana Lafayette

![2017 08 25_in-game_scores_01 1](https://user-images.githubusercontent.com/26412274/29943069-fc00c3ee-8e65-11e7-8027-21fd35e002b4.jpg)

## Template Description:
Jeff Schneider, of the Ragin' Cajuns, originally asked for three variations of this template. On examination, it looks like just one version would suffice (the one above). Since the differences are all text elements, he'll be able to delete or change the fields that aren't quite the same, instead.

## Dynamic Considerations:
None

## Additional Files
[Here's a .PSD for you, Adam.](https://drive.google.com/a/imsports.com/file/d/0BwH5-fbQakiybzFBbEFWTmtLSFU/view?usp=sharing)

**Comment by ValentineRain** [comment]
This template was requested for this Saturday, so it is high priority. 

Apparently I dropped the ball on the timing for this one, so I sincerely apologize, specifically to @adavila17 , who's life I made difficult with my being inconsiderate. I'm really sorry.

**Comment by adavila17** [comment]
This is going to have two states for FinalShot and one state for SnapShot. Because if they don't win that graphic is a no go. Although we can just not do snapshot it would be redundant really... ask your peeps if FinalShot with and without graphic is fine.

**Category Louisiana Lafayette**

temp ID with graphic is **655**
temp ID without graphic is **656**

**Comment by ValentineRain** [comment]
Yeah, he seems good on this. Did you need any fonts for this? He sent me an email that was supposed to contain the fonts he was using, which didn't quite make it to me intact, but if you need them I'll request them again.

Otherwise, starting on these now.

**Comment by adavila17** [comment]
I used close to a match as possible fonts that we have available i don't think it's a make it or break it situation. He can go in and change the fonts and save a draft to work from or save to library.

**Comment by ValentineRain** [comment]
I found one bug which appears to be engine-wide, and will be reported separately. 
The only other thing is that we should adjust 656 to read either "Kickoff" or "Halftime" by default, and update the preview image to match; I know this makes no difference but from a customer service standpoint I think it will help it more closely match what was requested.

Other than that, these are good to go. I'll add the category to his account and let him know that they're available in this state, and we'll be happy to make any adjustments once he's reviewed.
