### ISSUE TITLE
Villanova Player Stat Template

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#63]
### Requested by:
Michelle Ruel, Villanova

## Template Description:
Client contact:

> We would like to get two customized graphics made. One to feature a players stats either during or after a game, that has room for either an action shot or cut out photo.

> The NovaAutographCardBkgd in the attachment is what we use for the background of most of our graphics, and in the dropbox below are examples of graphics we have made just to give you a better feel for what we are looking for.  

## Dynamic Considerations:
None

## Additional Files
[Here's a link to their dropbox](https://www.dropbox.com/sh/r1zpztn76wj1k0i/AAAeIur3LrX6sRH2LSCOqmDPa?dl=0). They'd like something stylistically similar, but _not identical_. You can use these as a base.

Additionally, [here are some of their image and font assets](https://drive.google.com/a/imsports.com/file/d/0BwH5-fbQakiyT0drbjVBRmJ5aDg/view?usp=sharing) that you can use.

**Comment by ValentineRain** [comment]
Due date for this is September 16.

**Comment by adavila17** [comment]
![villanova_playershot](https://user-images.githubusercontent.com/26416133/30114793-d9554d44-92e6-11e7-9fa5-379492872d52.jpg)

**Comment by ValentineRain** [comment]
Flagging this to be sent to the client for approval. I think it looks good!

**Comment by adavila17** [comment]
![villanova_playershot2](https://user-images.githubusercontent.com/26416133/30161784-fe2722aa-939f-11e7-8c1d-57efb26039b2.jpg)

**Comment by ValentineRain** [comment]
Sent to client for approval again!

**Comment by adavila17** [comment]
@val test temp ID: 659

**Comment by Val** [comment]
@adavila17 : Could you please stop invite me in all of you issues using @Val in your messages and use provided completion if needed to write @ValentineRain ??

**Comment by ValentineRain** [comment]
Whoops, sorry about that, fellow Val! 
I'll go make fun of him at his desk and he won't do it again.

**Comment by ValentineRain** [comment]
@adavila17 Top left text fields defaulting to ScoreShots green.

![untitled2](https://user-images.githubusercontent.com/26412274/30224140-9f874430-949b-11e7-943d-c478b3ee6276.png)

**Comment by ValentineRain** [comment]
I actually just went ahead and fixed the above in the back-end. Sorry!

**Comment by ValentineRain** [comment]
Client has been given access to the category. Closing! Thanks for your hard work @adavila17
