### ISSUE TITLE
Modify Football Statshot, XML Integration

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#65]
![381](https://user-images.githubusercontent.com/26412274/29973855-f5c55384-8efe-11e7-850a-16f61d796e5e.jpg)

### Requested by:
Internal

## Dynamic Considerations:
Adding XML integration to template 381, pictured above. No other edits should be needed.

**Comment by Aubron** [comment]
https://github.com/Aubron/scoreshots/pull/265

**Comment by ValentineRain** [comment]
This has been merged. Task is done, closing.
