### ISSUE TITLE
FSU Drafted

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#66]
![fsu_drafted](https://user-images.githubusercontent.com/26416133/30074869-113d559a-9241-11e7-9628-c979160ad995.jpg)

**Comment by ValentineRain** [comment]
Dinging @lisajohnson11 , who I think needs to send this by FSU?

**Comment by lisajohnson11** [comment]
Approved by the client 9/12 email.

**Comment by adavila17** [comment]
@ValentineRain please test temp ID: 667

**Comment by ValentineRain** [comment]
This one works. I had a single crash in Firefox which was odd but it did not persist beyond a hard refresh.
Needs a preview image.

**Comment by adavila17** [comment]
added
