### ISSUE TITLE
Template ID: 381 Football

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#67]
Possession Time Circle is not starting in the right location it should start at the vertical top center, not the horizontal center right.

![slack-imgs](https://user-images.githubusercontent.com/26416133/30272465-a49ae6d8-96c2-11e7-8b7e-aeff38a4e593.png)

**Comment by kelvin-im** [comment]
Taking a look at this one.

**Comment by kelvin-im** [comment]
Alright, should be fixed now. Needed to revise the start and end points for the graph. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/280

**Comment by ValentineRain** [comment]
This looks good to go, @adavila17 reviewed it and confirmed this is as intended. Good job!

**Comment by ValentineRain** [comment]
Will close this once it's been merged.

**Comment by adavila17** [comment]
bc it's a template @ValentineRain  and this is where templates/template bugs should go.

**Comment by ValentineRain** [comment]
This will probably remain open until next week; it's too late to merge things this week.

**Comment by Aubron** [comment]
This is going to live.
