### ISSUE TITLE
FSU committed

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#68]
![ss_fsu_playershot3](https://user-images.githubusercontent.com/26416133/30290580-d63a2664-96fd-11e7-9e72-80c60988baf5.jpg)

**Comment by adavila17** [comment]
@lisajohnson11 share with FSU I am sure there'll be feedback.

**Comment by lisajohnson11** [comment]
Sent for review, but I'm not sure if they're in the office because of the hurricane.

**Comment by lisajohnson11** [comment]
Approved by the client 9/12 email.

**Comment by adavila17** [comment]
@ValentineRain test temp ID: 665

**Comment by ValentineRain** [comment]
For some reason the media manager button isn't appearing for background images.

![image](https://user-images.githubusercontent.com/26412274/30405356-4b2e2c42-98b9-11e7-804b-1223f11c94ab.png)

**Comment by ValentineRain** [comment]
In this episode of "Val can't read", Val can't read!

**Comment by ValentineRain** [comment]
Yeah, no, actually, this template works perfectly. Ignore me.

**Comment by adavila17** [comment]
preview image added
