### ISSUE TITLE
Template for Individual Poll Rankings

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#70]
![unnamed](https://user-images.githubusercontent.com/26412274/30336589-a50c44f8-97b3-11e7-860d-2f20ffae6e73.jpg)

![bcws_naia17_1_headline](https://user-images.githubusercontent.com/26412274/30336684-ebef520c-97b3-11e7-8669-f9b5958ecae7.jpg)

### Requested by:
Benedictine College's Josh POUND, which is a really cool name.

## Template Description:

> One graphic I can’t seem to locate is a national poll graphic for just a single team that showcases just that teams ranking. I don’t really have some examples. I have been able to modify a graphic to work, but it only works in rectangle and not a square.
>  
> I’m going to have three sports inside the Top 25 likely for the rest of the fall and so I would love to have something that features them individually without having to plug in the entire top 25 poll to a graphic every Monday and Tuesday.

> Please do share with everyone else in the system. I would think that I’m not the only one, especially among your NAIA clients, that would benefit from something like this. Not sure how these would translate to squares as well, but if you can figure out something that can be used in both situations, that would be ideal.

## Dynamic Considerations:
N/A

**Comment by ValentineRain** [comment]
This request has been approved by @rocksprings for design, and he mentioned he'd like to be pinged for feature suggestions.

**Comment by adavila17** [comment]
![ss_pollshot_v3](https://user-images.githubusercontent.com/26416133/30384644-e12ed4fe-9872-11e7-83a8-04b1eed4c85d.jpg)

**Comment by rocksprings** [comment]
So only responding to the original post. . .
We need a text space for the given week or the date.
And a space for identifying the next game.

**Comment by adavila17** [comment]
I have "Week 3" under AP. 
I don't think identifying next game is the route to take as it would be coming in the next post as a PreviewShot anyway that same week. Also, we have some FinalShot templates with fields that a team can identify next game information.

I have provided some PollShot examples and all are very similar in nature and do not use the next game concept.

![di-xnbsuwaa7fki](https://user-images.githubusercontent.com/26416133/30554481-ac577de0-9c72-11e7-89f5-ef2653fd19ef.jpg)

![cua5eznwaaevxpz](https://user-images.githubusercontent.com/26416133/30554489-b1b0157c-9c72-11e7-86d9-757b3c8de53a.jpg)

![ap_preseason_ranking](https://user-images.githubusercontent.com/26416133/30554493-b508efdc-9c72-11e7-84e6-aadba731f91b.jpg)

![iydacpinueacpur 20170110145722](https://user-images.githubusercontent.com/26416133/30554521-d035d4f0-9c72-11e7-9394-d45e1fd1c028.jpg)

**Comment by ValentineRain** [comment]
Flagging this so we can talk about it in today's meeting.

**Comment by rocksprings** [comment]
Quite honestly this just isn't working too well.
As soon as I share what I want to see you either don't do it or argue about it.
I am going to has us task Bill so we can push some things ahead.
Val, would you please see if Bill can pick this up for us?
Thanks.
Rick

**Comment by adavila17** [comment]
![ss_pollshot_v3](https://user-images.githubusercontent.com/26416133/30594250-71cdfe8e-9d1b-11e7-91a2-465be6d68390.jpg)

**Comment by rocksprings** [comment]
Let's at least give them a date for the next game.
Then we should be good.

**Comment by adavila17** [comment]
![ss_pollshot_v3](https://user-images.githubusercontent.com/26416133/30596496-43466608-9d22-11e7-9048-8a080e36e340.jpg)

**Comment by ValentineRain** [comment]
Thank you @adavila17 ! I'm going to send this by the client for review.  ❤️

**Comment by ValentineRain** [comment]
Client approves of this design, go for it!

**Comment by rocksprings** [comment]
I think we are good to share it in next template meeting!

**Comment by ValentineRain** [comment]
Finished testing, delivered it to the client who wanted it right away.
