### ISSUE TITLE
FSU Schedule Template

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#71]
High prio sorry they need for Thursday blame @lisajohnson11.

You will probably need this link because it is bigger than any of our other templates and set to a custom size. 

Link:
https://scoreshots.com/index.php/category/editor/2044/919/43/664

Template ID 664
Category Florida State

Drop down labeled "Number of Games"
12-32 for now should suffice.

Center row of logos and shapes and text horizontally on the template when reducing the number of games.

![unnamed](https://user-images.githubusercontent.com/26416133/30345054-b9f4dcfe-97d1-11e7-98f9-f76c0e81dab4.jpg)

**Comment by kelvin-im** [comment]
@ValentineRain, I will start on this one; **but I will forewarn right now**, this is lot more complex than the other templates, and may not be done by EOD.

**Comment by ValentineRain** [comment]
Thanks @kelvin-im , do your best! Truth be told this is the first I've heard of it either.
Good luck!

**Comment by Aubron** [comment]
I have done this, and would like for it to be reviewed.

https://github.com/Aubron/scoreshots/pull/284

That being said, this template will not currently be visible in our engine, even with a preview image, because it is irregularly sized. Now I have to go do that.

**Comment by ValentineRain** [comment]
Sweet. I'll prioritize this one.

**Comment by Aubron** [comment]
I have just pushed a change to master that will cause this template to show up in template selection for ultrawide templates.

**Comment by ValentineRain** [comment]
Finished testing the PR; sorry I took so long with it. I encountered an odd issue in Edge in which the browser would stop responding, which persisted for just a few attempts before disappearing. Further reps show that it's working just fine, though. I'm chalking it up to Edge just being bad in general.

No issues found overall. They work fine in drafts and libraries as well, including when using video. Going to check out the master branch next to see how the thumbnails are holding up.

**Comment by ValentineRain** [comment]
The thumbnail thing on the master also works.
This probably will not surprise you, but attempting to add a thumbnail in the PR (without the fixes to master), causes the template to not load when selected. This is probably because the additions from the master weren't present, but it does make me want to do a follow up test once both of these elements are merged.

**Comment by Aubron** [comment]
This has been merged to live. Please confirm your fixes and add your preview images.

**Comment by adavila17** [comment]
preview added.

**Comment by ValentineRain** [comment]
This works! Thanks for your hard work~
