### ISSUE TITLE
Bowling PreviewShot #1

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#72]
Like zero stock footage of people who look like they are in college bowling.... this is all I can do for a background image for now.

![ss_bowling_previewshot1](https://user-images.githubusercontent.com/26416133/30436180-87980c4a-9939-11e7-9a84-fcf5f97bd264.jpg)

**Comment by ValentineRain** [comment]
As requested, I have reached out to Arkansas State, as well as Lawrence Tech and Blue Mountain College, for feedback on our bowling designs. I included this one in the list just to fill it out.

**Comment by ValentineRain** [comment]
I'm going to paste our most recent feedback for all of he bowling templates in the relevant threads. We should talk about how to incorporate this stuff in the next review meeting, because it is waaaay over my head.

This is from Arkansas State:

> As for feedback, I think they look great. My only concern would be that you can get seven games on the first one in there for seven-game Baker matches, but that does look great and can be used for the five-game Baker matches. I think it would be good to add somewhere on there the total score. And I’m getting real technical and bowling is about as weird a sport as there is, but the five-game Baker matches take the total pins to determine the winner so maybe something that adds them up beside the team names.
>  
> The second one works great for the seven-game Baker matches that are usually on the final day of the tournaments. It would also be cool to have enough space to type in say 1,015 for team one to 1,002 for team two because that is what the scores are on five-game Baker matches and traditional team matches. But I like that one a lot, looks clean and right to the point.
>  
> Another design that would be cool, and again, I know I’m being hard to follow because bowling is so different, but on the second day of tournaments they play traditional team matches so five individual players bowl 10 frames each. It would be neat to have a graphic that lists all five players in the lineup and able to put their score beside their name with the total team score at the bottom and just a place to put the opponent’s total score. We don’t always get the scores for the individuals, but when we do that would be a cool graphic to add.
>  
> That’s a good start though and they all look great to me! Bowling is just really complicated. It took me a lot of time to get it as well, so I’m good to answer any other questions because I know a lot of that is confusing.
>  
> Thanks!

**Comment by ValentineRain** [comment]
This came in from LTU:

> I would use them for sure, however in the naia we only play in tournaments. I would love one that has a top five for teams and for players.

**Comment by Aubron** [comment]
Moving to engine, maybe adjust text skew?, add to multiple sports.

**Comment by ValentineRain** [comment]
Add preview image, copy to media relations, then tell Val she's pretty.

**Comment by adavila17** [comment]
Test temp ID: 726

**Comment by ValentineRain** [comment]
This one needs to have its background space confined to the left-hand side. It's currently fullscreen.

**Comment by adavila17** [comment]
donzo

**Comment by ValentineRain** [comment]
Works! Added a preview image, this one's done.
