### ISSUE TITLE
Bowling FinalShot #1

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#73]
![ss_bowling_finalshot1](https://user-images.githubusercontent.com/26416133/30447267-88c904f0-9959-11e7-9eb2-3c61d9e9488e.jpg)

**Comment by Aubron** [comment]
Add sponsor logos. Take a protractor to it. Send to partners. @ValentineRain

**Comment by Aubron** [comment]
Arkansas State, Redwolves, mentioned as a bowling partner.

**Comment by adavila17** [comment]
Meh ready to be tested. Temp ID: 678

**Comment by ValentineRain** [comment]
I have reached out to Arkansas State, as well as Lawrence Tech and Blue Mountain College, for feedback on the designs. In order to keep things moving forward I'm going to go ahead and review these templates, and we can reopen the task for edits later if need be.

**Comment by ValentineRain** [comment]
The left-hand background photo space in this template is not clipped to that space and should be!

**Comment by ValentineRain** [comment]
Everything else is fine!

**Comment by adavila17** [comment]
yeah i fixed it.

**Comment by ValentineRain** [comment]
Perfect! 
Please add a preview image so we don't forget later, and we'll leave this thread open until we get that client feedback.

**Comment by adavila17** [comment]
preview added

**Comment by ValentineRain** [comment]
I'm going to paste our most recent feedback for all of he bowling templates in the relevant threads. We should talk about how to incorporate this stuff in the next review meeting, because it is waaaay over my head.

This is from Arkansas State:

> As for feedback, I think they look great. My only concern would be that you can get seven games on the first one in there for seven-game Baker matches, but that does look great and can be used for the five-game Baker matches. I think it would be good to add somewhere on there the total score. And I’m getting real technical and bowling is about as weird a sport as there is, but the five-game Baker matches take the total pins to determine the winner so maybe something that adds them up beside the team names.
>  
> The second one works great for the seven-game Baker matches that are usually on the final day of the tournaments. It would also be cool to have enough space to type in say 1,015 for team one to 1,002 for team two because that is what the scores are on five-game Baker matches and traditional team matches. But I like that one a lot, looks clean and right to the point.
>  
> Another design that would be cool, and again, I know I’m being hard to follow because bowling is so different, but on the second day of tournaments they play traditional team matches so five individual players bowl 10 frames each. It would be neat to have a graphic that lists all five players in the lineup and able to put their score beside their name with the total team score at the bottom and just a place to put the opponent’s total score. We don’t always get the scores for the individuals, but when we do that would be a cool graphic to add.
>  
> That’s a good start though and they all look great to me! Bowling is just really complicated. It took me a lot of time to get it as well, so I’m good to answer any other questions because I know a lot of that is confusing.
>  
> Thanks!

**Comment by ValentineRain** [comment]
This came in from LTU:

> I would use them for sure, however in the naia we only play in tournaments. I would love one that has a top five for teams and for players.

**Comment by adavila17** [comment]
pin count added.
