### ISSUE TITLE
soccer finalshot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#75]
new temp concept.

![ss_soccer_finalshot3](https://user-images.githubusercontent.com/26416133/30548219-92206008-9c5f-11e7-9927-3760ba26b570.jpg)

**Comment by adavila17** [comment]
Temp ID: 672

**Comment by Aubron** [comment]
Text size.

**Comment by Aubron** [comment]
One more logo spot.

**Comment by adavila17** [comment]
ready to test

**Comment by ValentineRain** [comment]
The extra logo space you duplicated still has the same name. As a result, when you add a logo to the 4th space, the 3rd one disappears.

![logo space name](https://user-images.githubusercontent.com/26412274/30705956-f765a74a-9ec4-11e7-9d73-a491262c5e8f.png)

**Comment by adavila17** [comment]
fixed

**Comment by adavila17** [comment]
retested and added preview image.
