### ISSUE TITLE
Multisport new PreviewShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#76]
New concept PreviewShot

![ss_basketball_previewshot5](https://user-images.githubusercontent.com/26416133/30548482-416b7d5e-9c60-11e7-9d3e-a815d78c3bbd.jpg)

**Comment by adavila17** [comment]
Temp ID: 673

**Comment by Aubron** [comment]
Add logo spaces just in case, even if they're not represented.

**Comment by adavila17** [comment]
ready to test

**Comment by ValentineRain** [comment]
This looks good overall, however I think you forgot to adjust the logo positioning for the teams that you added.

![logo layer](https://user-images.githubusercontent.com/26412274/30705779-6d2b3428-9ec4-11e7-8e38-9b63675f23d8.png)

**Comment by adavila17** [comment]
fixed

**Comment by ValentineRain** [comment]
Just want to make 100% that you intend them to be overlapping with the text?

**Comment by ValentineRain** [comment]
Okay, cool, @adavila17 explained this to me. They have that positioning so they can replace the text entirely if the user wants. That makes more sense to me.

This needs a preview image; let me know what category it is meant to be in so I can double check and we can close.

**Comment by adavila17** [comment]
image added.
