### ISSUE TITLE
Head-to-Head Stat Preview

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#77]
### Requested by:
UNCW, Eric Rhew
Probably public.

## Template Description:

> Tom Riordan and I were chatting this morning about graphics and one suggestion we were wondering about is the creation of a head-to-head team stats graphic that could be used before a game.
 >I believe you have a head-to-head individual stats graphic in baseball, but wanted to see if there was the possibility of using an XML file to create something on a team comparison for soccer.
> I am sure this could be something to use for other sports, but soccer was the first one we thought of.
 >I have attached a team stats XML file that STAT CREW produces. If you want to take a look at that file and see what data could be pulled from that, please feel free.
> I think keeping it to the basics (W-L record, Goals per game, Goals Against Average, Shots Per Game) would be best. Probably also having the option to upload each team’s XML file would be helpful as well.
> This is something that can be developed over time – not something we would need right away.
> Please let me know your thoughts when you have a chance.

## Dynamic Considerations:
Probably lots.

**Comment by ValentineRain** [comment]
We'll take a look at this task during the next review, before anyone works on it, to pin down the details.

**Comment by Aubron** [comment]
Add that actual XML file because you forgot it.

**Comment by ValentineRain** [comment]
[Here's the XML file](https://drive.google.com/a/imsports.com/file/d/0BwH5-fbQakiyeEpMNEg0UkplNTQ/view?usp=sharing). It turns out it was just not included in the email.

**Comment by adavila17** [comment]
@ValentineRain please pull out of google drive and save in here for the team to look from.

Thanks!

**Comment by adavila17** [comment]
So until @ValentineRain get's me an xml I am not locked out of.... here's what I have

![ss_soccer_statshot2](https://user-images.githubusercontent.com/26416133/30714166-dbd47bbc-9edf-11e7-947b-2c1a1cb15814.jpg)

**Comment by Aubron** [comment]
@lisajohnson11 , [notify GAC when complete](https://github.com/Aubron/scoreshots-templates/issues/80).

**Comment by adavila17** [comment]
Just so we're clear this is for multisport use so the language will be generic Stat 1, Stat 2, Stat 3.... etc.

**Comment by adavila17** [comment]
Ready for Dev team temp ID: 680 

Need a Stats area on the client side. Each stat will be labeled generically since this will be for multiple sports. Just need the bars to work. The higher number is filled out entirely lower number adjusts to that.
Team 1 has overlays 1-3 that need to be adjusted for the bar stats. Please remember to do those. 

Thanks,

**Comment by kelvin-im** [comment]
Dynamicized, thanks for the help earlier @adavila17. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/316

**Comment by ValentineRain** [comment]
Hey, so I'm just now tuning in to the XML conversation. I agree that it makes sense to have an XML-less version for general use, since different sports will have different types of XML data and it's unreasonable to try to build for them all currently. I think that's what I'm testing now?

But UNCW did spefically ask for XML driven stats in the original request; I don't think it's good practice to strip the original feature request out in that case. So here's what I propose:

I'm going to test this template, and if it works out we'll go ahead and add it to media relations. We'll add a second template which is soccer-specific one.

**Comment by ValentineRain** [comment]
I'm reviewing this now and it looks good so far, but are there supposed to be two background dropzones? This doesn't look bad but it does differ from the preview.

![background photo space](https://user-images.githubusercontent.com/26412274/31026154-5088f422-a513-11e7-85ae-ea959ba807b5.png)

**Comment by ValentineRain** [comment]
Values of zero are not adjusting the stat bars.

![stat zero](https://user-images.githubusercontent.com/26412274/31026310-f4dc38cc-a513-11e7-80e5-b5312547c676.png)

**Comment by kelvin-im** [comment]
Alright, I've changed the dynamic code to allow zero values. Give it another go @ValentineRain.

**Comment by adavila17** [comment]
For this one I'm not even going to worry about xml. Let me copy it into soccer and have that be the one xml is added to.

**Comment by adavila17** [comment]
@kelvin-im 682 needs the dynamic code added to it and also xml integration.

**Comment by ValentineRain** [comment]
Hey, so that we can make this as clean as possible, I will make a new thread for 682.

**Comment by ValentineRain** [comment]
[Here's that thread](https://github.com/Aubron/scoreshots-templates/issues/89). I'll test the general one in this thread independently.

**Comment by adavila17** [comment]
coo coo ca-choo

**Comment by ValentineRain** [comment]
I think this one's ready to go. If nobody has any objections, here's what it looks like in the final. Ignore the weird symbol in the last stat, I was testing negative values for my own personal amusement.

![thing](https://user-images.githubusercontent.com/26412274/31197068-edeb95b8-a91d-11e7-93d9-0705bc7278ef.png)

We can merge this one.

**Comment by adavila17** [comment]
@ValentineRain I goofed and didn't read that a merge was needed. Ughhh.... any issues are on me. Sorry.

**Comment by ValentineRain** [comment]
Its all good. Any chance you can just remove the preview image until it's ready to go?

**Comment by lisajohnson11** [comment]
Tagging myself in this to notify GAC when it's complete.

**Comment by adavila17** [comment]
There's no remove preview image on my admin panel...... 😭

**Comment by ValentineRain** [comment]
Well, it's a non-issue this time because the template is ready to be merged anyway!

**Comment by ValentineRain** [comment]
It's been merged, closing this task. The Soccer specific one is still open! 
Thanks for your hard work everyone~
