### ISSUE TITLE
New Soccer StartingShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#78]
Minimal work take other template duplicate add in what's missing and go.

![ss_soccer_startingshot2](https://user-images.githubusercontent.com/26416133/30648394-ff544350-9deb-11e7-936c-ff2c37ec9507.png)

**Comment by adavila17** [comment]
Note for Dev:
Goalie starts at the bottom instead of at the top.

**Comment by Aubron** [comment]
Text is not quite centered.

**Comment by adavila17** [comment]
Temp ID: 676
It's centered in the code get over it.

Needs dynamic coding.

**Comment by kelvin-im** [comment]
I'll start on this one. By the way@adavila17, I'm concerned that **Berus** is part of the standing lineup...

**Comment by adavila17** [comment]
![main-qimg-827cb68056b7f3d565e96c3adf5e228d-c](https://user-images.githubusercontent.com/26416133/30655821-123fced0-9e00-11e7-9c6c-affd5b712053.jpg)

**Comment by kelvin-im** [comment]
This should be dynamic. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/295

**Comment by ValentineRain** [comment]
I really like this one, it's simple in a way I think we maybe don't have represented.
However, we need to remove the background step for this template since it doesn't do anything. Is that a design or development concern?

**Comment by kelvin-im** [comment]
@ValentineRain, removing the background step can probably be done on the Admin side.

**Comment by adavila17** [comment]
I can remove from admin side. We'll have to see if it throws a php error our way afterwards.

**Comment by adavila17** [comment]
Let's try to get this out today so if we can merge this and I'll get rid of the background step then we can retest.

**Comment by ValentineRain** [comment]
Everything else here is good then.

**Comment by ValentineRain** [comment]
Let's not add a preview image until the merge and background step hiding.

**Comment by Aubron** [comment]
Headed to live, leaving open for @adavila17 finalization.

**Comment by adavila17** [comment]
looks good works without background layer.

![loyetxr](https://user-images.githubusercontent.com/26416133/31026977-82a3fd28-a516-11e7-88bd-ee171d64d8a6.png)
