### ISSUE TITLE
GAC Template Requests 

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#80]
Eric from the Great American Conference has brought a few ideas for templates for conferences. 

1. Head to Head StatShot - ( I think I just saw this in the queue, but I'm adding it here anyway) 
He liked what he saw in the Baseball pitching head to head shot, but he'd like something more to cover all sports. Something he can use when two of their conference teams play each other. He said it didn't need to be XML capable, but more generic. Also, to include a "Who to Watch" portion. 

2. Top Performers of a day/week 
![screen shot 2017-09-26 at 11 00 39 am](https://user-images.githubusercontent.com/26416040/30868053-94d78ac2-a2ab-11e7-826f-07e6dc83d654.png)

3. Individual Standing for; golf, x country, track, swim meet, etc. Similar to this image. 
![screen shot 2017-09-26 at 11 13 34 am](https://user-images.githubusercontent.com/26416040/30868132-c719eeb2-a2ab-11e7-9176-77d15aa885f1.png)

**Comment by ValentineRain** [comment]
I'm going to insist after we have reviewed this that it be split into 3 separate tasks.

**Comment by Aubron** [comment]
For number 1, [see this thread](https://github.com/Aubron/scoreshots-templates/issues/77).

**Comment by Aubron** [comment]
For number 2, @lisajohnson11 will split into a new thread containing only it. Have fun @adavila17 .

For number 3, @rocksprings to provide golf XML file to Aubron, who is me. Will return later.

**Comment by rocksprings** [comment]
I shared the file with Aubron via email since Git doesn't support the specific file type.
Rick

**Comment by ValentineRain** [comment]
@lisajohnson11 , is everything that we needed to split off here accounted for?
If so, I'd like to close this task for housekeeping.

**Comment by lisajohnson11** [comment]
Yup! This is good to close. Thanks @ValentineRain
