### ISSUE TITLE
UNCW Ultrawide Starting Lineup for Baseball

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#81]
![utsa-baseball-lineup 1](https://user-images.githubusercontent.com/26412274/30921311-32865b72-a374-11e7-80f0-5a7cd3405e09.png)

### Requested by:
UNCW, Tom Riordan

## Template Description:

> I've attached several graphics that I found appealing for the baseball season. UTSA and Miss State are similar to the golf design you have now and Texas is similar too what you have already with the exception of being to highlight the pictured player with a solid bar under his name. The weekend rotation graphic would have to be able to be for three or four starting pitchers that weekend/series due to varying lengths of series.
>  
> Just wanted to pass along some ideas now so we could have some more choices come Feb. when softball and baseball begin.

## Dynamic Considerations:
N/A

**Comment by ValentineRain** [comment]
This is presumably a public template. Awaiting client response to that effect.

**Comment by adavila17** [comment]
get to this tomorrow.

**Comment by adavila17** [comment]
ran out of time still in progress need names and positions added but we can review.

![ss_baseball_startingshot5](https://user-images.githubusercontent.com/26416133/31183927-0880dbf4-a8f6-11e7-978a-0c9823f749fc.jpg)

**Comment by adavila17** [comment]
nvm SS meeting is tomorrow back to work.

**Comment by adavila17** [comment]
Ready:

![ss_baseball_startingshot5](https://user-images.githubusercontent.com/26416133/31184833-7a18f0a6-a8f8-11e7-943e-11c4f5c39552.jpg)

**Comment by Aubron** [comment]
Adam needs to add player cutouts to split up the gang. :((((((
Price and give to Aubron.

**Comment by adavila17** [comment]
this will be easy knocking out will have to hold if testing is done faster than preview image is corrected.

**Comment by adavila17** [comment]
ready to test temp ID: 689

**Comment by ValentineRain** [comment]
Did you or @Aubron ever sort out the player cutout thing? 
I'll be testing this next.

**Comment by ValentineRain** [comment]
The "Starting" text is in too low of a layer, the cutouts obscure it.

**Comment by ValentineRain** [comment]
![cutouts](https://user-images.githubusercontent.com/26412274/31407689-be6e86a0-add3-11e7-9153-96f4d981a96f.png)

**Comment by ValentineRain** [comment]
The "Lineup" text, as well as the colored lines above and below it, are defaulting to ScoreShots green.

No other issues; if you fix those it's good to go.

**Comment by adavila17** [comment]
updatedededededed
