### ISSUE TITLE
UNCW Starting Lineup Poster for Baseball

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#82]
![texas-baseba-lineup 1](https://user-images.githubusercontent.com/26412274/30921388-689ca630-a374-11e7-84d7-5800d13af247.png)

### Requested by:
UNCW, Tom Riordan

## Template Description:

> I've attached several graphics that I found appealing for the baseball season. UTSA and Miss State are similar to the golf design you have now and Texas is similar too what you have already with the exception of being to highlight the pictured player with a solid bar under his name. The weekend rotation graphic would have to be able to be for three or four starting pitchers that weekend/series due to varying lengths of series.
>  
> Just wanted to pass along some ideas now so we could have some more choices come Feb. when softball and baseball begin.

## Dynamic Considerations:
N/A

**Comment by ValentineRain** [comment]
Just noting again that they'd like a similar but distinct design. They do not own this.

**Comment by adavila17** [comment]
![ss_baseball_poster_startingshot](https://user-images.githubusercontent.com/26416133/30977019-4e36ad10-a444-11e7-8465-dbe653940ce2.jpg)

**Comment by Aubron** [comment]
👍

**Comment by adavila17** [comment]
test temp ID: 688

**Comment by ValentineRain** [comment]
Since you used the object's stroke for the white border around each position, it is actually impossible to match your preview image. In addition to being very difficult to click, if you succeed, there are no color controls. You can still change the actual blue diamond's color, however, so this is the closest you can get:

![highlight](https://user-images.githubusercontent.com/26412274/31408071-3e850688-add5-11e7-9182-41ee762e60d0.png)

I actually don't think this is a blocking issue but you might want to modify the preview image a hair.

**Comment by ValentineRain** [comment]
Finally, you might want to bring the "Team Name" layer above the others to make them easier to click on. I keep grabbing "Starting".

**Comment by ValentineRain** [comment]
No other issues, preview image please! No closey.

**Comment by adavila17** [comment]
updated and preview image added

**Comment by ValentineRain** [comment]
Sent! Closing!
