### ISSUE TITLE
UNCW Weekend Series Pitcher Template

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#83]
![missstate-baseball-rotation 1](https://user-images.githubusercontent.com/26412274/30921620-e7b7c9fe-a374-11e7-8e9e-240d6a7b8fd0.jpg)

### Requested by:
UNCW, Tom Riordan

## Template Description:

> I've attached several graphics that I found appealing for the baseball season. UTSA and Miss State are similar to the golf design you have now and Texas is similar too what you have already with the exception of being to highlight the pictured player with a solid bar under his name. The weekend rotation graphic would have to be able to be for three or four starting pitchers that weekend/series due to varying lengths of series.
>  
> Just wanted to pass along some ideas now so we could have some more choices come Feb. when softball and baseball begin.

## Dynamic Considerations:
N/A

**Comment by ValentineRain** [comment]
Looking for similar but distinct here. It's probably public.

**Comment by adavila17** [comment]
Fine tuning this...

![ss_baseball_pitcher_previewshot](https://user-images.githubusercontent.com/26416133/31093859-15a93d1a-a781-11e7-817e-10235fbd69c5.jpg)

**Comment by adavila17** [comment]
Ready for review:

![ss_baseball_pitcher_previewshotv2](https://user-images.githubusercontent.com/26416133/31177147-0b784d1e-a8e3-11e7-9148-42bb374c80ae.jpg)

**Comment by ValentineRain** [comment]
Also very fancy!

**Comment by Aubron** [comment]
@ValentineRain to contact UNCW, ask range of games in weekend series.

**Comment by adavila17** [comment]
@ValentineRain don't forget this because I may need to make room for 5 pitchers.

**Comment by ValentineRain** [comment]
Thanks for the reminder! Once I've gathered up the templates we owe them, I will ask in the same email.

**Comment by adavila17** [comment]
well the 4 variation is ready temp ID: 693

**Comment by ValentineRain** [comment]
Hey @adavila17 , here's Tom Riordan on the weekend series question (and also complimenting all of your other recent templates):

> Wow! Those look tremendous. A weekend series ranges from three to four games, five is unheard of (no one has enough pitching for that). For Division 1 schools the typical weekend is three games with some of the smaller D1's and the D2 and D3's playing four games (for economical reasons). Softball is the same with games on the weekend, ranging from 3-4 games, but often they use two starting pitchers only.
> 
> 
> Thanks for the great work!

**Comment by adavila17** [comment]
So next is dev team making a drop down labeled "Number of Pitchers"
Selector with range of 2-4
If Less than 4 remove right-most pitcher card and center remaining pitcher cards horizontally on the template.

**Comment by kelvin-im** [comment]
I'll work on this.

**Comment by kelvin-im** [comment]
Dynamic code is in. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/348

**Comment by ValentineRain** [comment]
Unless I've goofed something, it looks like the card elements in the background are not properly hiding when the dropdown is adjusted. There aren't any console errors that I can see in the console.

[Video](https://drive.google.com/a/imsports.com/file/d/0BwH5-fbQakiyNm50ZnlESl9oZjQ/view?usp=sharing).

**Comment by kelvin-im** [comment]
@ValentineRain, I am currently working on the issues with the logos that aren't aligning properly to the card elements; however, the card elements is a full-background image, rather than 4 seperate boxes. I won't be able to add dynamic code for the full image.

**Comment by ValentineRain** [comment]
I was worried that might be the case. We'll review it with @adavila17 when he returns, or might come up with a solution before that.

I don't see why we cant introduce separate elements for them but maybe there's some weird reason he did this.

**Comment by kelvin-im** [comment]
I've jumped the gun a bit on that last comment last week. After looking in the Admin section, those cards _are_ separated, and was able to hide them properly. The only thing that is a full-image is the light gradients on the boxes. 

The logos should now be properly aligned with it's background. Give it another go @ValentineRain when you get the chance. Sorry about that.

**Comment by ValentineRain** [comment]
No problem! I'm having a little trouble visualizing it cause I'm dumb so I'll take another look this afternoon!

**Comment by ValentineRain** [comment]
Everything beyond the gradient issue you mentioned looks great. Let's chat at some point today about what you need done in order to hide the gradients. Maybe it's something I can do!

Adjusting the prio on this one because the client is chomping at the bit to use it, hopefully by EOD if we can manage.

**Comment by ValentineRain** [comment]
@kelvin-im , you nailed it on the latest revision! Thanks for hiding those gradients.
This is 100% my fault, but it looks like there's one behavior I should have caught earlier and missed. When you reduce the teamcount, the number of logo zones is not decreasing within the logo step.

The result is that by double clicking from the media manager, you end up adding additional logos to spaces which should be hidden:

![untitled 2](https://user-images.githubusercontent.com/26412274/32244728-e68f24d2-be4f-11e7-8b1c-f9e845650e5a.png)

Sorry about this, definitely an oversight on my part. 
This should be the last item needing adjustment, unless I'm even worse at my job than I thought!

**Comment by ValentineRain** [comment]
Sorry, I hit the close button by mistake. Convenient, considering.

**Comment by kelvin-im** [comment]
Alright, the dropzones should now be hidden as well. Give it another test @ValentineRain.

**Comment by ValentineRain** [comment]
Perfect! Flagging this for a priority merge.
Thanks so much for your patience on this one, Kelvin! I know there was a lot of back and forth.

**Comment by adavila17** [comment]
sooooo......... we need the overlays on this. It could have waited. I will be adding in a moment.

**Comment by adavila17** [comment]
@kelvin-im  they will be labeled pitcher overlay 1-4 hide/show as needed.

**Comment by kelvin-im** [comment]
Done. Ready for review/testing.

PR: https://github.com/Aubron/scoreshots/pull/381

**Comment by ValentineRain** [comment]
> sooooo......... we need the overlays on this. It could have waited. I will be adding in a moment.
Sorry for rushing it along, but we were given a deadline while you were away. It couldn't have waited!

This looks great, and I've only got one concern, which is that it looks like the overlay is a couple of pixels off on the bottom-right of each box. It leaves a gap, which becomes more noticeable the further down you go.

![konatachan](https://user-images.githubusercontent.com/26412274/32453253-b7d00352-c2e9-11e7-9c33-19a0b817fb3a.png)

Everything else is perfect! I'm going to flag this as a design thing, as I think that's where it needs to go, but we might need to scooch some of them on the dev side as a result. I'm not 100% on the solution.

**Comment by adavila17** [comment]
sounds like it's off with the dynamicism......

**Comment by kelvin-im** [comment]
@ValentineRain, I've slightly adjusted the positioning of the dynamic code for the 2nd and 3rd pitchers. Give it another go, when you get the chance. Same PR as above.

**Comment by ValentineRain** [comment]
Thanks for looking at it, Kelvin! I'm gonna have @adavila17 take a look at it again tomorrow, since there's still a gap. It might be something on his end.

If not, it's not a huge deal. :DD

**Comment by adavila17** [comment]
Fixed.

**Comment by adavila17** [comment]
@kelvin-im  I increased the x value each overlay by .01 please make sure the 2 and 3 variants match up.

**Comment by adavila17** [comment]
![35p2ari](https://user-images.githubusercontent.com/26416133/32674373-ed2950d2-c620-11e7-8cf7-5c2face5aecf.png)

**Comment by ValentineRain** [comment]
I'm gonna go ahead and test this again, there might not be any need to redo anything at this point.

**Comment by ValentineRain** [comment]
Actually I squinted at it for a while and I honestly can't tell anymore, Kelvin can take a look after all. Ignore me!

**Comment by kelvin-im** [comment]
Was slightly off; I've went back and adjusted it. Seems fine on my end. Give it another test @ValentineRain, when you get the chance.

**Comment by ValentineRain** [comment]
Perfect!

**Comment by Aubron** [comment]
Merging!

**Comment by adavila17** [comment]
works was already available to clients
