### ISSUE TITLE
FSU Golf Round by Round Template Edit 

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#84]
FSU would like to be able to use this template for one round. 
So we need to include "1" under the "Number of Rounds".

They would also like to use this by Sunday because they have a tournament Sunday - Tuesday. 

![image](https://user-images.githubusercontent.com/26416040/30975853-47b03a54-a441-11e7-90c7-a604f9b5f189.png)

**Comment by kelvin-im** [comment]
I'll take care of it.

**Comment by kelvin-im** [comment]
Done. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/313

**Comment by ValentineRain** [comment]
Looks great!

**Comment by adavila17** [comment]
This needs a merge?!

**Comment by adavila17** [comment]
i would assume today but i can check their calendar please hold while your party is reached......

**Comment by lisajohnson11** [comment]
Yes, they need it today. Well actually Sunday, but since no one works over the weekend today would be fantastic :)

**Comment by adavila17** [comment]
yeah Women's team plays sunday

**Comment by Aubron** [comment]
Merge happening in the next couple of minutes. Please confirm preview image and close.

**Comment by adavila17** [comment]
Incorrect language. Should say rounds at the end of every selection. It's good other than that.

![ohzvkwv](https://user-images.githubusercontent.com/26416133/31026590-12694aaa-a515-11e7-8151-107d2ee3a24e.png)

**Comment by Aubron** [comment]
fixed via https://github.com/Aubron/scoreshots/pull/318 - please confirm preview image and close

**Comment by adavila17** [comment]
very good!
