### ISSUE TITLE
GAC Top Performers of the Day/Week 

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#85]
@adavila17 can you please design something wayyy prettier than this :) 

They're looking for something conferences can use to report the top players of a day or week for a specific sport. 

![image](https://user-images.githubusercontent.com/26416040/30983846-964bf3ca-a459-11e7-80b0-be5669e23eef.png)

**Comment by adavila17** [comment]
Hey look it's better it's like a designer actually designed something designy.

![ss_soccer_playershot2](https://user-images.githubusercontent.com/26416133/31181322-02a340d4-a8ef-11e7-8344-6267e46f772e.jpg)

**Comment by lisajohnson11** [comment]
Sent to the client for review.

**Comment by lisajohnson11** [comment]
Client is asking if this will convert well in resizing to a square for instagram since that is where they primarily use this template. @adavila17

**Comment by lisajohnson11** [comment]
@adavila17 to make a square version.

**Comment by ValentineRain** [comment]
Hey @lisajohnson11 , [here's the square version](https://github.com/Aubron/scoreshots-templates/issues/92). It's tested and everything, just needs to be made visible to clients.

Can I have a go at testing the rectangular one?

**Comment by adavila17** [comment]
Gotta make it. Sorry, the Square version was more urgent since the user wants templates for Instagram and Square is king there.

**Comment by adavila17** [comment]
Test Temp ID: 685

**Comment by ValentineRain** [comment]
Thanks, I'll add this to my stack today!

**Comment by ValentineRain** [comment]
The line dividing the photo from the right half stats is defaulting to ScoreShots green, rather than team coloration.

![team color](https://user-images.githubusercontent.com/26412274/31245553-b766a166-a9d8-11e7-8a63-2f5090916fee.png)

Actually I went ahead and edited that just now, setting the "Color Override" to "Primary". Sorry for stepping in your house; I just knew where this one was.

**Comment by ValentineRain** [comment]
No other issues. Preview image, and ship it.

**Comment by adavila17** [comment]
donzo preview added
