### ISSUE TITLE
GAC Game Recap with Individual Player Stats

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#86]
![screen shot 2017-09-28 at 4 01 16 pm](https://user-images.githubusercontent.com/26416040/30987818-4f7a3634-a466-11e7-9f4f-e14234a873c9.png)

Talked to @rocksprings about this. 

We need to come up with a way to make this applicable to multiple sports.

**Comment by adavila17** [comment]
well we haven't reviewed as a team. If xml integration then it'll be another case by case template just like the head to head template.

**Comment by lisajohnson11** [comment]
I think we talked about making this _without_ XML integration first. 
Just so conferences could make it for whatever they wanted.

**Comment by Aubron** [comment]
Final verdict: skip XML for now. Val is still great.
Try to complete in next 30 days.

**Comment by adavila17** [comment]
work in progress.

![ss_baseball_statshot3](https://user-images.githubusercontent.com/26416133/31290992-85fc143e-aa9c-11e7-8ee3-f10de8947c4a.jpg)

**Comment by rocksprings** [comment]
So you don't want any comments now, right?

**Comment by ValentineRain** [comment]
We should probably hold off until he's finished one, it could change substantially.

**Comment by adavila17** [comment]
![ss_baseball_finalshot13](https://user-images.githubusercontent.com/26416133/31548827-37c87786-affa-11e7-82fe-7ed49b9abf92.jpg)

**Comment by ValentineRain** [comment]
1) do both of them please
2) increase the box score space in the 2nd one.

**Comment by adavila17** [comment]
2nd design done:

![ss_baseball_finalshot8](https://user-images.githubusercontent.com/26416133/31821578-97fcf84c-b573-11e7-8f11-5c8a1e0b5beb.jpg)

**Comment by Aubron** [comment]
Go go power rangers.

**Comment by adavila17** [comment]
adding to engine.

**Comment by adavila17** [comment]
This is ready for testing Temp ID: 717

**Comment by ValentineRain** [comment]
Yep, this one works well. You can add a preview image, but since there's apparently a second template to this, lets not close it yet til that ones' done.

Once the preview image is in @lisajohnson11 might want to notify the GAC.

**Comment by lisajohnson11** [comment]
Yup, just drop me a note when it's all done. Thank you!

**Comment by adavila17** [comment]
preview added to temp id: 717

**Comment by adavila17** [comment]
Dis is ready to test Temp ID: 725

![ss_baseball_finalshot13](https://user-images.githubusercontent.com/26416133/32837277-e092a1d0-c9da-11e7-9432-81060bf511f0.jpg)

**Comment by ValentineRain** [comment]
This one's good, too. Can you add a preview image for it? I actually don't know where this template is located.

**Comment by adavila17** [comment]
preview added
