### ISSUE TITLE
Motorsports PreviewShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#87]
![ss_motorsports_previewshot2](https://user-images.githubusercontent.com/26416133/31016385-7557169c-a4f2-11e7-9d9c-57f55814ee98.jpg)

**Comment by Aubron** [comment]
To task: weekly lineup version of this.

**Comment by adavila17** [comment]
test temp ID: 692

**Comment by ValentineRain** [comment]
This one crashes on loading. @adavila17 , I vaguely recall you needing to do some ScoreShots Logo shenanigans? 

![php error](https://user-images.githubusercontent.com/26412274/31406924-19ca2408-add1-11e7-8435-ed31c9126b68.png)

**Comment by adavila17** [comment]
i think this php error is random everything was present logos/ss logo/sized background/color block/text and it still generated......

**Comment by adavila17** [comment]
anyway try again

**Comment by ValentineRain** [comment]
Whatever you did fixed it, the error is no longer present on any browser.
I'm not usually a fan of gradients but I dig this one.

Please add a preview image and it'll be ready to ship.

**Comment by adavila17** [comment]
preview addededededed
