### ISSUE TITLE
UNCW Starting Lineup With Player Images

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#88]
### Requested by:
UNCW, Tom Riordan

## Template Description:

> Hi Val,
> Can you add a template for a seven-player starting lineup based on the golf rectangular starting lineup? I saw Northwestern has this:
> 
> ![dlalpdvxkailicu](https://user-images.githubusercontent.com/26412274/31084249-eab76e3e-a761-11e7-964f-83d80f7639f9.jpg)
> 
> which is similar to the golf one we have now.
> 
> Thanks,

## Dynamic Considerations:
Just an idea, but if we were to provide a dropdown for the number of players to display, we could make one template which worked for multiple sports, instead of having to revisit this every time someone wants a new number.

**Comment by adavila17** [comment]
Is this for Volleyball cause it's like late in the season. Anyway on it tomorrow.

**Comment by ValentineRain** [comment]
It's for Volleyball, but I think we can make it for any sport if we include a number of players dropdown.

**Comment by adavila17** [comment]
In progress...

![ss_volleyball_startingshot](https://user-images.githubusercontent.com/26416133/31144346-7d24f5a6-a84e-11e7-9833-6a778fd48a23.jpg)

**Comment by adavila17** [comment]
Ready for review:

![ss_volleyball_startingshotv2](https://user-images.githubusercontent.com/26416133/31174218-afddbd36-a8d8-11e7-9813-fe24acae50da.jpg)

**Comment by ValentineRain** [comment]
I love the Ocracoke octopus.

**Comment by Aubron** [comment]
Will return to for dynamically sized version at later date.

**Comment by Aubron** [comment]
Val is so cool

**Comment by adavila17** [comment]
test temp ID: 691

**Comment by ValentineRain** [comment]
Did you mean to move the team logo to the left rather than over the text?
Still looks good so no issues there, just wondering since it'd changed since the preview.

![logo](https://user-images.githubusercontent.com/26412274/31406562-d771c292-adcf-11e7-8259-b72d7099f9ab.png)

PS I like cross-hatching

**Comment by ValentineRain** [comment]
This one is also good to go. It needs a preview image; please don't close it though, or I'll forget to notify the client.

**Comment by adavila17** [comment]
preview image added

**Comment by ValentineRain** [comment]
Sent! Closing.
