### ISSUE TITLE
Soccer, Head-to-Head Stat Preview Copy

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#89]
### Requested by:
UNCW, Eric Rhew
Probably public.

## Template Description:

> Tom Riordan and I were chatting this morning about graphics and one suggestion we were wondering about is the creation of a head-to-head team stats graphic that could be used before a game.
 >I believe you have a head-to-head individual stats graphic in baseball, but wanted to see if there was the possibility of using an XML file to create something on a team comparison for soccer.
> I am sure this could be something to use for other sports, but soccer was the first one we thought of.
 >I have attached a team stats XML file that STAT CREW produces. If you want to take a look at that file and see what data could be pulled from that, please feel free.
> I think keeping it to the basics (W-L record, Goals per game, Goals Against Average, Shots Per Game) would be best. Probably also having the option to upload each team’s XML file would be helpful as well.
> This is something that can be developed over time – not something we would need right away.
> Please let me know your thoughts when you have a chance.

## Dynamic Considerations:
Probably lots.

**Comment by ValentineRain** [comment]
This thread is for template 682, which Adam has made for this purpose. It is a copy of 680, but needs to be capable of accepting XML files. I've split this task to keep everything nice and neat.

**Comment by adavila17** [comment]
Pull XML team stats for:
Shots
Shots on Goal
Goals

Ignore pulling player stats are those can be changed a lot to reflect only positive stats. Also, a player who plays offense may be paired with a goalkeeper so this area will need to remain as a manual input field.

AD - Change stat 1 2 3 to targeted XML stats "Shots, Shots on Goal and Goals"

**Comment by adavila17** [comment]
DId my part.

**Comment by kelvin-im** [comment]
Template dynamic code has been copied over, and XML integration has been added. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/352

**Comment by ValentineRain** [comment]
Quick question about this; I uploaded[ this Team-based XML file](https://drive.google.com/a/imsports.com/file/d/0BwH5-fbQakiyeEpMNEg0UkplNTQ/view?usp=sharing) (which I think is the one you used to develop), and I get this result:

![proportion](https://user-images.githubusercontent.com/26412274/31793440-29779b38-b4ed-11e7-955f-d9062030e6e7.png)


One bar is significantly longer than the others, and its pair is scaled to it. I don't think they're supposed to extend that far. We might need to take another look at that one.

**Comment by ValentineRain** [comment]
A note for @adavila17 ; the background space at the bottom is not clipped to that space. It's filling the entire canvas, most of which is blocked.

**Comment by adavila17** [comment]
fixed on admin side should be good to go after that stat bar is fixed and merge is complete.

**Comment by kelvin-im** [comment]
Should be fixed now. The graph code was comparing the numbers as strings/words. Give it another go @ValentineRain, same PR as before.

**Comment by ValentineRain** [comment]
Issue is resolved! This is good to go. @lisajohnson11 Lisa mentioned she thought this template was supposed to have two background image spaces? If that's true it's something we can adjust after a merge; @adavila17 is out this week anyway.

**Comment by adavila17** [comment]
No. "Media Relations" category has two images for the top "Soccer" category only has one.

**Comment by Aubron** [comment]
Merging

**Comment by adavila17** [comment]
preview added
