### ISSUE TITLE
ScheduleShot 32 games

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#90]
@kelvin-im Add the dynamic code from template ID 657 to New template ID 683 category Basketball.

Thanks.

**Link to Admin creation:**
https://scoreshots.com/index.php/category/editor/2044/919/12/683

**Comment by adavila17** [comment]
I will work on the preview image here in a bit.

**Comment by kelvin-im** [comment]
Done. Ready for review/testing @ValentineRain. 

PR: https://github.com/Aubron/scoreshots/pull/333

**Comment by ValentineRain** [comment]
This is one for @adavila17 ; I think you left in one of your guidelines while making this. It starts off transparent but can be modified during the palette step. It's pink here.
![untitled](https://user-images.githubusercontent.com/26412274/31460461-8777d41e-ae94-11e7-947c-3efb8bce7678.png)

**Comment by ValentineRain** [comment]
Dynamic code works well here as well.

**Comment by adavila17** [comment]
line gone working on preview image in the morning.

**Comment by adavila17** [comment]
Here's the preview image we'll be using.

![ss_basketball_scheduleshot](https://user-images.githubusercontent.com/26416133/31503899-df72e848-af3e-11e7-8a9d-c1e876d21b49.jpg)

**Comment by adavila17** [comment]
Is this ready to merge? I've updated it and the preview image is ready to go.

**Comment by ValentineRain** [comment]
Yeah, we can merge this. I'll label the PR and stuff, sorry.

**Comment by Aubron** [comment]
Merged and awaiting PI

**Comment by adavila17** [comment]
preview image added
