### ISSUE TITLE
Individual Standing

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#91]
Template from this request:
https://github.com/Aubron/scoreshots-templates/issues/80

What they wanted:
![30868132-c719eeb2-a2ab-11e7-9176-77d15aa885f1](https://user-images.githubusercontent.com/26416133/31133347-2c0563d4-a82d-11e7-9627-3122b276faff.png)

My Design:
![ss_golf_standingshot](https://user-images.githubusercontent.com/26416133/31133098-88af2eb8-a82c-11e7-97f3-151b9cc20cd0.jpg)

**Comment by lisajohnson11** [comment]
Do I need to send this to the GAC or are we going to review it in a template meeting first?

**Comment by ValentineRain** [comment]
I think the most efficient thing to do is to send to them for approval in case they have things they want added, and just let them know we still need to review it internally so it might change a bit.

**Comment by lisajohnson11** [comment]
Okay, sent to the GAC!

**Comment by lisajohnson11** [comment]
Client asked if it could easily be switched from a team leaderboard to an individual player leaderboard and I assumed yes. He likes it!

**Comment by adavila17** [comment]
Yeah just change the language.

**Comment by Aubron** [comment]
Go ahead and design, should pass to development dynamic specs. We're thinking 1-10 in a dropdown.

**Comment by adavila17** [comment]
Ready for Dev team make dynamic:

Dropdown Labeled: Number of Teams
List: 1-10
Actions: Lower the number the small the box becomes center vertically in the template, please.

Temp ID: 687
Category: Golf - Rectangle

**Comment by kelvin-im** [comment]
I can take a crack at this one.

**Comment by kelvin-im** [comment]
Dynamicized. Thanks for the help earlier @adavila17. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/341

**Comment by ValentineRain** [comment]
I'd like to get @adavila17 to take a look at this and give me an idea of what he's intending at the lower teamcounts. The behavior that I'm seeing is that each step from 9 and below is adding an increasing about of blank space to the bottom of the box. Its texture also begins to spill outside of it.

I have a feeling this isn't what you want but if you could take a look and describe what it ought to be doing, that'd probably help!

![untitled 2](https://user-images.githubusercontent.com/26412274/31461212-d0accec6-ae96-11e7-8071-3122643b10a2.png)

**Comment by ValentineRain** [comment]
Oh yeah, also visible in that screenshot is a few instances of ScoreShots-green defaults.

**Comment by adavila17** [comment]
Yeah.... is there a way to mask/clip that graphic within the white opaque area while lowering the team count. Also too much space underneath when team count is 1.

**Comment by adavila17** [comment]
If no to the first I'll remove the graphic entirely I just like the texture it gave within that area.

**Comment by ValentineRain** [comment]
Just clarifying that the spacing begins as early as 9. I showed you 1 as it's the most dramatic.

**Comment by adavila17** [comment]
also 1 and team are above the clipped logo space by 20 or so px.

**Comment by ValentineRain** [comment]
Personally I'm a fan of the texture. If it can't be clipped maybe we should just hide it at 9 or less? So by default it's usable.

**Comment by kelvin-im** [comment]
@ValentineRain, I should be able to hide the graphic if 9 or less. However, shrinking it would be a no-go since the graphic is a full-screen image on the canvas. Will look into it and revise.

**Comment by ValentineRain** [comment]
Sounds good to me, thank you!

**Comment by kelvin-im** [comment]
Alright, the above changes have been added to the template. It should now hide the outer graphic if 9 or less teams. It should also properly shrink the box when number of teams is changed. Give it another test @ValentineRain. Same PR.

**Comment by ValentineRain** [comment]
Hi Kelvin! This is really close, but that extra space is still there as you shrink the box, from 6-9. 
![six](https://user-images.githubusercontent.com/26412274/31562123-42752264-b028-11e7-98cb-84efae366103.png)
5 and below, as well as 10, are perfect though!
![five](https://user-images.githubusercontent.com/26412274/31562128-45cfdbc0-b028-11e7-9dd6-e77bb43c4848.png)

**Comment by ValentineRain** [comment]
The texture is handled perfectly as well, by the way!

**Comment by kelvin-im** [comment]
Alright, went back and adjusted teams 6-9 to get rid of that excess spacing. Give it another go @ValentineRain.

**Comment by ValentineRain** [comment]
Yep, this is good! Thank you!

**Comment by ValentineRain** [comment]
Will update when it's been merged so we can finalize.

**Comment by Aubron** [comment]
Merged and awaiting PI

**Comment by adavila17** [comment]
preview added
