### ISSUE TITLE
GAC Performers of the Week - Square

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#92]
![ss_soccer_statshot3](https://user-images.githubusercontent.com/26416133/31188129-e7d18eec-a901-11e7-8580-2088b507fb77.jpg)

**Comment by lisajohnson11** [comment]
Approved.

**Comment by adavila17** [comment]
Val test temp ID: 684 media relations category.

**Comment by ValentineRain** [comment]
This one is good to go.

**Comment by ValentineRain** [comment]
Needs a preview image!

**Comment by adavila17** [comment]
preview added
