### ISSUE TITLE
Soccer StartingShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#93]
Additional templates to add:

![ss_soccer_startingshot2](https://user-images.githubusercontent.com/26416133/31189189-5be316fe-a905-11e7-9f28-88a9d5aeb054.jpg)

**Comment by Aubron** [comment]
@adavila17 should duplicate this thread, make a variation that makes more room for right-hand photo. Play with it a bit!

**Comment by adavila17** [comment]
make template dynamic like square variation additional add primary color to white stroke where "starting XI" sits inside of.

Temp ID: 690

**Comment by kelvin-im** [comment]
Dynamicised. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/350

**Comment by ValentineRain** [comment]
Needs to be merged. Once it has we'll add a preview image.

**Comment by Aubron** [comment]
Merged and waiting for PI

**Comment by adavila17** [comment]
preview image added
