### ISSUE TITLE
PollShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#94]
New PollShot:

![ss_mediarelations_pollshot](https://user-images.githubusercontent.com/26416133/31191047-e53fde5a-a90a-11e7-805c-397c4078e7a1.jpg)

**Comment by adavila17** [comment]
ready to test temp ID: 686

**Comment by ValentineRain** [comment]
Good to go. Preview image time!

**Comment by adavila17** [comment]
preview image added
