### ISSUE TITLE
MiLB Called Up Template 

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#95]
![screen shot 2017-10-05 at 3 46 17 pm](https://user-images.githubusercontent.com/26416040/31249192-677838b6-a9e4-11e7-8a66-dd7f33908880.png)
 No client has asked for this, but in doing some reserach for the marketing funnel I've noticed they use something like this alot. It would be really good to beef up our baseball category especially heading into the winter meetings. I'm noticing the Jumbo Shrimp and the Rubber Ducks rarely use our stuff and if they do it's one or two templates. I'd like to have wide variety heading into December. Just my thoughts.

**Comment by Aubron** [comment]
Broaden to include promotional images as well.

**Comment by adavila17** [comment]
Maybe this. If not I'll cook up another version.

![ss_baseball_playershot_1v2](https://user-images.githubusercontent.com/26416133/31457308-601961bc-ae8a-11e7-8c8a-01fb4963a7e6.jpg)

**Comment by ValentineRain** [comment]
@rocksprings to add stat suggestions. 
Reverse space devoted to player image versus stats.

**Comment by rocksprings** [comment]
Bill/Adam: A few changes for us to review. . .

1. Reduce the horizontal spacing of the overlay to not more than half of the graphic.
2. Add the word "Promoted" across the top half somewhere (even if you don't like the idea of doing this).
3. Make stat categories as noted here: Year Drafted, Position, Batting Ave, Home Runs (2 words) and RBI.
4. Take out the wording at the bottom.

**Comment by adavila17** [comment]
![ss_baseball_playershot1_v3](https://user-images.githubusercontent.com/26416133/31718132-babccd64-b3dc-11e7-8e31-d3871065af0b.jpg)

**Comment by rocksprings** [comment]
How about the RBI stat?

**Comment by adavila17** [comment]
oops, somehow I missed that added in.

![ss_baseball_playershot1_v3](https://user-images.githubusercontent.com/26416133/31720589-f1d72ca6-b3e4-11e7-9c9e-c0afbd51e07f.jpg)

**Comment by rocksprings** [comment]
Con mucho gusto

**Comment by Aubron** [comment]
teen titans go

**Comment by adavila17** [comment]
Ready for testing Temp ID: 709

**Comment by ValentineRain** [comment]
Judging by your preview image, the boxes behind the date as well as each stat are supposed to be quite a bit darker, and more transparent. 

![comp](https://user-images.githubusercontent.com/26412274/32452025-62fd34b0-c2e6-11e7-8079-35fb0e5032df.png)

**Comment by ValentineRain** [comment]
I don't think this needs to be fixed, but just so we're all aware, there are a lot of cutouts the name text wont work for because it will be completely obscured no matter the placement.

![thingyu](https://user-images.githubusercontent.com/26412274/32452218-ec0ef77a-c2e6-11e7-88a6-49ab1c313bfe.png)


I guess the client can always add a new text layer on top of it.

**Comment by ValentineRain** [comment]
Finally; that ScoreShots logo is even smaller than in the preview. It can't be read at normal resolutions. 
Which is sort of a weird problem to have, but, yeah, bump that up?

**Comment by adavila17** [comment]
Fixed everything

**Comment by ValentineRain** [comment]
Yep, this is good.

**Comment by adavila17** [comment]
preview added closing
