### ISSUE TITLE
Matchup previewshot graphic

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#96]
![preview-full-previewshot option](https://user-images.githubusercontent.com/26416133/31287865-c1c7c88e-aa90-11e7-922c-6547995e0528.jpg)

**Comment by adavila17** [comment]
![ss_football_previewshot12](https://user-images.githubusercontent.com/26416133/31394425-431b1f9e-adac-11e7-8151-7796c13dfc52.jpg)

**Comment by ValentineRain** [comment]
Good to go, consider more balanced layout if requested by folks later.

**Comment by adavila17** [comment]
ready to test temp ID: 695

**Comment by ValentineRain** [comment]
Two of the items on this template are defaulting to SS Green.
![ssgreen](https://user-images.githubusercontent.com/26412274/31560972-69b9c7ac-b024-11e7-9420-8f587d6183ce.png)

**Comment by ValentineRain** [comment]
We also need to remove the background step from this template.

**Comment by ValentineRain** [comment]
I'm not sure what's happening with the white lines on the left.
When I try to alter all of the white items on the canvas (in this case, to red), I get an effect like this.

![redline](https://user-images.githubusercontent.com/26412274/31561091-c4d239f8-b024-11e7-87f9-4fb41ab77f6f.png)

I think the items are either not lined up, or they aren't all editable.

**Comment by ValentineRain** [comment]
That's all!

**Comment by adavila17** [comment]
fixed

**Comment by ValentineRain** [comment]
Confirmed all of this is good to go!
It needs a preview image. Who requested this, by the way, so we can let them know it's ready?

**Comment by adavila17** [comment]
this was a Rick request.

**Comment by adavila17** [comment]
preview added
