### ISSUE TITLE
Villanova Meet Day, Swimming

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#98]
### Requested by:
Michelle Ruel, Villanova

## Template Description:

![scoreshots swimming example](https://user-images.githubusercontent.com/26412274/31404445-17d1a7ae-adca-11e7-8f35-04820bfcff4d.JPG)

Michelle would like a template similar to what we're offering here, but themed to match the previous Villanova template branding that you did. Here's a link to that [old thread](https://github.com/Aubron/scoreshots-templates/issues/63), where I think you can find the fonts and other assets if you still need them!

She has a couple of edits she'd like to make to it to better fit their needs as well. Primarily, while she'd like to keep a space for the Villanova logo, she would like to _not_ dedicate any space for opponent logos. To quote her:

> I have add three examples from scoreshots that David and I liked but would love to see them more customized to us.  One off the biggest problem that we have with these sports is that we don’t have a lot of action shots.  So many of the photos in the background will have to be generic which causes us some issues.
>  
> For the general design we would like it similar to the style of our last two graphics we had made, we are keeping that same look this year.   Also if you can set the fonts to ours that would be great.
>  
> Please let me know if you need anything else from me, I can send along action shots to plug in if you need them.

## Dynamic Considerations:
None.

**Comment by ValentineRain** [comment]
I've reached out to her for a desired completion date, and also some action shots that you can use. Otherwise you can refer to her dropbox for assets!

**Comment by ValentineRain** [comment]
Updated with the correct example template. My bad!

**Comment by ValentineRain** [comment]
Hey, real quick update on what the client wants. I got a due date, but also another note:

> The only change, and this just was something David and I just realized, is for “Meet Day” if you can have two photos in the background.  This way for men’s and women’s meets we can have both in the background. 

>  And if we can have the “meet day” by the 20th ... that would be great.

**Comment by adavila17** [comment]
ready for client

![villanova_swimming_previewshot1](https://user-images.githubusercontent.com/26416133/31496507-ad82b184-af29-11e7-8ae8-9f4be140073b.jpg)

**Comment by adavila17** [comment]
How's bout dis wan?

![villanova_swimming_previewshot2](https://user-images.githubusercontent.com/26416133/31505993-30c309e4-af44-11e7-9178-e101c80a138e.jpg)

**Comment by ValentineRain** [comment]
I like it, I'll send it their way for approval too!

**Comment by ValentineRain** [comment]
Sent it to them. Still haven't heard back from them!

**Comment by ValentineRain** [comment]
Hey @adavila17 , instead of letting this run down to the wire, let's just go ahead and push forward on this Meet Day template. It has the soonest due date.

If they have problems with it, we can tweak it. I just don't want to leave it to the last minute because they won't approve the thing.

**Comment by adavila17** [comment]
I'll "dive" right into it.

**Comment by adavila17** [comment]
Ready to test temp ID: 698

**Comment by ValentineRain** [comment]
Villanova has reviewed this one and they'd like one change before I test it. 

> Hi Val,
>  
> Is there any way the middle part can be a little smaller in the two photo one, David and I think that if the text is moved up a little and the gray area made smaller it might give more room of the photos on the side.
>  
> Thanks,
>  
> Michelle

**Comment by adavila17** [comment]
![villanova_swimming_previewshotv2](https://user-images.githubusercontent.com/26416133/31716949-12a648ca-b3d8-11e7-80ec-d184f5b5f542.jpg)

**Comment by adavila17** [comment]
![villanova_swimming_previewshotv3](https://user-images.githubusercontent.com/26416133/31783874-c3e81d02-b4cd-11e7-9fcd-0f45b81fe03b.jpg)

**Comment by adavila17** [comment]
test temp ID: 698

**Comment by ValentineRain** [comment]
Still playing with this, but there's only one background space here.
Also the hashtag defaults to a different position than in the preview.

![vg](https://user-images.githubusercontent.com/26412274/31784766-e50bf85c-b4d0-11e7-87dd-85e651d2d90e.png)

**Comment by ValentineRain** [comment]
It looks like the drop shadow might be off a little too, or else this is just because the font is different. Can you tell me if this is what you intended?

![shadow](https://user-images.githubusercontent.com/26412274/31784897-590bfed2-b4d1-11e7-8094-c127239ef599.png)

**Comment by ValentineRain** [comment]
No other problems. Let me know when to retest~

**Comment by adavila17** [comment]
It's how Villanova set's their drop shadows. 0 on X-axis and -4 on Y-axis. Anyway forgot to unclick the 1 background thing.

**Comment by ValentineRain** [comment]
Fixed!
I'll add the preview image on this one and let them know they can use it.
