### ISSUE TITLE
Villanova Team-Oriented FinalShot, Swimming

### ISSUE THREAD

**Issue by ValentineRain** [Aubron/scoreshots-templates#99]
### Requested by:
Michelle Ruel, Villanova

## Template Description:

![unnamed](https://user-images.githubusercontent.com/26412274/31404271-8d4d9b56-adc9-11e7-9529-0e1836d28700.jpg)

Similar to this task, Villanova would like a template similar to the above, but with their branding. They've also specified that they would like this results template to be team-oriented, and that they intend to use it primarily on Twitter (whatever considerations that implies).

You can find their assets in that other thread. I've contacted them for a desired due date, will update when I know more.

## Dynamic Considerations:
None.

**Comment by ValentineRain** [comment]
Hey, apparently these are being used not just for swimming, but also track, tennis, and maybe rowing? So the stats should maybe be generic.

Also they gave you these photos to use if you want.

![ak7z5043](https://user-images.githubusercontent.com/26412274/31461524-c6bc4d50-ae97-11e7-952f-09180847121f.JPG)
![pierce1](https://user-images.githubusercontent.com/26412274/31461525-c6ca6b60-ae97-11e7-8816-c550e2bff15f.JPG)

**Comment by adavila17** [comment]
![villanova_swimming_finalshot_rectangle1](https://user-images.githubusercontent.com/26416133/31462417-b8cdba14-ae9a-11e7-8ec7-0b802013e2ab.jpg)

**Comment by adavila17** [comment]
ready for client

**Comment by adavila17** [comment]
test temp ID: 701

**Comment by ValentineRain** [comment]
This one is also ready for a preview image!

**Comment by adavila17** [comment]
preview added
